### ISSUE TITLE
Enable madvise() usage on Unix and Cygwin

### ISSUE THREAD

**Issue by ivmai** [ivmai/bdwgc#100]

**Comment by chenzhuoyu** [comment]
Please implement this

**Comment by ivmai** [comment]
madvise(MADV_DONTNEED) is needed on some targets if GC_unmap relies on mprotect(PROT_NONE) to return the memory to OS - this will be fixed in issue #420 (the fix is needed for v8.2.0 and maybe for v8.0.0 but not older versions).

**Comment by ivmai** [comment]
About madvise(MADV_FREE):

As said in [golang issue](https://github.com/golang/go/issues/23687):
A potentially faster alternative is MADV_FREE, available since linux 4.5 (and already used for bsd). The mechanism is very similar, but the page fault will only be incurred if the kernel, between the call to madvise and the first access, decides to reuse that memory for something else.
...
However:
First, while it is somewhat cheaper then MADV_DONTNEED, it is not that cheap, since page tables have to be walked and modified. It doesn't get reflected in RSS and thus interaction of this and memory reclaim facility in kernel, especially in settings with heavy usage of control groups isn't trivial. And also defaults about how this memory is preferred compared other memory during reclaim is also not entirely clear.
(See also: https://go-review.googlesource.com/c/go/+/267100/)

Considering this golang discussion, I don't think it is worth to use madvise(MADV_FREE) in bdwgc.
