### ISSUE TITLE
HP-UX 11 fails in GC_push_regs

### ISSUE THREAD

**Issue by ivmai** [ivmai/bdwgc#109]
HP-UX 11.00 with the vendor cc fails in gctest with the message:
Perhaps GC_push_regs was configured incorrectly?

See details in http://article.gmane.org/gmane.comp.programming.garbage-collection.boehmgc/4901/

**Comment by ivmai** [comment]
@brhaible Is this still reproducible?

**Comment by ivmai** [comment]
> See details in http://article.gmane.org/gmane.comp.programming.garbage-collection.boehmgc/4901/

Bruno Haible wrote on 2012-01-18:
gc-7.2alpha6, built on HP-UX 11.00 with the vendor cc, fails 1 of 6 tests:
```
Switched to incremental mode
Emulating dirty bits with mprotect/signals
Apparently failed to mark from some function arguments.
Perhaps GC_push_regs was configured incorrectly?
Test failed
/bin/sh: 13551 Abort(coredump)
FAIL: gctest
```
This sounds worrying. Is it already known?

**Comment by danglin44** [comment]
I tested builds on HP-UX 11.11 32-bit at trunk and commit 569490aadc50550354d8dc31601d24a3aa8542a9.

Both build successfully with gcc-8.5.

Tests all pass when the test suite runs through, but often the gctest (particularly on trunk) and the threadleaktest
hang.  Ran the tests several times on both builds.

-- 
John David Anglin  ***@***.***

**Comment by ivmai** [comment]
Good. Thank you
