### ISSUE TITLE
Mingw: gctest (compiled with PARALLEL_MARK) either crashes or deadlocks

### ISSUE THREAD

**Issue by ivmai** [ivmai/bdwgc#119]
How to reproduce:
* gctest launched in gdb with breakpoint at GC_mark_local
* after several breakpoint hits it crashes with the messages "Caught ACCESS_VIOLATION in marker; memory mapping disappeared" and "Tried to start parallel mark in bad state", or enters a deadlock.

**Comment by adrpo** [comment]
Isn't this the same or similar to: #81?

**Comment by adrpo** [comment]
It seems this can be fixed if we use the win32 threads for parallel marking even when pthreads support is selected via `--enable-threads=posix`. 

One can disable pthreads parallel marking in win32_thread.c via an ifdef for __MINGW32__:
```
# if defined(GC_PTHREADS) && !defined(GC_PTHREADS_PARAMARK)
    /* Use pthread-based parallel mark implementation.    */
#if !defined(__MINGW32__)
#   define GC_PTHREADS_PARAMARK
#endif

# endif
```

**Comment by adrpo** [comment]
With this workaround all tests are passing:
```
PASS: cordtest.exe
PASS: gctest.exe
PASS: leaktest.exe
PASS: middletest.exe
PASS: smashtest.exe
PASS: hugetest.exe
PASS: realloc_test.exe
PASS: staticrootstest.exe
PASS: threadleaktest.exe
PASS: threadkey_test.exe
PASS: subthreadcreate_test.exe
PASS: initsecondarythread_test.exe
PASS: disclaim_test.exe
PASS: disclaim_bench.exe
============================================================================
Testsuite summary for gc 7.5.0
============================================================================
# TOTAL: 14
# PASS:  14
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
```

**Comment by ivmai** [comment]
Yes, this seems to duplicate #81 
I will apply the workaround.
