### ISSUE TITLE
"getcontext failed" in a 32-bit Docker container

### ISSUE THREAD

**Issue by andyli** [ivmai/bdwgc#133]
With a `Dockerfile` as follows:

```
# FROM ubuntu:trusty # for reference, the 64-bit "ubuntu:trusty" works correctly

FROM osrf/ubuntu_32bit:trusty

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
		git \
		build-essential \
		libtool \
		pkg-config \
		autoconf \
		automake \
	&& rm -r /var/lib/apt/lists/*

RUN git clone git://github.com/ivmai/bdwgc.git /bdwgc

WORKDIR /bdwgc

RUN git clone git://github.com/ivmai/libatomic_ops.git

RUN autoreconf -vif

RUN automake --add-missing

RUN ./configure

RUN make

CMD make check
```

Build it:
```
$ docker build . -t gc_docker
```

Run it:
```
$ docker run -it gc_docker bash
root@21a11fe7e22e:/bdwgc# make check
...
============================================================================
Testsuite summary for gc 7.5.0
============================================================================
# TOTAL: 14
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  14
# XPASS: 0
# ERROR: 0
============================================================================
See ./test-suite.log
Please report to bdwgc@lists.opendylan.org
============================================================================
make[3]: *** [test-suite.log] Error 1
make[3]: Leaving directory `/bdwgc'
make[2]: *** [check-TESTS] Error 2
make[2]: Leaving directory `/bdwgc'
make[1]: *** [check-am] Error 2
make[1]: Leaving directory `/bdwgc'
make: *** [check-recursive] Error 1
root@21a11fe7e22e:/bdwgc# cat test-suite.log
================================
   gc 7.5.0: ./test-suite.log
================================

# TOTAL: 14
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  14
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: cordtest
==============

getcontext failed: Use another register retrieval method?

FAIL: gctest
============

getcontext failed: Use another register retrieval method?

FAIL: leaktest
==============

getcontext failed: Use another register retrieval method?

FAIL: middletest
================

getcontext failed: Use another register retrieval method?

FAIL: smashtest
===============

getcontext failed: Use another register retrieval method?

FAIL: hugetest
==============

getcontext failed: Use another register retrieval method?

FAIL: realloc_test
==================

getcontext failed: Use another register retrieval method?

FAIL: staticrootstest
=====================

getcontext failed: Use another register retrieval method?

FAIL: threadleaktest
====================

getcontext failed: Use another register retrieval method?

FAIL: threadkey_test
====================

getcontext failed: Use another register retrieval method?

FAIL: subthreadcreate_test
==========================

getcontext failed: Use another register retrieval method?

FAIL: initsecondarythread_test
==============================

getcontext failed: Use another register retrieval method?

FAIL: disclaim_test
===================

getcontext failed: Use another register retrieval method?

FAIL: disclaim_bench
====================

getcontext failed: Use another register retrieval method?
```

**Comment by andyli** [comment]
It works correctly if it is built with `NO_GETCONTEXT`. Is it possible for the config script to add that define automatically by checking `getcontext`?

**Comment by ivmai** [comment]
I think it should be possible. Could you please send the patch? (There is a difficulty that some clients do not use make, so, some config params should be determined during compilation.)
--

Tue, 09 Aug 2016, 07:19 +03:00 from Andy Li <notifications@github.com>:
It works correctly if it is built with NO_GETCONTEXT. Is it possible for the config script to add that define automatically by checking getcontext?

**Comment by ivmai** [comment]
I wonder what is errno value after getcontext failure?

**Comment by ivmai** [comment]
Maybe it is better to fix the Docker itself? Right now I don't think checking getcontext is implemented in configure is a good choice because it won't help if you compile bdwgc outside docker and run inside it.
Another opportunity is try other methods of saving regs in case of getcontext failed during bdwgc execution.

**Comment by andyli** [comment]
Thanks for the quick reply!

> what is errno value after getcontext failure?

`getcontext(&ctxt)` returns `-1`. `errno` is `1`.

> Maybe it is better to fix the Docker itself?

I have no idea who is responsible for the bug, Docker, the base container image, or bdwgc. But I think it is relatively easy to workaround in the bdwgc code base.

I agree having a fallback mechanism in run-time is better then checking getcontext during config.

**Comment by okuoku** [comment]
> I have no idea who is responsible for the bug, Docker, the base container image, or bdwgc

... or the Kernel; it seems the problem only occur on i686 binary on amd64 kernel -- I haven't tried yet without Docker for amd64 kernel though.
IIRC, Fedora23 was OK(with Ubuntu trusty image) and Fedora24 has this problem.

**Comment by okuoku** [comment]
Uh, it seems the problem belongs to Docker.. running the same binary which was built inside Docker(osrf/ubuntu_32bit:trusty) on the host directly, it runs successfully.

I can reproduce the problem with official `ubuntu:trusty` image and the binary built on `osrf/ubuntu_32bit:trusty` on Ubuntu 16.04 host.

Dockerfile:
```
FROM ubuntu:trusty
RUN apt-get update && apt-get install -y lib32z1
COPY libgc.so.1 /
COPY gctest /
```

Transcript:
```
# docker run -it --rm  gc_test bash
root@f0a1905f64b7:/# LD_LIBRARY_PATH=. ./gctest
getcontext failed: Use another register retrieval method?
Aborted (core dumped)
```

**Comment by ivmai** [comment]
Please test a62e6fc

**Comment by andyli** [comment]
I confirm it works now. Thanks a lot!
