### ISSUE TITLE
Platforms where threads suspend is not available

### ISSUE THREAD

**Issue by tomspilman** [ivmai/bdwgc#138]
I'm porting to a platform where thread suspension is not available.  

Does the GC have an existing features to help deal with these sorts of platforms?  Or is it entirely up to me to develop a system for this... likely sprinkling a bunch of suspension checks in my code?

Any other suggestions on how to support multithreaded platforms like this?

**Comment by ivmai** [comment]
Several suspension implementations exist in GC depending the target: Windows, Darwin, OpenBSD (old versions), NaCl, Unix (other than Cygwin, Darwin, OpenBSD).
If your target has signals (and ability to send it to another thread), then look at Unix variant of thread suspension.
