### ISSUE TITLE
MAX_HEAP_SECTS too little?

### ISSUE THREAD

**Issue by tholp** [ivmai/bdwgc#143]
If I create a program that tries to exhaust the memory then it dies with the "Too many heap sections", rather than a heap exhaustion.

We have defined LARGE_CONFIG and for 64bit platform the comment says that it should give an overflow at "roughly 128 GB":

```
#ifndef MAX_HEAP_SECTS
# ifdef LARGE_CONFIG
#   if CPP_WORDSZ > 32
#     define MAX_HEAP_SECTS 8192        /* overflows at roughly 128 GB  */
#   else
#     define MAX_HEAP_SECTS 768         /* Separately added heap sections. */
#   endif
# elif defined(SMALL_CONFIG) && !defined(USE_PROC_FOR_LIBRARIES)
```

The HBLKSIZE is 4KB and each heap section will contain between 64 (MINHINCR) and 4096 (MAXHINCR) heap blocks.

As far as I can see this means that the "overflow" will occur at some point between 2 GB and 128 GB (which is not quite the same as "roughly 128 GB").

I can of course set the MAX_HEAP_SECTS larger myself, but isn't this a general problem that everybody will have to address.

**Comment by hboehm** [comment]
Presumably most of them are MAXHINCR sized, so this happens nearer 128GB?

I agree that the constants should be increased, or there should be a larger
config.

On Thu, Feb 2, 2017 at 8:14 AM, Thomas Linder Puls <notifications@github.com

**Comment by tholp** [comment]
I do not know what influences on the size of the sections, nut in a little simple test the program broke down around 12GB.  So, I have chosen to use 10 times larger numbers (81920 and 7680 respectively), but I do not feel that this choice is very-well founded.

**Comment by ivmai** [comment]
Please make a pull request.

**Comment by ivmai** [comment]
Related pull request: #153
