### ISSUE TITLE
Manually preventing/triggering collection (benchmarking)

### ISSUE THREAD

**Issue by arximboldi** [ivmai/bdwgc#145]
Hi!

I am benchmarking some components that use `libgc`.

It would be nice to be able to measure the effects of the GC sepparately. Having the GC trigger in the middle of the benchmarks adds too much noise. For this, I would like to disable the GC (stop it from automatically triggering) and the manually trigger it after a benchmark is run. Is there a way to do this?

I considered playing with `GC_free_space_divisor`, `GC_non_gc_bytes` and `GC_expand_hp()`, but I would like to learn if there are any established best practices to achieve sound benchmarking results with `libgc`.

**Comment by hboehm** [comment]
I believe that GC_disable() / GC_enable can still be used to turn GC on and
off. But it will depend on the benchmark as to whether that's a reasonable
thing to do. If there's enough allocation during the benchmark, the heap
may grow substantially, potentially drastically altering application
locality. If it grows enough to start paging, the results are unlikely to
be meaningful.

**Comment by arximboldi** [comment]
I missed that those functions exist because they are not mentioned in the README, but I see in the headers that they are still available. There is also `gc_gcollect`, which I guess I can still call between runs to keep memory under control. I believe that due to the nature of my benchmarks, this might just work, but I should experiment.

Thanks a lot for the quick reply and for all these years dedicated to advancing our field, I was surprised and honored to get a reply from Boehm himself :-)
