### ISSUE TITLE
Does BDWGC support user-level context switching with linux makecontext/swapcontext?

### ISSUE THREAD

**Issue by sisarolo** [ivmai/bdwgc#150]
Hi, I am using user-level context switching with linux `makecontext` and `swapcontext` for a discrete event simulation to schedule several user-level threads using only one pthread. Before, I was using several pthreads and BDWGC was working perfectly fine. Now, I get a segfault in `GC_push_all_eager`, when a `GC_gcollect` is triggered. For each user-level thread, a stack is allocated - not with `GC_malloc`, but with normal `malloc`. Could this segfault happen, because these user-level stacks are not known to the BDWGC and how could I possibly solve this issue?

**Comment by ivmai** [comment]
Try to use GC_malloc_uncollectable instead of malloc to allocate user-space stack.

**Comment by sisarolo** [comment]
The segfault still happens.

**Comment by sisarolo** [comment]
I created a small program, which reproduces the segfault.

    #include <stdio.h>
    #include <stdlib.h>
    #include <ucontext.h>
    #include <gc.h>

    #define STACK_SIZE 1024*64

    ucontext_t child, parent;

    void threadFunction() {
        GC_gcollect();

        printf("Child: Switch to parent\n");
        swapcontext( &child, &parent );
        printf("Child: Switch to parent\n");
        swapcontext( &child, &parent );
    }

    int main() {
        GC_INIT();
        void *mem = GC_MALLOC(1000);

        getcontext( &child );
        child.uc_link = 0;
        child.uc_stack.ss_sp = GC_MALLOC_UNCOLLECTABLE( STACK_SIZE );
        child.uc_stack.ss_size = STACK_SIZE;
        child.uc_stack.ss_flags = 0;
        if ( child.uc_stack.ss_sp == 0 ) {
            perror( "malloc: Could not allocate stack" );
            exit( 1 );
        }
        makecontext( &child, &threadFunction, 0);

        printf("Parent: Switch to child\n");
        swapcontext( &parent, &child );
        printf("Parent: Switch to child\n");
        swapcontext( &parent, &child );

        GC_FREE( child.uc_stack.ss_sp );
        return 0;
    }

**Comment by hboehm** [comment]
The likely problem is that the collector will try to scan the region
between your stack pointer and the base of what it thinks the current stack
is, which is actually likely to be the base of the main stack. Oops.

There's probably not a good way around this other than to actually teach
the collector how to find the base of your stacks.

**Comment by sisarolo** [comment]
Thank you for that hint! I have an idea about a possible solution without changing anything at the BDWGC. The pthread that executes user-space threads has to be unregistered from the BDWGC so that the current stack pointer can change as it likes and collection does not fail. Non-active user-space stacks are added as root segments from stack pointer to base. The active user-space stack has to be fully added as root segment. In case of a context switch, the root segments have to be adapted. Only one additional registered pthread is required, which is anyway existing in my use case. Does this sound feasible or are there probably unseen pitfalls?

**Comment by sisarolo** [comment]
Ok, the idea above didn't work out. The solution was exactly what @hboehm said. I had to change the location where BDWGC tries to find the base of the current stack. My solution now was to allocate all user-space stacks with GC_malloc_uncollectable and then to check whether the current stack pointer points to somewhere in the GC heap with GC_is_heap_ptr(lo), if yes then hi = GC_base(lo) + STACK_SIZE. Thank you again for your help.

**Comment by ivmai** [comment]
> The pthread that executes user-space threads has to be unregistered from the BDWGC so that the current stack pointer can change as it likes and collection does not fail.

As I wrote in #150, there's another way of dealing with user-level context switching (known as coroutines or fibers): manually call GC_[un]register_my_thread (at the beginning and end of the coroutine) and invoke context switching by GC_do_blocking (e.g. GC_do_blocking(&yield, 0)).
