### ISSUE TITLE
Returning Memory to OS (the default behavior)

### ISSUE THREAD

**Issue by crisward** [ivmai/bdwgc#152]
I'm using [crystal-lang](https://github.com/crystal-lang/) which I believe incorporates libgc. 

Crystal doesn't seem return memory to the OS after a spike in memory usage. How does libgc determine when to do this?

**Comment by ivmai** [comment]
First, libgc should be built with configure --enable-munmap option. An optional parameter can be specified along with the option - to set the desired memory blocks unmapping threshold (the number of sequential garbage collections for which a candidate block for unmapping should remain free).

**Comment by crisward** [comment]
@ivmai ,thanks for this, I'll feed this back to crystal to see if we can get more desirable behaviour.

**Comment by asterite** [comment]
@ivmai Hi, thank you for the prompt reply! Is there a reason why this isn't the default behaviour? (to return memory back to the OS after some time)

**Comment by ivmai** [comment]
Several reasons (why unmapping is not on by default):
* historical - it was an experimental feature initially
* unmapping is not supported yet on some targets (e.g. tests fail on Cygwin)
* unmapping+MPROTECT_VDB is not supported yet (so the client app won't be able to use incremental collection (except for Solaris and Windows target) if GC is compiled with unmapping)

We could, of course, change it to the default behavior in GC 7.8 (having items 2 and 3 addressed somehow).
Let's ask @hboehm

**Comment by hboehm** [comment]
I'm not sure what the right thing is.

There is, or at least used to be, also some additional cost associated with
it, assuming you have enough memory not to really need it. The kernel has
to clear memory to remap it. Sometimes that's entirely wasted work. Even if
it isn't, I'm not sure we properly take advantage of it.

Last I looked at this code, it also made the decision about when to unmap
based on a poorly tested and somewhat unconvincing heuristic. If we make it
the default, this should probably be better explored.
