### ISSUE TITLE
Python ctypes and a library with bdwgc

### ISSUE THREAD

**Issue by ckaran** [ivmai/bdwgc#156]
I've got an odd sort of problem.  I'm using [python's ctypes](https://docs.python.org/3/library/ctypes.html) library to bind to a shared library that uses bdwgc to manage any memory it allocates. The general pattern is this:

1. Python uses ctypes to ask the shared library to create an object on its behalf.
2. The shared library does so, returning a pointer to the object.
3. Python does some work on this, possibly keeping it around for a long period of time.
4. Eventually the python object goes out of scope, making the pointer invalid.

The issue seems to be that ctypes is copying the pointer into some internal memory, which is managed by python's internal garbage collector, letting the original pointer go out of scope, which leads to bdwgc collecting the object, leaving python with a stale pointer that causes a crash later on.  I think that the solution is to use `GC_add_roots()` and `GC_remove_roots()` to add the pointers that ctypes creates to the root set.  However, those pointers are managed by python; if adding them means that bdwgc takes ownership of the pointers and disposes of them, then there will be even more crashes.

So, does bdwgc take ownership of the pointers given it by `GC_add_roots()`?

**Comment by ivmai** [comment]
See my reply in #158

**Comment by ckaran** [comment]
I solved this, and my solution is documented in #158
