### ISSUE TITLE
Website unreachable, certificate expired

### ISSUE THREAD

**Issue by fxcoudert** [ivmai/bdwgc#157]
The package's website at https://www.hboehm.info/ is unreachable as its HTTPS certificate expired a few days ago.

**Comment by hboehm** [comment]
I will investigate.

In the meantime, here are the md5 sums from my source directory, if you
want to use plain http:

hboehm@fs2:/export/www/work/gc/gc_source$ md5sum *
4f3c130fc71ff23584edaa19a37739ee  bdwgc-7_2alpha5-20110107.tar.bz2
49d0db4f59bb4874db24c5942ed8c2ee  cordh.txt
528371164ac9838dcb263fede456eff6  gc6.0.tar.gz
00a87b68f4baa21c56fa42d811e98f7c  gc6.1.tar.gz
15492b14ca7b9a9e035238611e9cd1e3  gc6.2.tar.gz
b703cf7ddda01ec625761abc46c84f41  gc6.3alpha1.tar.gz
32338a25ca94440ecccbf583cde21d49  gc6.3alpha4.tar.gz
217546fb28a810acccd1287ae3fbd89c  gc6.3alpha5.tar.gz
8b37ee18cbeb1dfd1866958e280db871  gc6.3.tar.gz
ef03495e980b834a99c0e27eedaa546e  gc6.4.tar.gz
00bf95cdcbedfa7321d14e0133b31cdb  gc6.5.tar.gz
c7c301e8fab8ce152c908b05bc8d452c  gc6.6.tar.gz
be780413a0360306ad3b701e45fa8871  gc6.7.tar.gz
418d38bd9c66398386a372ec0435250e  gc6.8.tar.gz
a73e10fa105f00a6cd0471cbbe7361f4  gc7.0alpha7.tar.gz
d262774a7c79db4df9a57f20eb561c0c  gc-7.0alpha9.tar.gz
3645ccf5f32ebb27d99b27b0d29e9c38  gc-7.0.tar.gz
1aa1b0047199d64ad76da38fbb40bb4b  gc-7.1alpha2-revised.tar.gz
4fa4fa6d54666df9b60c2921a41c7096  gc-7.1alpha2.tar.gz
d15c1c624d542bb06e74481001d63063  gc-7.1alpha3-080220.tar.gz
c104abd2c0a0278ed32ae9e7f4460948  gc-7.1alpha3-080224.tar.gz
2ff9924c7249ef7f736ecfe6f08f3f9b  gc-7.1.tar.gz
873fe5f0612b6edcb07ca46e04af7c94  gc-7.2alpha2.tar.gz
0a6785ebb61c6e2b50c3952c3bbf9ea1  gc-7.2alpha4.tar.gz
319d0b18cc4eb735c8038ece9df055e4  gc-7.2alpha6.tar.gz
7124aad6171bcdf0ccf84b0aa4dd2fff  gc-7.2b.tar.gz
edd99c64174a1f3b10a474b3e4c74634  gc-7.2c.tar.gz
91340b28c61753a789eb6077675d87d2  gc-7.2d.tar.gz
5e230029f802d0ac633b1d9b3d4934c9  gc-7.2e.tar.gz
37edd40ebd0b4fe9ce13d27fcf4e5902  gc-7.2f.tar.gz
6f77f9fff5fb5bf96adfc1e93cd035b6  gc-7.2g.tar.gz
d17aecedef3d73e75387fb63558fa4eb  gc-7.2.tar.gz
ba21f50d4f96ac277a85449aba3c989c  gc-7.3alpha2.tar.gz
f40d9a47c90d60791eeecb484f8df5ee  gc-7.4.0.tar.gz
12c05fd2811d989341d8c6d81f66af87  gc-7.4.2.tar.gz
96d18b0448a841c88d56e4ab3d180297  gc-7.4.4.tar.gz
bf46ccbdaccfa3186c2ab87191c8855a  gc-7.6.0.tar.gz
108d88ee7af49f9dd391ec9e8a1d88e1  gc_cpph.txt
da457ef21bc7a0c00b5fd7759f3b161d  gch.txt
5e230029f802d0ac633b1d9b3d4934c9  gc.tar.gz
124a9ee194ba655302058d53fbf7053f  gc_typedh.txt
md5sum: historical: Is a directory
e6d1c85c90563555f1fde7a0980d41ab  libatomic_ops-7.2g.tar.gz
c9361a8dea3748599b91c87a51eaf4a8  libatomic_ops-7.3alpha2.tar.gz
59f9a7cc845dcc775e7b7901eb582766  libatomic_ops-7.4.0.tar.gz
426d804baae12c372967a6d183e25af2  libatomic_ops-7.4.4.tar.gz
e1097df03a41d31e23427b75e41a78f5  recent_changes

**Comment by ivmai** [comment]
Distribution tarballs are now hosted on GitHub:
* bdwgc - https://github.com/ivmai/bdwgc/wiki/Download
* libatomic_ops - https://github.com/ivmai/libatomic_ops/wiki/Download

PS. Mailing lists at lists.opendylan.org are not accessible, here is the backup:
* [bdwgc-announce](https://github.com/ivmai/bdwgc/files/1037650/bdwgc-announce-mailing-list-archive-2014_02.tar.gz) (Oct 2002 - Feb 2014)
* [bdwgc](https://github.com/ivmai/bdwgc/files/1038163/bdwgc-mailing-list-archive-2017_04.tar.gz) (Dec 2002 - Apr 2017)
