### ISSUE TITLE
MinGW: gctest fails with SIGSEGV in test_tinyfl

### ISSUE THREAD

**Issue by Hamayama** [ivmai/bdwgc#167]
from #166

> 1. Could you please recheck it using master branch of bdwgc (with any libatomic_ops)?
> 2. Same as 1 plus --disable-parallel-mark --enable-gc-assertions
> 3. Same as 2 plus comment out THREAD_LOCAL_ALLOC definition in include/config.h

I tried a master branch, but I got many failures.

( I uploaded the logs to the following URL.
  https://gist.github.com/Hamayama/e3e61daf09a4a0dafe3c503c21904947 )

I found that SEGV occurs in 'test_tinyfl' in tests/test.c by using 'git bisect'.

If ./configure option CPPFLAGS="-DDONT_ADD_BYTE_AT_END " doesn't exist,
'test_tinyfl' is skipped by early return and no error occurs.

Also, if I comment out 'test_tinyfl' in tests/test.c, no error occurs.

Issue #166 still exists in a master branch,
so I commented out 'typed_test' and 'test_tinyfl'.

There seems to be no problem as a result.

```
--- tests/test_orig.c	2017-06-16 11:06:24.537473300 +0900
+++ tests/test.c	2017-06-16 13:37:24.877269600 +0900
@@ -1249,7 +1249,9 @@
         FAIL;
       }
 #   endif
+#if 0
     test_tinyfl();
+#endif
 #   ifndef DBG_HDRS_ALL
       collectable_count += 3;
       if ((GC_size(GC_malloc(7)) != 8 &&
@@ -1447,6 +1449,7 @@
                         (unsigned) time_diff, (void *)&start_time);
         }
 #   ifndef DBG_HDRS_ALL
+#if 0
       typed_test();
       if (print_stats) {
         CLOCK_TYPE typed_time;
@@ -1456,6 +1459,7 @@
         GC_log_printf("-------------Finished typed_test at time %u (%p)\n",
                       (unsigned) time_diff, (void *)&start_time);
       }
+#endif
 #   endif /* DBG_HDRS_ALL */
     tree_test();
     if (print_stats) {
```

OS: Windows 8.1 (64bit)
DevTool: MSYS2/MinGW-w64 (64bit) (gcc version 6.3.0 (Rev2, Built by MSYS2 project))

GC: gc-7.7.0_96a81eb_HEAD and libatomic_ops-7.6.0.tar.gz

- **testA:**
  ./autogen.sh
  ./configure --enable-threads=win32 --enable-large-config --disable-gcj-support CPPFLAGS="-DDONT_ADD_BYTE_AT_END "
  make check
  
  COUNT=0; while :; do ./gctest.exe; (( COUNT++ )); echo $COUNT; done
  
  **result:**
  TOTAL COUNT:              1000
  PASS:                     1000
  FAIL(Segmentation fault):    0

--

It seems that the function table in my environment is as follows.

|function|availability|
|---|---|
|GC_MALLOC|O|
|GC_malloc_explicitly_typed|X|
|GC_MALLOC_WORDS|X|

**Comment by Hamayama** [comment]
I made a following patch.

It seems to repair SEGV in 'test_tinyfl' in tests/test.c,
even though I don't understand the logic of reclaim.c well.

```
--- reclaim_orig.c	2017-06-16 11:06:24.521830300 +0900
+++ reclaim.c	2017-06-18 14:34:45.340347600 +0900
@@ -438,10 +438,12 @@
           }
         } else if (GC_find_leak || !GC_block_nearly_full(hhdr)) {
           /* group of smaller objects, enqueue the real work */
-          struct hblk **rlh = ok -> ok_reclaim_list + BYTES_TO_GRANULES(sz);
-
-          hhdr -> hb_next = *rlh;
-          *rlh = hbp;
+          struct hblk **rlh = ok -> ok_reclaim_list;
+          if (rlh != 0) {
+            rlh += BYTES_TO_GRANULES(sz);
+            hhdr -> hb_next = *rlh;
+            *rlh = hbp;
+          }
         } /* else not worth salvaging. */
         /* We used to do the nearly_full check later, but we    */
         /* already have the right cache context here.  Also     */
```

**Comment by ivmai** [comment]
Thank you for reporting and fixing the bug (SIGSEGV in GC_reclaim_block). Patch applied to master: 77bddd5

**Comment by Hamayama** [comment]
I rechecked a master branch 5dff576 and there are no problem.
Thanks!!

|function|availability|
|---|---|
|GC_MALLOC|O|
|GC_malloc_explicitly_typed|O|
|GC_MALLOC_WORDS|O|
