### ISSUE TITLE
Integrate patches from Unity-Technologies/bdwgc/commits/unity-release-7_4 to upstream master

### ISSUE THREAD

**Issue by ivmai** [ivmai/bdwgc#173]
Integrate patches from https://github.com/Unity-Technologies/bdwgc/commit/9379c66bccdf2b911a50cbb77e18c080dbead02a (and later commits).

**Comment by ivmai** [comment]
Hello @joncham 
I have started porting parts of https://github.com/Unity-Technologies/bdwgc/commit/9379c66bccdf2b911a50cbb77e18c080dbead02a to upstream master.
Just FYI.

**Comment by joncham** [comment]
@ivmai I have actually just  started applying the patches we need (there is likely much we don't) to https://github.com/Unity-Technologies/bdwgc/tree/unity-release-7_6
