### ISSUE TITLE
Turn on handle-fork by default

### ISSUE THREAD

**Issue by ivmai** [ivmai/bdwgc#174]
Requested by Erik Bray (for Cygwin platform)
Current behavior: handle-fork is enabled if the client calls GC_set_handle_fork(1)
See details in: http://bdwgc.opendylan.narkive.com/qOaibiGO/gc-cygwin-and-handle-fork-gc-handle-fork

Note: there are some platforms where handle-fork mode is conflicting with other feature:
* Darwin: incremental mode

**Comment by ivmai** [comment]
\+ @embray

**Comment by embray** [comment]
IIRC the issue here was just that on Cygwin it doesn't even make sense not to have `handle-fork` enabled by default since otherwise the world breaks if you fork a process using GC with multithreading.  I can provide a patch if desired.

**Comment by embray** [comment]
Oh, I missed the commit 686a667 referencing this issue.  Yes, I think that looks like what I had in mind!
