### ISSUE TITLE
signal/futex deadlock on Linux

### ISSUE THREAD

**Issue by mikeday** [ivmai/bdwgc#175]
(apologies if this isn't the right place, but the mailing list appears to be missing)

We have hit an apparent Linux kernel bug where a signal is not interrupting a futex, leading to a deadlock in our code that uses Boehm GC when it attempts to create a new thread.

Here is the relevant strace output just before it blocks (complete strace log is attached):

14069 set_robust_list(0x7f7b3e7ee9e0, 24 <unfinished ...>
14061 futex(0x7f7b46721fd8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
14069 <... set_robust_list resumed> )   = 0
14069 futex(0x7f7b46721fd8, FUTEX_WAKE_PRIVATE, 1) = 1
14061 <... futex resumed> )             = 0
14061 futex(0x1585ea0, FUTEX_WAIT_PRIVATE, 2, NULL <unfinished ...>
14069 tgkill(14061, 14061, SIGPWR)      = 0
14069 futex(0x1586280, FUTEX_WAIT_PRIVATE, 0, NULL

Thread '69 sends SIGPWR to thread '61, but it is never delivered and we have not been able to figure out why.

Background information: this deadlock is experienced by our customer running Prince on CentOS 7. The bug happens every time on their system, but we have not been able to reproduce it on ours yet. They have tried two different kernel versions:

3.10.0-327.28.2.el7.x86_64
3.10.0-514.26.2.el7.x86_64

Over the past two years we have heard similar deadlock issues from other customers, always on CentOS and typically involving PHP, although these are of course very popular systems.

This issue appears to be unrelated to the earlier futex bug affecting Haswell processors, but could there be another bug along these lines affecting futexes or signal delivery?

The GDB backtrace shows that we have seven GC threads paused here:

0x00007f2d63a2a6d5 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
0x0000000000b31977 in GC_wait_marker ()

The newly created thread has done some allocation and triggered a collection so it tried to stop the world and is waiting for the main thread to respond:

0x00007f2d63a2c79b in do_futex_wait.constprop.1 () from /lib64/libpthread.so.0
0x00007f2d63a2c82f in __new_sem_wait_slow.constprop.0 () from /lib64/libpthread.so.0
0x00007f2d63a2c8cb in sem_wait@@GLIBC_2.2.5 () from /lib64/libpthread.so.0
0x0000000000b31f5e in GC_stop_world ()
0x0000000000b22abc in GC_stopped_mark ()
0x0000000000b2354f in GC_try_to_collect_inner ()
0x0000000000b24060 in GC_collect_or_expand ()
0x0000000000b2425d in GC_allocobj ()
0x0000000000b2f5b2 in GC_generic_malloc_inner ()
0x0000000000b2ffe6 in GC_new_thread ()
0x0000000000b301de in GC_register_my_thread_inner ()
0x0000000000b31327 in GC_start_rtn_prepare_thread ()
0x0000000000b3324e in GC_inner_start_routine ()
0x0000000000b27272 in GC_call_with_stack_base ()
0x00007f2d63a26dc5 in start_thread () from /lib64/libpthread.so.0
0x00007f2d6142a76d in clone () from /lib64/libc.so.6

Meanwhile the main thread is still blocked waiting for the new thread to finish starting up:

0x00007f2d63a2c79b in do_futex_wait.constprop.1 () from /lib64/libpthread.so.0
0x00007f2d63a2c82f in __new_sem_wait_slow.constprop.0 () from /lib64/libpthread.so.0
0x00007f2d63a2c8cb in sem_wait@@GLIBC_2.2.5 () from /lib64/libpthread.so.0
0x0000000000b314c6 in GC_pthread_create ()

The signal did not interrupt the futex and wake the main thread, so the entire program is deadlocked.

Has anyone else experienced this issue, or have any tips about why it might be happening? We have also reported it to CentOS and the Linux Kernel Mailing List but are yet to hear a reply.

[strace.txt](https://github.com/ivmai/bdwgc/files/1167979/strace.txt)

**Comment by ivmai** [comment]
1.
> (apologies if this isn't the right place, but the mailing list appears to be missing)

This is the right place.

2. I don't remember similar reports.

**Comment by mikeday** [comment]
We are trying to reproduce this with a simpler C program that will be easier to debug. In order to do this we need to ensure that when we call GC_pthread_create the newly created thread will immediately trigger a heap expansion when it tries to allocate the necessary data structures, while the main thread is still blocked waiting for it to finish initialising.

This is a bit awkward to arrange! We either have to edit the Boehm source to make sure that it always triggers gc during thread initialisation, or ensure that the heap is full just before creating the thread.

Is there a simpler way of making sure that the next allocation will require gc and heap expansion? Or a reliable way of filling the entire heap?

Possibly we could just use an environment variable to set the initial heap size and reduce the value until it triggers the allocation, but that sounds like a possible source of complexity if we run it on different machines.

**Comment by ivmai** [comment]
> Is there a simpler way of making sure that the next allocation will require gc and heap expansion?

Call GC_gcollect(); GC_expand_hp(<how_much_to_add>);

**Comment by mikeday** [comment]
Hmm I mean so when we call GC_pthread_create the allocation that _it_ does when allocating the data structures for the new thread needs to trigger a collection in order get the deadlock we are experiencing.

**Comment by ivmai** [comment]
Is it possible to call GC_gcollect before pthread_create?

**Comment by mikeday** [comment]
Oh right, to avoid the deadlock? Yes, we have considered that. But we would also like to understand the problem. One possibility is that SIGPWR is blocked by the parent process, perhaps the collector needs to explicitly unblock it with pthread_sigmask at startup?

**Comment by mikeday** [comment]
We have confirmed that PHP 7.0.21 blocks SIGPWR and many other signals, and this block is inherited by any processes that it execs, so we must explicitly unblock the signal before using Boehm.

**Comment by ivmai** [comment]
@mikeday Have you solved the issue?
The issue is caused by PHP which blocks the signals, right?

**Comment by mikeday** [comment]
Sorry that was the issue, yes. We have added our own code to unblock the signals:

```
    sigset_t set;
    int sig1;
    int sig2;

    sigemptyset(&set);
    sig1 = GC_get_suspend_signal();
    sig2 = GC_get_thr_restart_signal();
    if (sig1 >= 0 &&
        sig2 >= 0 &&
        sigaddset(&set, sig1) == 0 &&
        sigaddset(&set, sig2) == 0 &&
        pthread_sigmask(SIG_UNBLOCK, &set, NULL) == 0)
```
It might make sense for Boehm to do this itself though, as any application that uses it can deadlock unexpectedly if the signals are blocked.

**Comment by ivmai** [comment]
> It might make sense for Boehm to do this itself though

**Comment by mikeday** [comment]
Just once at initialisation should be sufficient; if the process blocks signals again after that then I think it's on its own. :)

**Comment by ivmai** [comment]
> It might make sense for Boehm to do this itself though

I guess -D GC_EXPLICIT_SIGNALS_UNBLOCK is what you are asking about. Does it help in your case?

**Comment by wangp** [comment]
Not sure how we missed that! -D GC_EXPLICIT_SIGNALS_UNBLOCK would indeed solve the issue.

By the way, it wasn't PHP itself blocking the signals, but mod_php in combination with the "worker" multi-processing module in Apache.

**Comment by wangp** [comment]
Hmm, that doesn't unblock the signals on the main thread.

**Comment by ivmai** [comment]
I see. Your case is different. You need this in the main thread (and only in it). I will make a fix.
