### ISSUE TITLE
Hello, bdwgc 7.6 support iOS,  does bdwgc support iOS bitcode?

### ISSUE THREAD

**Issue by radxe** [ivmai/bdwgc#176]
Hello, 
    Bbdwgc is great to support iOS,  does bdwgc support iOS bitcode?
   because apple require submit bitcode for watchOS,tvOS, iOS is optional, bdwgc use asm code, I know apple has a asm exception for bitcode, I just want to know bdwgc if support bitcode.

Thank you very much!

**Comment by ivmai** [comment]
Please use libatomic_ops-7.6, it should not use asm.
What are the other source places that cannot be converted to bitcode?

**Comment by radxe** [comment]
dear ivmci,
    I see.  I will try to use  libatomic_ops-7.6. 
    Another question, when will you release bdwgc 7.6? do you have a bdwgc roadmap?
thanks

**Comment by ivmai** [comment]
> when will you release bdwgc 7.6? do you have a bdwgc roadmap?

I plan to release it at the end of September. Maybe earlier.
