### ISSUE TITLE
Assert during finalize

### ISSUE THREAD

**Issue by tomspilman** [ivmai/bdwgc#186]
I'm hoping someone can point me in the right direction as to what this error could mean so i can fix the issue.

I'm having the following assert fire shortly after startup of our application when an allocation of a large block of memory occurs:

https://github.com/ivmai/bdwgc/blob/master/finalize.c#L1026
```
              /* unhide object pointer so any future collections will   */
              /* see it.                                                */
              curr_fo -> fo_hidden_base =
                        (word)GC_REVEAL_POINTER(curr_fo -> fo_hidden_base);
              GC_bytes_finalized +=
                        curr_fo -> fo_object_size
                        + sizeof(struct finalizable_object);
            GC_ASSERT(GC_is_marked(GC_base(curr_fo))); // <-- ASSERT FAILS!
            curr_fo = next_fo;
```
What could cause the finalizing object not be marked at this point?

Any other diagnostics i could enable to help track the problem?

Note this *ONLY* occurred in release builds with asserts enabled.  In debug builds there is no error... making it harder to track down.

**Comment by tomspilman** [comment]
So i figured out my bug... it was stupid, but really easy to do.  It makes me wonder if there should be an assert to catch this mistake.

What happened is i had some C++ code that should not use the GC mixed into my code that does use the GC.  I mistakenly left `gc_cpp.cc` included in my build of bdwgc.  This means that any call to `new` would use the GC allocators.  This itself wasn't the bug... but it sort of triggered it.

I had a static variable allocated with `new` which meant it gets allocated before my `main()`.  I have very specific initialization code for the GC which i intended to be called before any other GC work:
```
GC_set_all_interior_pointers(0);
GC_set_free_space_divisor(2);
GC_INIT();
GC_set_finalize_on_demand(true);
GC_set_finalizer_notifier(&_my_FinalizerNotifier);
GC_allow_register_threads();
```
So this meant that the static initialized with `new` was initializing the GC before me and with other settings.  My guess is that changing one of these settings after the initial `new` caused the assertion (maybe this is a bug in itself).

Anyway...   i've since fixed my initialization to check `GC_is_initialized` to verify nothing has mistakenly initialized the GC before i do.

**Comment by ivmai** [comment]
My understanding is that the assertion failed because of GC_set_all_interior_pointers(0). In case of multiple inheritance C++ object pointer may point to inside the object thus disabling scanning of interior pointer might lead to collecting of live C++ objects.

**Comment by tomspilman** [comment]
> In case of multiple inheritance C++ object pointer may point to inside the object

 Thanks @ivmai .   That could be possible...  the object was an C++ STL map.
