### ISSUE TITLE
disclaim_test fails in incremental mode

### ISSUE THREAD

**Issue by ivmai** [ivmai/bdwgc#192]
How to reproduce:
./configure && GC_ENABLE_INCREMENTAL=1 make check

Output:
Assertion failure, line 114: !p->cdr || is_pair(p->cdr)
FAIL disclaim_test (exit status: 255)

The test fails even with --disable-threads.

My test host: Linux/x64
Source: latest master (but it fails even on release-7_4 branch, I guess disclaim_test has never been tested with the incremental mode). 

PS. The feature was added in #5

**Comment by ivmai** [comment]
Hello @paurkedal 
Could you please look at this issue?

**Comment by paurkedal** [comment]
Yes, that looks suspicious.  I'll have take a closer look in the weekend.

**Comment by ivmai** [comment]
Fixed.
Test added: 0bde150
