### ISSUE TITLE
_DYNAMIC=0 not needed for Liniux

### ISSUE THREAD

**Issue by wangp** [ivmai/bdwgc#196]
README.linux currently says:
> A static executable should be linked with the gcc option "-Wl,-defsym,_DYNAMIC=0".

If I understand correctly, once `#pragma weak _DYNAMIC` was added to dyn_load.c (in gc5.0alpha3) it should no longer be necessary to manually define _DYNAMIC to avoid an unresolvable symbol error.

The advice is problematic for Alpine Linux (and probably other systems using musl). Building a program with gcc -static produces a binary containing a _DYNAMIC symbol with non-zero address, and forcing the address to 0 causes a crash during GC initialisation.

**Comment by ivmai** [comment]
Done
