### ISSUE TITLE
libgc version changed in a linkage breaking way

### ISSUE THREAD

**Issue by ivmai** [ivmai/bdwgc#197]
The libtool version-info incompatible change (from 1:3:0 to 2:0:0) was performed intentionally (see ivmai/bdwgc@5f74078) because the part of GC API was changed in an incompatible way (see ivmai/bdwgc@2dd4ee7) some time before.

The part of the API changed in an ABI-incompatible way contains only 2 functions (defined in some prior libgc release): GC_set_free_space_divisor, GC_set_warn_proc. The change is in the return type of these function - it was replaced from int to void. Thu,s only the clients relying on the return value of these functions are actually affected by this ABI incompatible change.

At the same time. the issue is that the mentioned change causes dependency issues in the downstream packages: the existing dependent packages are linked against libgc.so.1 while the latest libgc (7.6.2) package build produces libgc.so.2; even more, it seems impossible to have both of the versions installed because both the old and new libgc package contain same libcord and libgccpp have the same filename - libcord.so.1 and libgccpp.so.1, respectively.

As the mentioned ABI-incompatible change was done in 7.2alpha1 (released in 2009) and many libgc version have been released after that without the change of version-info, there is no actual benefit in reflecting this ABI change in the version-info, only the drawbacks exist.

Links:
* https://github.com/ivmai/libatomic_ops/issues/29
* https://github.com/andyli/libgc-cygwin/issues/1
* https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html

**Comment by ivmai** [comment]
As some downstream package maintainers already released v7.6.2 (see https://repology.org/metapackage/boehm-gc/versions), I think the best thing I could do in the upstream is to increment "age" part of the version-info and release v7.6.4 shortly, and then ask the maintainers to make the packages again.

**Comment by ivmai** [comment]
+ @andyli 
+ @ilovezfs

**Comment by ilovezfs** [comment]
@ivmai Given this hasn't affected the major Linux distros yet, I'd suggest just rolling back to the old versions.

**Comment by ivmai** [comment]
@ilovezfs Rolling back means decrement of "current" part of the version-info. It looks to me that just increasing "age" is less painful (as if new version of ABI is now compatible with that of all the previous versions of libgc).

**Comment by vapier** [comment]
agreed that, while the ABI breakage should originally have bumped the SONAME, the fact that it didn't and no one noticed suggests we should just leave it be.  add a note to some news/readme/changelog file and move on :).

**Comment by ilovezfs** [comment]
@ivmai I think any of the package managers that are on 7.4.2 or 7.6.0 should be able to upgrade to 7.6.4 without rebuilding the reverse dependencies. I may be wrong, but I think the only way to make that possible is to revert the version change and decrement the current part.

**Comment by ilovezfs** [comment]
@vapier the problem is that 7.6.2 already shipped with the version-info changed in a linkage breaking way. I'm advocating that 7.6.4 should just revert that as if it never happened.

**Comment by ivmai** [comment]
The revert does not seem to be easy (unlike incrementing of the age) as each branch (e.g. release-7_6 and master) have different "current" part as master branch adds new API functions. Here are the version-info update commits for release-7_6 (e8c5032) and master (f6f720e7f).

> I think the only way to make that possible is to revert the version change and decrement the current part.
Could someone confirm that the revert is the best way in the current situation (not incrementing of the age)?

**Comment by vapier** [comment]
https://www.gnu.org/software/libtool/manual/html_node/Versioning.html

* current: 5
  * the latest ABI level that the lib supports.  you've updated the ABI in an incompatible way, so incrementing this number is correct.
* revision: 0
  * just a convenience value for the current ABI level.  0 is fine since you just bumped current.
* age: 3
  * how many ABI levels back you support.  you've broken the previous ABI, so using 3 here is correct (so you support back to level 2 of the ABI).  this is actually a delta, not an absolute ABI level (unlike "current").

going by this report, we agree that we should just lie and say that it's actually compatible with older versions.  which means updating the age field.

so if you're passing `5:0:3` in master as the libtool version info currently for libgc, change it to `5:0:4`.  that'll change the SONAME back to `libgc.so.1` on ELF systems because we're lying and saying we're compatible with the pre-ABI breakage level.

for `4:0:2` in release-7_6, change it to `4:0:3`.

**Comment by ivmai** [comment]
> for 4:0:2 in release-7_6, change it to 4:0:3

Thank you, @vapier, I will release 7.6.4 next week.

**Comment by ivmai** [comment]
[v7.6.4](https://github.com/ivmai/bdwgc/releases/tag/v7.6.4) released: https://github.com/ivmai/bdwgc/releases/download/v7.6.4/gc-7.6.4.tar.gz
