### ISSUE TITLE
syntax error in configure

### ISSUE THREAD

**Issue by rdp** [ivmai/bdwgc#200]
FWIW If I do this:

> 
> git clone https://github.com/ivmai/bdwgc.git
> cd bdwgc
> git clone https://github.com/ivmai/libatomic_ops.git
> autoreconf -vif
> automake --add-missing
> ./configure

It says this:

> 
> ...
> checking pkg-config is at least version 0.9.0... yes
> ./configure: line 18544: syntax error near unexpected token `else'
> ./configure: line 18544: `else'
> make: *** [config.status] Error 2

No amount of running pkg-config seems to overcome it.

Current work around:

`make -f Makefile.direct` and rename gc.a to libgc.a (except lacks pthread support)

(or download a versioned tar that already contains a built configure, use that instead [works with pthread support]).

This is CentOS 6.7 so might not be worth worrying about but thought I'd log it here for followers.

**Comment by ivmai** [comment]
Duplicates #69.

As documented in configure.ac:
\# Note: "syntax error near unexpected token ATOMIC_OPS" reported by configure
\# means Autotools pkg.m4 file was not found during aclocal.m4 generation;
\# in this case, most probably, you should run pkg-config once before running
\# autogen.sh (autoreconf); **alternatively, comment out the following 3 lines.**
AS_IF([test x$missing_libatomic_ops = xtrue],
  [ PKG_CHECK_MODULES([ATOMIC_OPS], [atomic_ops],
    [ missing_libatomic_ops=false ], [ [] ]) ])

**Comment by ivmai** [comment]
Probably it's worth dropping these lines in configure.ac permanently (for master branch which does not need libatomic_ops on modern hosts). I'm checking it.
