### ISSUE TITLE
make CFLAGS=-xc++

### ISSUE THREAD

**Issue by jaykrell** [ivmai/bdwgc#206]
make CFLAGS=-xc++ has some compilation problems. Interested?
The ones I recall are: ptr_t vs. void*, and extra.c playing games with extern/inner leads to:
int foo;
int foo = 1;

which isn't legal. I can work it through if you are interested. I do not have any grand plan here -- void* and extern "C" was really all.

**Comment by ivmai** [comment]
Making the whole code compliant with C++ would not be bad I think.

My understanding for "int foo redefinition" is that we should define GC_EXTERN to extern in extra/gc.c if not NO_DEBUGGING.

So, I'm OK to accept your patch. Thank you

**Comment by ivmai** [comment]
I've decided to help you with this, I've added some casts some individual .c files can be now compiled by C++ compiler (I have tested with Cygwin only, so probably I missed some casts). See commit a825a2d6.

**Comment by jaykrell** [comment]
You are pretty much way ahead of me. I had similar looking stuff, but you did a lot more.
