### ISSUE TITLE
gctest fail on risc-v

### ISSUE THREAD

**Issue by ivmai** [ivmai/bdwgc#212]
As reported in #208 by @rwmjones:

Note these results are on qemu, not on real hardware. I used -smp 4 to emulate 4 CPUs.

```
PASS: cordtest
./test-driver: line 107:  4801 Aborted                 (core dumped) "$@" > $log_file 2>&1
FAIL: gctest
PASS: leaktest
PASS: middletest
PASS: smashtest
PASS: hugetest
PASS: realloc_test
PASS: staticrootstest
PASS: test_atomic_ops
PASS: threadleaktest
PASS: threadkey_test
PASS: subthreadcreate_test
PASS: initsecondarythread_test
PASS: disclaim_test
PASS: disclaim_bench
============================================================================
Testsuite summary for gc 7.7.0
============================================================================
# TOTAL: 15
# PASS:  14
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See ./test-suite.log
Please report to https://github.com/ivmai/bdwgc/issues
============================================================================
```

I'll see if I can get a stack trace from the failure.

FAIL: gctest

Typed alloc failed at 15921
Test failed
FAIL gctest (exit status: 134)

I just realised we don't have gdb, and we're some way from having it, so no stack trace for a while ... If there's anything else that can be done to diagnose problems (verbose mode?) let me know.

**Comment by ivmai** [comment]
I suggest first to try the following variants of configure options (the first one just turns on extra check, the 2nd one disables threads, and the 3rd one enables thread but disables parallel marking and local allocations):
* --enable-gc-assertions
* --enable-gc-assertions --disable-threads
* --enable-gc-assertions--disable-parallel-mark --disable-thread-local-alloc

**Comment by rwmjones** [comment]
This error is intermittent.  At the moment I cannot make it reproduce, even though nothing significant has changed about the system.

I suspect we'll have to revisit this when we have real hardware, which will also be faster and so more likely to expose concurrency problems.

**Comment by ivmai** [comment]
OK. I leave the issue open.

PS. Probably related issue: #11

**Comment by bhaible** [comment]
For me, the gctest hangs on riscv64. (Also QEMU emulated, not real hardware.)

**Comment by rwmjones** [comment]
Well I'd totally forgotten about this, but we have plenty of real hardware these days.  All the tests run fine for me, but I've set up a loop running `gctest` over and over again since it was originally reported as an intermittent problem.

**Comment by rwmjones** [comment]
It does indeed hang (not crash) after a few rounds.  No CPU is used.  The stack trace is very long, so I captured it as a separate file.
[gctest-stack.txt](https://github.com/ivmai/bdwgc/files/6056730/gctest-stack.txt)

**Comment by ivmai** [comment]
> It does indeed hang (not crash) after a few rounds. No CPU is used. The stack trace is very long, so I captured it as a separate file.
> [gctest-stack.txt](https://github.com/ivmai/bdwgc/files/6056730/gctest-stack.txt)

The shortened stacks trace:
```
Thread 9 (Thread 0x3fc0b6e150 (LWP 469742)):
#1  0x0000003fc44ed090 in pthread_mutex_lock () from /lib64/lp64d/libpthread.so.0
#2  0x0000003fc45250d4 in GC_call_with_alloc_lock (fn=fn@entry=0x130aa <set_stackbottom>, client_data=client_data@entry=0x3fc0b6d640) at extra/../misc.c:2129
#3  0x000000000001494e in run_one_test () at tests/test.c:1557

Thread 8 (Thread 0x3fc136f150 (LWP 469741)):
#1  0x0000003fc44ed090 in pthread_mutex_lock () from /lib64/lp64d/libpthread.so.0
#2  0x0000003fc45218a4 in GC_free (p=0x3fc0326f20) at extra/../malloc.c:601
#3  0x000000000001478c in run_one_test () at tests/test.c:1477

Thread 7 (Thread 0x3fc1b70150 (LWP 469740)):
#1  0x0000003fc44ed090 in pthread_mutex_lock () from /lib64/lp64d/libpthread.so.0
#2  0x0000003fc45218a4 in GC_free (p=0x3fc0161fc0) at extra/../malloc.c:601
#3  0x0000000000013a94 in test_generic_malloc_or_special (p=<optimized out>) at tests/test.c:697

Thread 6 (Thread 0x3fc2371150 (LWP 469739)):
#1  0x0000003fc44ed090 in pthread_mutex_lock () from /lib64/lp64d/libpthread.so.0
#2  0x0000003fc452b2bc in GC_generic_malloc_many (lb=32, k=<optimized out>, result=0x3fc4386940) at extra/../mallocx.c:332
#3  0x0000003fc452b7cc in GC_malloc_kind (bytes=bytes@entry=16, kind=kind@entry=1) at extra/../thread_local_alloc.c:179
....
#3360 ints (low=low@entry=1, up=up@entry=4500) at tests/test.c:466

Thread 5 (Thread 0x3fc2b72150 (LWP 469738)):
#1  0x0000003fc44ed090 in pthread_mutex_lock () from /lib64/lp64d/libpthread.so.0
#2  0x0000003fc452b2bc in GC_generic_malloc_many (lb=32, k=<optimized out>, result=0x3fc4386ed0) at extra/../mallocx.c:332
#3  0x0000003fc452caee in GC_gcj_malloc (bytes=bytes@entry=24, ptr_to_struct_containing_descr=0x18010 <gcj_class_struct2>) at extra/../thread_local_alloc.c:228
#4  0x00000000000135e2 in gcj_cons (x=0x3fc01e4ec8, y=0x3fc019d008) at tests/test.c:428

Thread 4 (Thread 0x3fc3383150 (LWP 469737)):
#0  0x0000003fc44f062a in pthread_cond_wait@@GLIBC_2.27 () from /lib64/lp64d/libpthread.so.0
#1  0x0000003fc45208d8 in GC_wait_marker () at extra/../pthread_support.c:2374
#2  GC_help_marker (my_mark_no=my_mark_no@entry=32) at extra/../mark.c:1221

Thread 3 (Thread 0x3fc3b84150 (LWP 469736)):
#0  0x0000003fc44f062a in pthread_cond_wait@@GLIBC_2.27 () from /lib64/lp64d/libpthread.so.0
#1  0x0000003fc45208d8 in GC_wait_marker () at extra/../pthread_support.c:2374
#2  GC_help_marker (my_mark_no=my_mark_no@entry=32) at extra/../mark.c:1221

Thread 2 (Thread 0x3fc4385150 (LWP 469735)):
#0  0x0000003fc44f062a in pthread_cond_wait@@GLIBC_2.27 () from /lib64/lp64d/libpthread.so.0
#1  0x0000003fc45208d8 in GC_wait_marker () at extra/../pthread_support.c:2374
#2  GC_help_marker (my_mark_no=my_mark_no@entry=32) at extra/../mark.c:1221

Thread 1 (Thread 0x3fc43b6010 (LWP 469721)):
#1  0x0000003fc44ed090 in pthread_mutex_lock () from /lib64/lp64d/libpthread.so.0
#2  0x0000003fc452b2bc in GC_generic_malloc_many (lb=32, k=<optimized out>, result=0x3fc45393d8 <first_thread+320>) at extra/../mallocx.c:332
#3  0x0000003fc452b7cc in GC_malloc_kind (bytes=bytes@entry=16, kind=kind@entry=1) at extra/../thread_local_alloc.c:179
...
#1376 ints (low=low@entry=1, up=up@entry=4500) at tests/test.c:466
```

So, the situation:
* Several marker threads are waiting on a conditional var - it's normal
* Other threads are trying to acquire GC_alloc_lock - this is strange.

The question is: which thread is holding GC_alloc_lock?

**Comment by ivmai** [comment]
Is this still reproducible on fresh master?
If yes, what's the value of GC_lock_holder when gctest hangs?

**Comment by rwmjones** [comment]
This has been running for ~ 2 hours and does not appear to be failing in any way.  Previously it failed after about 5 minutes (but that was on different hardware).  So I guess we can declare this bug fixed.

**Comment by ivmai** [comment]
Okay, thank you for checking it.
