### ISSUE TITLE
Trouble installing in Windows: ntwin32.mak not found

### ISSUE THREAD

**Issue by matheusantonio** [ivmai/bdwgc#216]
Hi, i am trying to execute "nmake -f NT_MAKEFILE" at the Visual Studio Developer command prompt as said in "README.win64" to install the garbage collector in Windows, but i get "fatal error U1502", file "ntwin32.mak" not found. I have searched through web about, it is said that the file should be in my Microsoft SDK folder, but no sign of it, even though the SDK uptadated.
Thanks for the attention and help.

**Comment by ivmai** [comment]
I've checked Microsoft Windows SDK v7.0, NtWin32.Mak is located in "include" folder. (The only thing it does is include of win32.mak.)
Which SDK do you have?

**Comment by matheusantonio** [comment]
I realized by your reply that I only updated v10 SDK, and not v7. Now, I have the file in "C:\Program Files\Microsoft SDKs\Windows\v7.0\Include", just as you said. Therefore, I am still getting the error.

**Comment by ivmai** [comment]
Check "WindowsSdkDir" environment variable - it should point to "C:\Program Files\Microsoft SDKs\Windows\v7.0" .

**Comment by matheusantonio** [comment]
I found no environment variable called "WindowsSdkDir". I tried to create one and specify this path, but it did not worked (i am getting the same error).

**Comment by ivmai** [comment]
This is on an issue of this project. There are plenty of ways how to work around this:
* downgrade MS SDK to v7
* use CMake
* use gc.mak
* use cl command directly (e.g. "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\x86_amd64\cl" -I "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include" -I "C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Include" -I include -I libatomic_ops\src -DGC_THREADS -DTHREAD_LOCAL_ALLOC -DPARALLEL_MARK -DGC_DLL -DDONT_USE_USER32_DLL extra/gc.c /link /dll /out:gc64.dll /libpath:"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\lib\amd64" /libpath:"C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Lib\x64")
* use other toolchain/compiler: cygwin, mingw, intel c++, dmc, watcom, etc.
