### ISSUE TITLE
Nan tagging

### ISSUE THREAD

**Issue by manuel-serrano** [ivmai/bdwgc#217]
Hi There,

I'm not reporting an issue but rather a feature request so I'm not sure whether this is the appropriate place or not...

I would like to experiment with nan-tagging for my Scheme compiler (Bigloo) on x86-64 platforms.
From the GC point of view, this means that the pointers highest 16 bits are used to detect what's a integer and what's a pointer and should be ignored when tracing pointers (a relatively safe alternative would be to simply ignore the higher 16 bits and just checking the value alignment). Do you think it would it be possible to add a new option to the collector to implement that? For language like Scheme or JavaScript this would be a very nice feature to have as it enables to get rid of floating point boxing,
a problem that has always been very difficult to handle efficiently with non-copying generational collectors.

**Comment by manuel-serrano** [comment]
Hi Ivan,

First, thanks a lot for quick reply. It helps.

Yes, POINTER_MASK is what I need (although not optimal because some floating point numbers might erroneously be interpreter as pointers, but I guess the risk is minimal). Checking the various .h files
(gc.h, ...) I have missed that macro but now I see it is described in README.macros. I will have a carefull look at all this macros available there.

To come back to your question, yes NAN is not-a-number. It consists in playing tricks with the 2^53 ways of representing NAN in IEEE doubles. I think it has first been used in LUA-jit. V8, JavaScriptCore,
and SpiderMonkey use it. If you are interested in the details, you may find a explanation here:

https://nikic.github.io/2012/02/02/Pointer-magic-for-efficient-dynamic-value-representations.html

Thanks again for your help.

**Comment by ivmai** [comment]
I see, thank you. If you have an idea of improvement, either make a pull request or let's discuss it here.
I'm closing the issue for now
