### ISSUE TITLE
include/weakpointer.h doesn't have an implementation

### ISSUE THREAD

**Issue by edolstra** [ivmai/bdwgc#221]
[`weakpointer.h`](https://github.com/ivmai/bdwgc/blob/master/include/weakpointer.h) sounded useful for a C++ project I'm working on, but it doesn't work because it refers to various symbols such as `_WeakPointer_Pointer` that don't exist anymore. It appears that these used to be defined in [`gcc_support.c`](https://github.com/ivmai/bdwgc/blob/acf2e57f2091522924a0064b318642253e2b2bac/gcc_support.c), which was removed in e35a4171fe47dfbf847e08988ea6cec4dfc8d124. So I guess either weakpointer.h should be removed from the repository or perhaps the implementation could be revived.

**Comment by ivmai** [comment]
Thank you. Fixed.
