### ISSUE TITLE
Compiling using Microsoft Visual Studio

### ISSUE THREAD

**Issue by priand** [ivmai/bdwgc#223]
I found a couple of issues when trying to compile the code using VC++.
1- It is confusing: should we use NT_MAKEFILE.mak or gc.mak?
2- I tried gc.mak but did not find how to compile for x64. I then tried to import it in both VC2010 & VC2017 but it failed.
3- NT_MAKEFILE uses ntwin32.mak which apparently disappeared with V11. I was able to find this file and its dependencies in SDK V7. Btw, the downloadable zip file (gc-7.6.4.tar.gz) seems to have different make files from the Git repo,  and no VC++ projects.
4- Was able to compile for x86 using NT_MAKEFILE but it fails for x64: it actually generates many type conversion warnings, and a compilation error:
misc.c(1216): error C2118: negative subscript
I created a brand new project in VC2017 and the errors above/warning do not appear.
I'm also seeing this kind of warnings in libatomic:
libatomic_ops\src\atomic_ops/sysdeps/msftc/x86_64.h(49): warning C4163: '_InterlockedIncrement64': not available as an intrinsic function
5- It will help to define _CRT_SECURE_NO_WARNINGS early in a .h instead of relying on a preprocessor settings
#ifdef _MSC_VER
#define _CRT_SECURE_NO_WARNINGS
#endif

Any help/hint will be more than appreciated! I

**Comment by ivmai** [comment]
> 1- It is confusing: should we use NT_MAKEFILE.mak or gc.mak?

NT_MAKEFILE, as it is tested better.

> 2- I tried gc.mak but did not find how to compile for x64. I then tried to import it in both VC2010 & VC2017 but it failed.

gc.mak needs fixing I think.

> 3- NT_MAKEFILE uses ntwin32.mak which apparently disappeared with V11. I was able to find this file and its dependencies in SDK V7.

Fixed (in master for now).

> Btw, the downloadable zip file (gc-7.6.4.tar.gz) seems to have different make files from the Git repo, and no VC++ projects.

Yes, master branch is more recent, its makefile might not work for older source (like v7.6.x).
VS projects have not been tested for ages.

> 4- Was able to compile for x86 using NT_MAKEFILE but it fails for x64: it actually generates many type conversion warnings, and a compilation error:
misc.c(1216): error C2118: negative subscript

This is fixed (in master for now). Please note that if you are targeting x64 but your host is x86 then you should pass "cpu=AMD64" argument to nmake.

> I'm also seeing this kind of warnings in libatomic:
libatomic_ops\src\atomic_ops/sysdeps/msftc/x86_64.h(49): warning C4163: '_InterlockedIncrement64': not available as an intrinsic function

This is fixed, pass "cpu=AMD64".

> 5- It will help to define _CRT_SECURE_NO_WARNINGS early in a .h instead of relying on a preprocessor settings

This macro is defined in NT_MAKEFILE, it works.
