### ISSUE TITLE
crashed on android

### ISSUE THREAD

**Issue by ZeroKill1024** [ivmai/bdwgc#226]
hi, i build libbdwgc.a with ndk-r16b, and use api 21, armeabi-v7a with NEON, clang 5.0.3
but it crashed, and get some logs like this:
"Application crash has been observed
Sending signal. PID: 21363 SIG: 9
Unable to load native library: /data/app-lib/com.app.entry-1/libEntry.so"
is there need some special configs with android build?

**Comment by ivmai** [comment]
Each supported target has own configuration, and the target might not be well tested.

Which bdwgc config and source do you use? I recommend to recheck the crash with the lastest master
How do you compile bdwgc? I recommend to try it statically link with your native library.
Have you tried to run GC tests (gctest, etc.)?
Is it crashed because of some GC assertion violation?

**Comment by ZeroKill1024** [comment]
I use the latest master codes, and just config with GC_NOT_DLL, GC_DEBUG, GC_NAMESPACE,  and build it statically, finally, I just use GC_INIT() in android_main(). Working well on windows, but crashed on android.
It looks like just cant't load the native library with gc according to the logcat infos:
D/dalvikvm( 2055): GC_FOR_ALLOC freed 1537K, 25% free 5638K/7456K, paused 6ms, total 7ms
D/BstCommandProcessor-httpd( 2055): command: getlaunchactivityname com.spaces.entry
D/BstCommandProcessor-httpd( 2055): response: {"value":"Samples","result":"ok"}
D/houdini (21363): [21363] Loading library(version: 4.0.8.45720 RELEASE)... successfully.
D/houdini (21363): [21363] Open Native Library /data/app-lib/com.spaces.entry-1/libEntry.so failed.
D/AndroidRuntime(21363): Shutting down VM
W/dalvikvm(21363): threadid=1: thread exiting with uncaught exception (group=0x9cd3eb20)
D/BstCommandProcessor-Application( 2055): Application crash has been observed.
D/WindowManager( 1870): Sending appClickStats request with data: [package=com.spaces.entry, appname=Samples, appver=1.0, clickloc=system_server]

If delete the GC_INIT(), it can run normally.

**Comment by ivmai** [comment]
What does happen during GC_INIT?
I'm sorry I can't run a test on Android right now but I will test it by Jul 13 I think.

**Comment by ZeroKill1024** [comment]
I'am looking for the reasons too, but nothing has been found. If I find somthing I'll write here, or you find the reasion after test it on android.
Thanks!

**Comment by ivmai** [comment]
Probably fixed by patch in #259. Closing for now.
