### ISSUE TITLE
NINTENDO_SWITCH config problem

### ISSUE THREAD

**Issue by woollybah** [ivmai/bdwgc#228]
Hallo, I believe the NINTENDO_SWITCH defines in gcconfig.h are in the wrong section. They are currently under ARM32, but they should probably be under AARCH64 instead.

An attempt to build the library (using devkitpro) results in an error about STACKBOTTOM not being defined. However, if the defines are moved under AARCH64, the library builds okay.

**Comment by ivmai** [comment]
Thank you. Fixed.

PS. Nintendo support was added in commit 9718229 (issue #173) which is a cherry-pick of 9379c66 from https://github.com/Unity-Technologies/bdwgc)
