### ISSUE TITLE
test_cpp fail on Cygwin

### ISSUE THREAD

**Issue by ivmai** [ivmai/bdwgc#229]
Reported by @andyli: https://github.com/andyli/libgc-cygwin/pull/3

The reason of the failure is that operator delete defined in cyggccpp.dll is not called (the default one in c++  st library is called instead).

Observed on release-7_6 branch (e.g. v7.6.8) at least and current master (ae3d724).

**Comment by andyli** [comment]
Thanks for fixing it so quickly!
Are you going to make a new release? Alternatively, I can integrate as a patch to 7.6.8.

**Comment by ivmai** [comment]
Tip (for me): -D GC_NOT_DLL is essential if compiling client C++ code and linking it static libs on Cygwin, otherwise clang produces warnings in gc_cpp.h like:
replacement function 'operator new[]' cannot be declared 'inline'
