### ISSUE TITLE
Document key differences between 7.2, 7.4, and 7.6

### ISSUE THREAD

**Issue by murmour** [ivmai/bdwgc#230]
At the moment, there are three active branches: 7.2, 7.4, and 7.6.

While the ChangeLog is very detailed, containing hundreds of entries, it is difficult for me, as an end user, to decide whether it's worth upgrading from 7.2.

What are the _key_ changes in 7.4 and 7.6? Why were these branches created? What are the official recommendations on which version to use and why? I think all of these questions deserve an answer, if just a succinct one, in the README.

Thank you!

**Comment by ivmai** [comment]
Typically clients should use (upgrade to) the latest stable release (7.6.8 as of now). 

All releases branches (7.2 .. 7.6 as of now) are closed for new functionality addition (and optimization), i.e. every new release X.Y.Z just contains bug fixes comparing to X.Y.(Z-1).
If you are satisfied with the release you use now, it worth to upgrade to the latest version in the same release branch, at least.

I will summarize the key changes later.

PS. 8.0 branch is coming soon.

**Comment by ivmai** [comment]
Key changes between 7.6.8 and 8.0.0 (not yet released):
* support new targets
* new API
* enable sanitization by ASan, MSan, TSan, UBSan
* libatomic_ops is no longer needed (if using gcc/clang with built-in atomic operation support)

**Comment by murmour** [comment]
Thanks a lot! I found it helpful.

Perhaps it'd make sense to put these "version change digests" into README?

**Comment by ivmai** [comment]
I don't want to put information about particular releases (or the difference between releases) into README.
ChangeLog file should be more appropriate for the summary (version change digest), in my opinion. Alternately, we could put it to https://github.com/ivmai/bdwgc/releases page.

The information about the difference between legacy/stable/experimental is provided on https://github.com/ivmai/bdwgc/wiki/Download page.

**Comment by murmour** [comment]
> ChangeLog file should be more appropriate for the summary (version change digest), in my opinion.

Agreed. That'd be even better!
