### ISSUE TITLE
Darwin/ios12 -- GC_start_world doesn't resume all threads

### ISSUE THREAD

**Issue by dkimitsa** [ivmai/bdwgc#231]
This happens due mach thread ports are released in GC_stop_world as result in some cases system creates new and GC_start_world will not find thread to resume. as result threads will stay suspended. When this happen to GDC threads app is terminated as message loop is halt

**Comment by ivmai** [comment]
I see the issue, I will process the fix this week I hope.

**Comment by dkimitsa** [comment]
I've also created PR https://github.com/ivmai/bdwgc/pull/232 with fix we have applied in robovm project

**Comment by ivmai** [comment]
Please test the refactored patch which I've just pushed to master.

**Comment by dkimitsa** [comment]
did same tests on isolated start/stop world. It works. Thanks
