### ISSUE TITLE
License rules with libatomics as a dependency.

### ISSUE THREAD

**Issue by nickwanninger** [ivmai/bdwgc#234]
If I were to have this GC linked against a programming langauge I wrote, would there be any license worries?

libatomics seems to be GPLv2, but bdwgc itself seems to be similar to MIT/X11.

Is there a possibility of license problems if I have this link into the final binaries of my langauge?

**Comment by ivmai** [comment]
There should be no license issue even with static linking of bdwgc.
libatomic_ops is not used by default in bdwgc starting from libgc-8.0.0.
GPL'ed part of libatomic_ops (the rest is similar to MIT/X11) was never used in bdwgc.

**Comment by hboehm** [comment]
See libatomic_ops/doc/LICENSING.txt for details, mostly relevant for old
bdwgc versions now.
