### ISSUE TITLE
different symbol names on arm64 ilp32 and x86 ilp32

### ISSUE THREAD

**Issue by wookey** [ivmai/bdwgc#241]
I've been building libgc for arm64 ilp32 ABI (on debian GNU/linux). (background info at: https://wiki.linaro.org/Platform/arm64-ilp32 and https://wiki.debian.org/Arm64ilp32Port)

This worked OK (with a config patch) on libgc 7.4.2, but there is a problem with symbols on libgc 7.6.4.

The config patches I submitted to do this are in 7.6 (thanks for that), but the (debian) build fails when it  checks the symbol names. The offending symbols are:
(arch-bits=32)_ZdaPvj@Base 1:7.6.4
(arch-bits=64)_ZdaPvm@Base 1:7.6.4
(arch-bits=32)_ZdlPvj@Base 1:7.6.4
(arch-bits=64)_ZdlPvm@Base 1:7.6.4
(arch-bits=32)_Znaj@Base 1:7.6.4
(arch-bits=64)_Znam@Base 1:7.6.4
(arch-bits=32)_Znwj@Base 1:7.6.4
(arch-bits=64)_Znwm@Base 1:7.6.4

The issue seems to be that the method of annotating symbols has changed between 7.4 and 7.6.
Previously (7.4.2) these symbols were generated using size_t:
(subst)_Zna{size_t}@Base 1:7.2d
(subst)_Znw{size_t}@Base 1:7.2d

Now they are done using arch-bits.
On arm64ilp32 we get:
_ZdaPvm@Base
_ZdlPvm@Base
_Znam@Base
_Znwm@Base
'm' means 'unsigned long' according to c++filt
'j' means 'unsigned int'.

It seems that arm64 ILP32 uses unsigned long for size_t, whilst other 32-bit arches use unsigned int.
Both are 32 bits long (on this ABI), but they generate different C++ type-mangled symbol names.

So far as I can tell nothing is 'wrong' here except that the annotation in the symbols file makes an apparently-incorrect assumption about types across architectures/ABIs. The symbols file is actually part of the debian packaging so not directly an upstream issue, so this is probably a debian bug, but before filing that I wanted to check with you guys whether in fact it is correct that these symbols should match size_t type, rather than 'unsigned int'? (My understanding of how this codebase actually works is negligible.)

Is the symbol referring to 
  void* operator new(size_t size) GC_DECL_NEW_THROW {
    return GC_MALLOC_UNCOLLECTABLE(size);
  }
(and corresponding 'operator delete') 
 in gc_cpp.cc?

Those do use size_t parameters so if I've understood correctly then the subst size_t notation in the symbols files is correct and the arch-bits notation is wrong.
If you can confirm my understanding that I'll file this as a debian bug. 

Thanks for your time.

So the ABI is fine here - everything works (or should do - I've not really tested it), but there is a build issue.

**Comment by ivmai** [comment]
> Those do use size_t parameters so if I've understood correctly then the subst size_t notation in the symbols files is correct and the arch-bits notation is wrong.

Right.

I'd also recommend you to ask debian guys to upgrade libgc to 7.6.8.

**Comment by wookey** [comment]
OK, cheers for that clarification. This issue is tracked in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=872392
