### ISSUE TITLE
arm64 ILP32 minor documentation fix

### ISSUE THREAD

**Issue by wookey** [ivmai/bdwgc#242]
The configuration patch to make this ABI (arm64/aarch64 ILP32) available has already been accepted, which makes the docs/comments out of date. 
This minor patch makes the info on available ABIs more consistent.

+--- libgc-7.6.4.orig/include/private/gcconfig.h
++++ libgc-7.6.4/include/private/gcconfig.h
+@@ -639,6 +639,7 @@
+                     /*             S390       ==> 390-like machine      */
+                     /*                  running LINUX                   */
+                     /*             AARCH64    ==> ARM AArch64           */
++                    /*                  (LP64 and ILP32 variants)       */
+                     /*             ARM32      ==> Intel StrongARM       */
+                     /*             IA64       ==> Intel IPF             */
+                     /*                            (e.g. Itanium)        */

**Comment by ivmai** [comment]
Thank you, submitted (as 03aa2b1).
