### ISSUE TITLE
Visual Studio GC_malloc (unresolved external symbol, static linking)

### ISSUE THREAD

**Issue by zezba9000** [ivmai/bdwgc#248]
1) Ran cmake .\
2) Open with VS 2017 and build Debug for x86
3) Import gc-lib.lib into a new C program and method call to "GC_malloc".
4) Compile and get "unresolved external symbol" error.

Both gc-lib and my test app are built with "Multi-threaded Debug DLL (/MDd)".

Basic build instructions for Windows are just missing from the docs. Not sure what I'm missing.

**Comment by zezba9000** [comment]
Looks like only gcmt-dll.lib links correctly in VS 2017. So just have to ship the .dll file as well.

**Comment by ivmai** [comment]
cmake + MS VC is not well tested. Currently we have only CI for the dynamic libgc: https://ci.appveyor.com/project/ivmai/bdwgc/build/job/hd9qxujvrvb6jaab

The documentation is poor too, sorry. The patches are welcomed!

Anyway, you could build the static library right from your app, e.g.:
cl -I include -I libatomic_ops/src -Ox -DGC_THREADS -DTHREAD_LOCAL_ALLOC -DPARALLEL_MARK -c extra/gc.c

**Comment by zezba9000** [comment]
Ok tnx for info.

I will make a .bat for Windows and .sh file for Posix systems that auto builds the lib for most common use cases with minimal effort.

After I have time to get that done, will submit a pull request or first submit here for feedback on the scripts operation.

**Comment by ivmai** [comment]
Hmm. Do you mean the .sh file will contain just ./configure && make ?

**Comment by ivmai** [comment]
I mean why not to fix static lib generation in cmake file? Or improve the documentation that you miss?

**Comment by zezba9000** [comment]
Nothing wrong with cmake. My thinking was along the lines of portability in terms a legacy systems.
Relying on cmake means if I wanted to target an older system with beohm I will now have to also find an older version of cmake and hope it still works with the newer CMakeLists.txt file (thats at least a potential in the future).  Because cmake fundamentally relies on the sdks installed on your computer it may become harder to generate older VS projs as time goes on with older compilers / IDEs.

If however you just generate a .bat or .sh file that manually builds the .c files it works without needing any 3rd party platform specific generation tools existing on the computer you're compiling with. Its more explicit vs implicit way to build stuff. You can generate the .bat or .sh files on a modern PC and with a far degree of certainty it will compile on legacy systems with no additional effort. (This .bat / .sh generation tool is something I plan on making later for my own sanity as it allows me to build on Linux, macOS and Windows in an almost identical manor).

Anyway sorry know its not directly related to this gc proj but an issue I've noticed with many cross platform build systems.

**Comment by zezba9000** [comment]
> I mean why not to fix static lib generation in cmake file? Or improve the documentation that you miss?
-- With how you have things setup up probably the simplest solution for sure. My confusing came from only seeing the docs talk about make (which isn't useful for using the VC++ compiler). In the short term I can update the docs to suggest cmake on windows with the correct args and note that it only supports non-static linking if that sounds reasonable.

**Comment by ivmai** [comment]
There are also MS VC scripts in windows-untested (on Github).

**Comment by ivmai** [comment]
> In the short term I can update the docs to suggest cmake on windows with the correct args and note that it only supports non-static linking if that sounds reasonable.

It's OK.
