### ISSUE TITLE
Use soft dirty bits on Linux

### ISSUE THREAD

**Issue by ivmai** [ivmai/bdwgc#265]
From @hboehm:
Has anyone added soft dirty bits support to bdwgc? It seems like an opportunity, if it hasn't already been done.

PS. Doc about soft dirty bits: https://www.kernel.org/doc/Documentation/vm/soft-dirty.txt

**Comment by ivmai** [comment]
From the documentation, it is unclear to me how to read soft dirty bits and clear them atomically (otherwise we could loose some writes between reading and clearing the bits).

**Comment by ivmai** [comment]
The most disappointing this here is that soft-dirty bit is not supported by linux/arm and linux/aarch64.

**Comment by ivmai** [comment]
Feature is enabled for i686, x86_64, mips and powerpc.

**Comment by ivmai** [comment]
BTW, @hboehm, as soft-dirty bits are on available on ARM, do you know any alternative there (other than mprotect-based VDB)?

PS. I see someone proposed [soft-dirty support for Aarch64](https://patchwork.kernel.org/project/linux-arm-kernel/patch/1512029649-61312-1-git-send-email-bin.lu@arm.com/) but it is still not merged.

**Comment by hboehm** [comment]
Has someone looked at userfaultfd and UFFDIO_REGISTER_MODE_WP? That seems
to require a very recent kernel, but maybe that's now the intended way
forward here? My impression is that this is much easier on kernel resources
than explicit mprotect calls. But it's probably worth confirming with an
actual kernel expert.
