### ISSUE TITLE
Mesh: Compacting memory management for C/C++ applications

### ISSUE THREAD

**Issue by PaulBone** [ivmai/bdwgc#267]
Here is a paper a colleague passed to me with an interesting idea for compacting memory in an uncooperative environment.  This is not an "issue" or even a "request".  But if there was a mailing list I would have sent it there.

https://arxiv.org/pdf/1902.04738.pdf

TL;DR: The paper claims to show that meshing of two pages (by aliasing them) with disjoint sets of allocations is tractable and can improve fragmentation.

**Comment by ivmai** [comment]
This might be interesting in case of huge pages use (#165).

**Comment by ivmai** [comment]
The algorithm from the paper is implemented in: https://github.com/plasma-umass/mesh
