### ISSUE TITLE
SIGSEGV in disclaim_bench on Cygwin

### ISSUE THREAD

**Issue by ivmai** [ivmai/bdwgc#270]
Build link: https://ci.appveyor.com/project/ivmai/bdwgc/builds/23091862/job/yefwe044t173i2hw
Source: latest master (12b5d3897)
Host: win32/cygwin (some 2-core virtual host)
Build config: ./configure --enable-cplusplus && make -j check-without-test-driver CFLAGS_EXTRA=-DGCTEST_PRINT_VERBOSE

**Comment by ivmai** [comment]
Cannot reproduce locally.

**Comment by ivmai** [comment]
\+ @paurkedal

**Comment by ivmai** [comment]
Still observed on latest master (c85518128) multiple runs of "make check-without-test-driver" (~10 times) on AppVeyor (32-bit Cygwin only).

**Comment by paurkedal** [comment]
Sorry for not commenting before, but I have neither knowledge nor access to a Cygwin environment, so I am not sure how much help I can be on this issue.

Getting a backtrace might give a clue about the cause if we are lucky. Maybe it could be useful in any case to invoke gdb in the CI script if a core file appears? Also, `lscpu` (or the Cygwin equivalent) output might give a clue about the underlying hardware, in case it's something outside the collector (like a Skylake CPU without patched firmware), but the utility of this is limited by the fact that it's running in a VM.

**Comment by ivmai** [comment]
@paurkedal, OK, I will look into it. Thank you for the advice.

**Comment by ivmai** [comment]
Tip for me: Fail on latest master: https://ci.appveyor.com/project/ivmai/bdwgc/builds/31119739/job/nwfqlgnvqp60n6ux

**Comment by ivmai** [comment]
Tip for me: Reproduced on fresh master: https://ci.appveyor.com/project/ivmai/bdwgc/builds/40838900/job/tax8hhs0vqxtw2ax (commit https://github.com/ivmai/bdwgc/commit/198f7adbc5d335d65ca6eb4ca1f8befa15404e33)
TARGET=cygwin
CONF_OPTIONS=--disable-thread-local-alloc --disable-gcj-support --enable-gc-assertions
CFLAGS_EXTRA=-O0 -D GC_DISABLE_INCREMENTAL

**Comment by ivmai** [comment]
Stack trace:
```
#11 0x0028c490 in ?? ()
#12 0x66242106 in get_index (addr=4246929408) at extra/../headers.c:232
#13 0x662421b6 in GC_install_header (h=0xfd230000) at extra/../headers.c:265
#14 0x66246c0b in add_to_heap_inner (p=0xfd230000, bytes=16777216)
    at extra/../alloc.c:1406
#15 0x66247275 in GC_add_to_heap (space=0xfd230000, bytes=16777216)
--Type <RET> for more, q to quit, c to continue without paging--
    at extra/../alloc.c:1603
#16 0x66247022 in GC_scratch_recycle_inner (ptr=0xfd230000, bytes=16777216)
    at extra/../alloc.c:1535
#17 0x66250c04 in alloc_mark_stack (n=4194304) at extra/../mark.c:1264
#18 0x6624f961 in GC_mark_some (cold_gc_frame=0x28cab8 "\b\313(")
    at extra/../mark.c:348
#19 0x66245d28 in GC_stopped_mark (stop_func=0x66244e5f <GC_never_stop_func>)
    at extra/../alloc.c:880
#20 0x66245862 in GC_try_to_collect_inner (
    stop_func=0x66244e5f <GC_never_stop_func>) at extra/../alloc.c:626
#21 0x66246897 in GC_try_to_collect_general (stop_func=0x0, force_unmap=0)
    at extra/../alloc.c:1292
#22 0x66246996 in GC_gcollect () at extra/../alloc.c:1317
#23 0x00401510 in main (argc=1, argv=0x28cc4c) at tests/disclaim_bench.c:145
```

**Comment by ivmai** [comment]
```
(gdb) fr 12
#12 0x66242106 in get_index (addr=4246929408) at extra/../headers.c:232
232         BZERO(r, sizeof(bottom_index));
(gdb) p r
$1 = (bottom_index *) 0x2388d0
(gdb) p *r
Cannot access memory at address 0x2388d0
```

**Comment by ivmai** [comment]
Looks like pointer arithmetic overflow in GC_scratch_alloc

**Comment by ivmai** [comment]
Fixed. Not reproduced anymore (https://ci.appveyor.com/project/ivmai/bdwgc/builds/40840400)
