### ISSUE TITLE
Fix cmake build on MacOS

### ISSUE THREAD

**Issue by nickwanninger** [ivmai/bdwgc#275]
I get this error on every single file that the CMake program attempts to compile. Is this a known problem or is my machine not configured correctly?

```
In file included from /var/folders/33/mjfjj83j3zgc_hfnrkj9wkjw0000gn/T/tmp.HMPg99oq/bdwgc/alloc.c:19:
In file included from /var/folders/33/mjfjj83j3zgc_hfnrkj9wkjw0000gn/T/tmp.HMPg99oq/bdwgc/include/private/gc_priv.h:59:
In file included from /usr/include/stdlib.h:65:
In file included from /usr/include/sys/wait.h:109:
In file included from /usr/include/sys/signal.h:150:
In file included from /usr/include/sys/_types/_sigaltstack.h:40:
/usr/include/machine/types.h:37:2: error: architecture not supported
#error architecture not supported
 ^
```

**Comment by ivmai** [comment]
CMake works on Windows. Should work on other hosts but not tested for ages. The script contains some workaround for MacOS:
```
IF(APPLE)
    IF("${CMAKE_OSX_ARCHITECTURES}" STREQUAL "")
        SET(CMAKE_OSX_ARCHITECTURES "ppc;i386;x86_64" CACHE STRING "Build architectures for Mac OS X" FORCE)
    ENDIF()
ENDIF(APPLE)
```
I guess it should not be difficult to fix the build.

**Comment by nickwanninger** [comment]
Hmm, I've looked into this and the only way I can get it working is by a) moving that workaround to above the `project()` call, and b) changing the architectures to only "x86_64".

```
IF(APPLE)
    IF("${CMAKE_OSX_ARCHITECTURES}" STREQUAL "")
        SET(CMAKE_OSX_ARCHITECTURES "x86_64" CACHE STRING "Build architectures for Mac OS X" FORCE)
    ENDIF()
ENDIF(APPLE)
```

Doing this allows me to fully compile using cmake on macos

**Comment by ivmai** [comment]
If you know how to fix this in GC, please contribute.

**Comment by vicroms** [comment]
@nickwanninger 

I've opened a PR (#281) to modify the existing CMakeLists.txt, which I believe is due for modernization. 

I'll try to add your workaround there as well.

**Comment by vicroms** [comment]
Hi @nickwanninger 
It's been a while, but can you test whether the patches in PR #281 work for you?

**Comment by nickwanninger** [comment]
Yes I will look into the PR really quick

**Comment by nickwanninger** [comment]
@vicroms, #281 doesn't seem to work for me. I simply did a `mkdir build; cd build; cmake ..; make` and it fails on the final make with the same error as it did before

**Comment by vicroms** [comment]
I see, I'll try to get a Mac to make some more local testing.
Thanks @nickwanninger!

**Comment by nickwanninger** [comment]
Ill see what I can figure out as well

**Comment by nickwanninger** [comment]
@vicroms. So it seems that running cmake with `cmake .. -DCMAKE_OSX_ARCHITECTURES=x86_64` allows builds on macos in your PR

**Comment by ivmai** [comment]
> I've looked into this and the only way I can get it working is by a) moving that workaround to above the project() call, and b) changing the architectures to only "x86_64".

@nickwanninger moving that workaround to above the project() is not needed, right?

**Comment by nickwanninger** [comment]
It seems like it. I was able to just run with that flag on @vicroms' PR with no modifications

**Comment by ivmai** [comment]
Hello @nickwanninger, @vicroms,
I have modified the cmake script in the master branch since this discussion, e.g. multi-threaded builds are on by default now. It would be nice if you test the latest version if it works OK for you.
