### ISSUE TITLE
CORD_len("") returns arbitrary value 

### ISSUE THREAD

**Issue by sequix** [ivmai/bdwgc#278]
I'm trying to write a function f like:
if (CORD_len(s) == 0) {
return CORD_EMPTY;
}

CORD_pos i;  CORD_FOR(i, cord) {  ... CORD_pos_fetch(i) ... } 

when I call f(""), it says:
CORD_pos_fetch: bad leaf

after some examination, I found CORD_len("") returns something arbitrary.
Shouldn't it return zero?

**Comment by ivmai** [comment]
No. CORD_len accepts CORD values, "" is not a valid CORD value. See the comment in cord.h:

```
/* Cords have type const char *.  This is cheating quite a bit, and not */
/* 100% portable.  But it means that **nonempty** character string          */
/* constants may be used as cords directly, provided the string is      */
/* never modified in place.  The empty cord is represented by, and      */
/* can be written as, 0.                                                */
```

This behavior can't be changed because zero (of the first character) is used to distinguish between C strings and CordRep values:
```
/* Is a nonempty cord represented as a C string? */
#define CORD_IS_STRING(s) (*(s) != '\0')
```
