### ISSUE TITLE
[Question] Measure the peak memory consumption.

### ISSUE THREAD

**Issue by rtakacs** [ivmai/bdwgc#279]
Hi Ivan,

I'd like to calculate the peak memory usage of my application. To do this, I'd like to monitor the allocations and deallocations. The following is a short description of the concept. I hope you can validate/correct that.

**Allocation monitoring**
All the allocator macros (`GC_MALLOC`, `GC_REALLOC`, `GC_STRDUP`, ...) are hooked in order to save the given pointers their original size (the requested size and not GC_size). An example:

```c
// Track all the pointers with the size.
// The size is needed to know when free happens.
std::map<void*, size_t> addressTable;
size_t allocated = 0;
size_t peak_allocated = 0;

#undef GC_MALLOC
#define GC_MALLOC(size) GC_malloc_hook(size)

void* GC_malloc_hook(size_t size)
{
#if defined(GC_DEBUG)
    void* ptr = GC_debug_malloc(size, GC_EXTRAS);
#else
    void* ptr = GC_malloc(size);
#endif
    addressTable[ptr] = size;  // Save the pointer and its size.
    allocated += size;

    if (allocated > peak_allocated)
        peak_allocated = allocated;

    return ptr;
}
```

**Deallocation monitoring**
There are two solutions at this part: 

**The first solution** is to use the `GC_debug_register_finalizer_no_order` method to register a finalizer callback for each pointer (given by `GC_MALLOC` and its friends). In this case the GC can notify before deallocating the memory area.
Note that `GC_FREE` explicit calls should also be checked, because (as I checked) the finalizer callbacks won't  executed when explicit free happens. An example:

```c
void* GC_malloc_hook(size_t size)
{
#if defined(GC_DEBUG)
    void* ptr = GC_debug_malloc(size, GC_EXTRAS);
#else
    void* ptr = GC_malloc(size);
#endif
    // Same as above.

    GC_REGISTER_FINALIZER_NO_ORDER(ptr, [](void* obj, void* cd)
    {
       allocated -= addressTable[obj];
       addressTable.erase(obj);
    }, nullptr, nullptr, nullptr);

    return ptr;
}

#undef GC_FREE
#define GC_FREE(address) GC_free_hook(address)

void GC_free_hook(void* address)
{
#if defined(GC_DEBUG)
    GC_debug_free(address);
#else
    GC_free(address);
#endif
    allocated -= addressTable[address];
    addressTable.erase(address);
}
```

**The second solution** to check the memory deallocations is based on the GC collection event. If a callback is registered  (by `GC_set_on_collection_event`) to the `GC_EVENT_END`, after the GC execution, all the manually tracked pointers can be validated by the `GC_is_valid_displacement` function. If a pointer is not valid (probably freed by `GC_FREE` or `GC finalizer`), the `GC_is_valid_displacement_print_proc` is executed. An example:

```c
    GC_is_valid_displacement_print_proc = [](void* ptr)
    {
         allocated -= addressTable[ptr];
         addressTable.erase(ptr);
    };

    GC_set_on_collection_event([](GC_EventType evtType)
    {
        if (GC_EVENT_END != evtType)
            return;

        // Loop on all the tracked pointers and check their validity after GC.
        auto iter = addressTable.begin();
        while (iter != addressTable.end()) {
            GC_is_valid_displacement(iter->first);
            iter++;
        }
    });
```

What do you think about the deallocation monitoring solutions? Are the two solutions equivalent? Which is the better for this purpose?

Best regards,
  Roland

**Comment by ivmai** [comment]
I think it is better to post it here: https://stackoverflow.com/questions/tagged/boehm-gc

**Comment by rtakacs** [comment]
Oh, you are right :)

I've posted this question to stackoverflow:
https://stackoverflow.com/questions/55937194/measure-the-peak-memory-consumption
