### ISSUE TITLE
mmap(PROT_NONE) failure on AIX

### ISSUE THREAD

**Issue by wangp** [ivmai/bdwgc#285]
`make check` fails on AIX 7.1 if --enable-munmap is used (or left at the default configuration on master and 8.0 branches).
```
================================
   gc 8.1.0: ./test-suite.log
================================

# TOTAL: 11
# PASS:  8
# SKIP:  0
# XFAIL: 0
# FAIL:  3
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: gctest
============

mmap(PROT_NONE) failed
FAIL gctest (exit status: 134)

FAIL: staticrootstest
=====================

mmap(PROT_NONE) failed
FAIL staticrootstest (exit status: 134)

FAIL: disclaim_test
===================

mmap(PROT_NONE) failed
Unthreaded disclaim test.
FAIL disclaim_test (exit status: 134)
```

**Comment by wangp** [comment]
The mmap(PROT_NONE) call in GC_unmap() returns -1 with errno = ENOMEM. The man page says mmap() returns ENOMEM when:
> There is not enough address space to map len bytes, or the application has not requested Single UNIX Specification, Version 2 compliant behavior and the MAP_FIXED flag was set and part of the address-space range (addr, addr+len) is already allocated.

Setting the environment variable XPG_SUS_ENV=ON - all the tests pass.

Removing MAP_FIXED from the mmap() call - all the tests pass.

Using the mprotect(PROT_NONE) code path currently used for Cygwin - all the tests pass.

**Comment by ivmai** [comment]
Could you please make a PR?

**Comment by wangp** [comment]
Removing MAP_FIXED didn't make sense to me (though I am no expert) so I chose to use mprotect().

**Comment by ivmai** [comment]
Hello @wangp,

> Using the mprotect(PROT_NONE) code path currently used for Cygwin - all the tests pass.

Have you checked that the memory unmapping (returning memory to OS) really happens after the fix on AIX?
I think madvise(MADV_DONTNEED) might be needed after mprotect(PROT_NONE) (or even replace mprotect() call).
I've checked Cygwin - mprotect() returns memory to OS (and madvise() is a no-op on Cygwin).

[Here](https://github.com/ivmai/bdwgc/issues/311#issuecomment-1018837152)'s a small how-to, just use the proper commit (either the commit mentioned above or release-8_0 branch, or c91eaf6edc which is nearly latest master).

**Comment by wangp** [comment]
(I had trouble with the autoconf build system at this time, so I used Makefile.direct. I tested commit c91eaf6edcf8134d63c371b69411af39b91981e1.)

AIX doesn't have `top` as far as I know but I think the info is available from `ps`.

With unmapping enabled:
```
cecuser@p1293-pvm1:/home/cecuser/bdwgc $ ./gctest &
[1] 21168426
cecuser@p1293-pvm1:/home/cecuser/bdwgc $ Completed 6 tests
Allocated 4078367 collectable objects
Allocated 1218 uncollectable objects
Allocated 8216820 atomic objects
Reallocated 756 objects
Garbage collection after fork is tested too
Finalized 13218/13218 objects - finalization is probably OK
Total number of bytes allocated is 560829676
Total memory use by allocated blocks is 1327104 bytes
Final heap size is 446464 bytes
Obtained 9150464 bytes from OS (of which 8245248 bytes unmapped)
Final number of reachable objects is 2723
Completed 412 collections in 159 ms
Collector appears to work

cecuser@p1293-pvm1:/home/cecuser/bdwgc $ ps v | grep -E 'gcte|RSS'
      PID    TTY STAT  TIME PGIN  SIZE   RSS   LIM  TSIZ   TRS %CPU %MEM COMMAND
 21168426  pts/1 A     0:05    0 10192 10784 32768   140   592  1.0  0.0 ./gcte
```

With unmapping disabled:
```
cecuser@p1293-pvm1:/home/cecuser/bdwgc $ GC_UNMAP_THRESHOLD=0 ./gctest & 
[1] 21168428
cecuser@p1293-pvm1:/home/cecuser/bdwgc $ Completed 6 tests
Allocated 4078367 collectable objects
Allocated 1218 uncollectable objects
Allocated 8216820 atomic objects
Reallocated 756 objects
Garbage collection after fork is tested too
Finalized 13218/13218 objects - finalization is probably OK
Total number of bytes allocated is 560829676
Total memory use by allocated blocks is 1323008 bytes
Final heap size is 8691712 bytes
Obtained 9150464 bytes from OS (of which 0 bytes unmapped)
Final number of reachable objects is 2722
Completed 396 collections in 161 ms
Collector appears to work

cecuser@p1293-pvm1:/home/cecuser/bdwgc $ ps v | grep -E 'gcte|RSS'
      PID    TTY STAT  TIME PGIN  SIZE   RSS   LIM  TSIZ   TRS %CPU %MEM COMMAND
 21168428  pts/1 A     0:01    0 10196 10788 32768   140   592  0.5  0.0 ./gcte
```

There isn't any great difference between the SIZE and RSS columns so I think memory is not being returned to the OS.
The man page says:
```
       RSS
            (v flag) The real-memory (resident set) size of the process (in 1 KB units).
       SIZE
            (v flag) The virtual size of the data section of the process (in 1 KB units).
```

I tried `madvise(MADV_DONTNEED)` as well but it didn't help, from what I can tell.

**Comment by ivmai** [comment]
> I tried madvise(MADV_DONTNEED) as well but it didn't help, from what I can tell.

Okay, just to be sure, could you please recheck it again on unmodified latest master (commit c66af36a2)? just with unmapping enabled would be enough.

**Comment by wangp** [comment]
There's no difference with commit c66af36 either.

**Comment by ivmai** [comment]
Got it, thank for checking. I've opened #421.
