### ISSUE TITLE
Crashes with "sem_wait failed" when creating many threads on macOS

### ISSUE THREAD

**Issue by thomasthiriez** [ivmai/bdwgc#296]
Hi,

I have an application that uses libgc on macOS, and it randomly crashes when it creates many threads, with this message:

`sem_wait failed`

Produced on this line: [pthread_support.c#L1986](https://github.com/ivmai/bdwgc/blob/ed912875addff7e0724e5da2734b8f878c4f7148/pthread_support.c#L1986)

On macOS, the semaphore is actually a `pthread_mutex`, and it is the call to `pthread_mutex_lock` that fails with an error of `EINVAL`, there: [darwin_semaphore.h#L67](https://github.com/ivmai/bdwgc/blob/ed912875addff7e0724e5da2734b8f878c4f7148/include/private/darwin_semaphore.h#L67)

Further experimentation has revealed that two threads were using the same semaphore, and one thread has destroyed the semaphore before the other could lock it.

The semaphore is stored in a `start_info` structure. That structure is allocated by a call to `GC_INTERNAL_MALLOC` ([here](https://github.com/ivmai/bdwgc/blob/ed912875addff7e0724e5da2734b8f878c4f7148/pthread_support.c#L1906)), and later released with `GC_INTERNAL_FREE` ([here](https://github.com/ivmai/bdwgc/blob/ed912875addff7e0724e5da2734b8f878c4f7148/pthread_support.c#L1992)).

In the case where the crash occurs, two threads are created, each one of them calls `GC_INTERNAL_MALLOC` to allocate a start_info, and the `GC_INTERNAL_MALLOC` function returns the same address. I have checked that `GC_INTERNAL_FREE` has not been called between the two `GC_INTERNAL_MALLOC` calls.

So the two threads end up using the same memory area to store the semaphore, and that leads to trouble.

After studying the code, I couldn't understand why that structure was being allocated dynamically in the first place. I have modified the code to allocate it on the stack instead, and the `sem_wait failed` crash has disappeared.

Even if my solution fixes the problem, it would be nice to study `GC_INTERNAL_MALLOC` and understand why it returns twice the same address in the first place.

Regards,
Thomas Thiriez

**Comment by ivmai** [comment]
> two threads are created, each one of them calls GC_INTERNAL_MALLOC to allocate a start_info

Do you mean that 2 threads have invoked GC_pthread_create (almost in parallel)?
If yes, could you please check that these threads are both registered (i.e. check GC_thread_is_registered result before calling GC_pthread_create)

> is this reproducible without various GC optimizations? (-D GC_DISABLE_INCREMENTAL -U THREAD_LOCAL_ALLOC -U PARALLEL_MARK -U USE_MUNMAP)

>  I have modified the code to allocate it on the stack instead
Yes, it is technically possible to allocate this on the stack of the thread creator. But it is somewhat a hack I want to avoid (because accessing some other's stack is a bad design), not to mention, as you said, it's a workaround not a bug fix.

**Comment by ivmai** [comment]
Alternatively we could use GC_malloc_uncollectable but it's a workaround too.

> I have checked that GC_INTERNAL_FREE has not been called between the two GC_INTERNAL_MALLOC calls.

It might be reclaimed because the garbage collector sees it as unreachable.

**Comment by thomasthiriez** [comment]
> Do you mean that 2 threads have invoked GC_pthread_create (almost in parallel)?
> If yes, could you please check that these threads are both registered (i.e. check GC_thread_is_registered result before calling GC_pthread_create)

Yes two threads are created very closely. I am not sure I can check if the thread is registered before calling `GC_pthread_create`, because the thread does not exist before that function is called. And the created thread is registered by `GC_start_rtn_prepare_thread` that calls `GC_register_my_thread_inner` at [pthread_support.c#L1848](https://github.com/ivmai/bdwgc/blob/ed912875addff7e0724e5da2734b8f878c4f7148/pthread_support.c#L1848).

> Is this reproducible without various GC optimizations? (-D GC_DISABLE_INCREMENTAL -U THREAD_LOCAL_ALLOC -U PARALLEL_MARK -U USE_MUNMAP)

Yes, I was able to reproduce the problem with these compiler options.

> Yes, it is technically possible to allocate this on the stack of the thread creator. But it is somewhat a hack I want to avoid (because accessing some other's stack is a bad design), not to mention, as you said, it's a workaround not a bug fix.

Yes, it is a workaround for a seemingly faulty `GC_INTERNAL_MALLOC` function, but it looks like very good design to me. I don't see anything wrong with temporarily storing the semaphore on the stack. It is exactly what the stack is for. I would even argue that if `GC_INTERNAL_MALLOC` worked as intended, storing the semaphore on the stack would still be a much better design.

When you call a function, `GC_pthread_create` in our case, you certainly expect it to borrow your stack, and that is not bad design. The `start_info` struct has the same life span as the `result` variable. Why don't you dynamically allocate this `int result;` as well?

**Comment by ivmai** [comment]
> it looks like very good design to me. I don't see anything wrong with temporarily storing the semaphore on the stack. It is exactly what the stack is for

OK, I agree, I'm fine with the change to allocating it on the stack.

But, it would be good to figure out what's wrong with the GC_INTERNAL_MALLOC.

> Yes two threads are created very closely. I am not sure I can check if the thread is registered before calling GC_pthread_create, because the thread does not exist before that function is called.

Hmm. Looks like we are miscommunicating. I mean the 2 threads that call GC_pthread_create. To ensure the thread is registered, just check the result of GC_thread_is_registered() is non-zero (call GC_thread_is_registered just before GC_pthread_create).

 And the created thread is registered by GC_start_rtn_prepare_thread that calls GC_register_my_thread_inner

Do you mean

**Comment by thomasthiriez** [comment]
> OK, I agree, I'm fine with the change to allocating it on the stack.

Thanks! I will work on a pull request.

> But, it would be good to figure out what's wrong with the GC_INTERNAL_MALLOC.

Certainly. I have tried digging further, but it is getting very complex.

I have tried allocating a second start_info struct, on the very next line:

```c
si = GC_INTERNAL_MALLOC(...);
si2 = GC_INTERNAL_MALLOC(...);
```

In some cases, the second `GC_INTERNAL_MALLOC` call returns the same address, and `si == si2`. It appears that the first one is being garbage collected by the second `GC_INTERNAL_MALLOC` call.

I have also discovered another failure mode. In some cases, it aborts with this message: "Duplicate large block deallocation". This crash also disappears when I allocate the start_info structure on the stack.

> Hmm. Looks like we are miscommunicating. I mean the 2 threads that call GC_pthread_create.

Oops, of course. Sorry for the confusion.

I have checked, and all the threads that call GC_pthread_create are correctly registered. That would otherwise have explained why the `start_info` would get garbage collected too early. Is there anything else that could be causing that?

**Comment by ivmai** [comment]
>> Is this reproducible without various GC optimizations? (-D GC_DISABLE_INCREMENTAL -U THREAD_LOCAL_ALLOC -U PARALLEL_MARK -U USE_MUNMAP)
>
> Yes, I was able to reproduce the problem with these compiler options.

Just to clarify, I meant, if you use configure: ./configure --disable-thread-local-alloc --disable-parallel-mark --disable-unmap --enable-gc-assertions && make CFLAGS_EXTRA="-D GC_DISABLE_INCREMENTAL"

Is GC_INTERNAL_MALLOC defined as GC_generic_malloc_inner in your case?

> si = GC_INTERNAL_MALLOC(...);
> si2 = GC_INTERNAL_MALLOC(...);
> In some cases, the second GC_INTERNAL_MALLOC call returns the same address, and si == si2

Could you also please check that if could observe si2 == si3 with GC_malloc?

    LOCK();
    si = (struct start_info *)GC_INTERNAL_MALLOC(sizeof(struct start_info),
                                                 NORMAL);
    UNLOCK();
\+    si2 = GC_malloc(sizeof(struct start_info));
\+    si3 = GC_malloc(sizeof(struct start_info));

**Comment by thomasthiriez** [comment]
> Just to clarify, I meant, if you use configure: ./configure --disable-thread-local-alloc --disable-parallel-mark --disable-unmap --enable-gc-assertions && make CFLAGS_EXTRA="-D GC_DISABLE_INCREMENTAL"

> Is GC_INTERNAL_MALLOC defined as GC_generic_malloc_inner in your case?

Yes, I did that:

./configure CC="gcc -g -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -mmacosx-version-min=10.9 -D GC_DISABLE_INCREMENTAL" --disable-thread-local-alloc --disable-parallel-mark --disable-munmap --enable-gc-assertions

And I have verified that GC_INTERNAL_MALLOC expands to GC_generic_malloc_inner. I didn't have --enable-gc-assertions at first. I have now added it, with the same behavior.

> Could you also please check that if could observe si2 == si3 with GC_malloc?

I have tested with:

```c
LOCK();
si = (struct start_info *)GC_INTERNAL_MALLOC(sizeof(struct start_info),
                                             NORMAL);
UNLOCK();

si2 = GC_malloc(sizeof(struct start_info));
si3 = GC_malloc(sizeof(struct start_info));
```

And balancing the `GC_malloc` calls with `GC_free` further down. I didn't have any si2 == si3, but I had si == si2.

I have also tested this:

```c
si  = GC_malloc(sizeof(struct start_info));
si2 = GC_malloc(sizeof(struct start_info));
```

And I am getting si == si2.

**Comment by ivmai** [comment]
It's interesting. Let's try to figure out the root cause with the previous variant of the code:
LOCK();
si = GC_generic_malloc_inner(sizeof(struct start_info), NORMAL);
si2 = GC_generic_malloc_inner(sizeof(struct start_info), NORMAL);
assert si != s2
UNLOCK();

GC_generic_malloc_inner could be simplified for these 2 invocations as follows
void * GC_generic_malloc_inner(size_t lb, int k)
{
    void *op;
    struct obj_kind * kind = GC_obj_kinds + k;
    size_t lg = GC_size_map[lb];
    void ** opp = &(kind -> ok_freelist[lg]);

    op = *opp;
    if (0 == op) {
      if (lg == 0) {
        GC_extend_size_map(lb);
        lg = GC_size_map[lb];
        opp = &(kind -> ok_freelist[lg]);
        op = *opp;
      }
      if (0 == op) {
        if (0 == kind -> ok_reclaim_list)
          GC_alloc_reclaim_list(kind);
        op = GC_allocobj(lg, k);
      }
    }
    *opp = obj_link(op);
    obj_link(op) = 0;
    return op;
}

Each time it returns an allocated memory, *opp is modified, so it seems unclear how 2 subsequent calls could return the same pointer.

When you observe si == si2, what is the control flow in the 1st invocation and in the 2nd invocation? (it should not be difficult to do - just create GC_generic_malloc_inner1 and GC_generic_malloc_inner2 and using some global vars to record the control flow in each of the function)

**Comment by thomasthiriez** [comment]
On the first call to `GC_generic_malloc_inner`, there is one object in the free list, and it is returned.

On the second call, because the list is now empty, `GC_allocobj` is called, and the free list is repopulated with this call stack:

```
GC_allocobj
GC_continue_reclaim
GC_reclaim_small_nonempty_block
GC_reclaim_generic
GC_reclaim_clear
```

A number of objects are added to the list, around 10 or 20, depending on the run. The last one pushed to the list is the same one that was returned by the first `GC_generic_malloc_inner`, so it is returned a second time, causing the crash.

**Comment by thomasthiriez** [comment]
I believe the first object returned by `GC_generic_malloc_inner` is being garbage collected when the second call to `GC_generic_malloc_inner` finds an empty free list.

The first object is collected, because it is not marked as reachable. `GC_is_marked(si)` is false. Is there a function that should have marked the object to prevent it from being reclaimed?

**Comment by ivmai** [comment]
LOCK();
si = GC_generic_malloc_inner(sizeof(struct start_info), NORMAL);
GC_set_mark_bit(si);
si2 = GC_generic_malloc_inner(sizeof(struct start_info), NORMAL);
assert si != s2
UNLOCK();

**Comment by ivmai** [comment]
si should be marked by GC_push_all_stack (when thread == my_thread) called by GC_push_all_stacks in darwin_stop_world.c.

Is GC_query_task_threads true or false in your case?

I see the following potential cases:
1. "si" is in the register, the register is not stored to stack and thus not canned. You could check it by forcing "si" to be a non-register variable (i.e. declare it as volatile)
2. si is stored to the stack it is out of the stack region that is scanned. You could print "si" address and also print the scanned stack region of the current thread (i.e. lo, hi arguments of GC_push_all_stack calls when thread == my_thread).

**Comment by ivmai** [comment]
Could you please also try with the commented out lines in GC_push_regs_and_stack:
      if (NULL == cold_gc_frame)
        return; /* GC_push_all_stacks should push registers and stack */

**Comment by ivmai** [comment]
Is NO_GETCONTEXT defined by configure or in gcconfig.h? Could you please also try w/o NO_GETCONTEXT?

**Comment by thomasthiriez** [comment]
GC_push_all_stack is not called between the two malloc calls. I’ll have more time to look into this later tonight.

**Comment by hboehm** [comment]
A corrupted reclaim_list containing a cycle might also do this? Could the
same block be reclaimed more than once?

**Comment by thomasthiriez** [comment]
I found it.

While investigating why the stack returned by `GC_stack_range_for` would not include `&si`, I found it was caused by a `GC_do_blocking` higher in the stack.

The documentation for the `GC_do_blocking` function says I should not allocate garbage collected memory, but it is not immediately obvious whether creating threads is allowed or not. I assume it is fine, now that `si` is allocated on the stack.

Would it be a good idea to add an assert to verify that the GC is active in the allocation functions?

`GC_ASSERT(!(me -> thread_blocked));`

**Comment by ivmai** [comment]
> Would it be a good idea to add an assert to verify that the GC is active in the allocation functions?

Not easy to add the assertion. So, I am leaving it as-is. The comment of GC_do_blocking is rather big but it provides a note that GC functions as well as GC pointer manipulations are not safe while in blocking state.

Anyway, your commit about the struct allocation on the stack is a good thing. Thank you
