### ISSUE TITLE
Memory leak while exit.

### ISSUE THREAD

**Issue by ssrlive** [ivmai/bdwgc#302]
See image

I think you forget to release `GC_malloc_heap_l` global object.

![image](https://user-images.githubusercontent.com/30760636/71986783-fdd77e80-3267-11ea-8167-91e9e57d0e7e.png)

**Comment by ivmai** [comment]
It is not safe to free GC_malloc_heap_l elements because the heap might be used by other running threads of the client application.

**Comment by ssrlive** [comment]
I think that exiting all child threads before the end of the main thread is the basic quality of writing a program.
It is the programmer's responsibility to exit the child thread.
So, please provide at least a function that releases GC_malloc_heap_l, which is convenient for users to call it. likes:
```
void fnExit1 (void)
{
  release_GC_malloc_heap_l();
  ...
}

int main ()
{
  atexit (fnExit1);
  ...
  return 0;
}
```

**Comment by ivmai** [comment]
> I think that exiting all child threads before the end of the main thread is the basic quality of writing a program.
> It is the programmer's responsibility to exit the child thread.

I can't agree. At least, BDWGC does not terminate marker threads.
But, anyway, we could add freeing of GC_malloc_heap_l to GC_win32_free_heap. OK?
BTW, why do you need to free it? To be sure no memory leak is detected, right?

**Comment by ssrlive** [comment]
Yes.  I cannot tolerate memory leaking in a C program.  If so, the rest of
the program is also untrustworthy.

**Comment by ivmai** [comment]
Is commit 5551f9a OK for you?

**Comment by ssrlive** [comment]
ok it's fine
