### ISSUE TITLE
Provide more aggressive heap scaling parameters

### ISSUE THREAD

**Issue by hanwen** [ivmai/bdwgc#304]
Hi!

I work on LilyPond, which uses the GUILE Scheme library. As of v2.0 of GUILE, it uses BDWGC.

This has unfortunately caused a performance regression. LilyPond is a compiler-style typesetter, and in some phases, it builds up large, live datastructures.  In these construction phases, we continually allocate new memory, which triggers GC, but GC can then only reclaim 20% of the heap.

This causes GC costs to balloon by 5x, compard to the pre-BDWGC version.

I have already tuned the GC_free_space_divisor to 1.

I can tune the initial heap size to match the cost of program initialization (which helps), but beyond that, I want the heap to grow more aggressively. 

Is there a tuning mechanism I have overlooked, and if not, could one be added? Maybe a GC_free_space_numerator?

In absense of API enhancements, is there something I could do to make the heap grow faster? 
Could I call something like this from a GC hook?

grow_heap() {
  long current_heap_size = ...
  GC_FREE(GC_MALLOC(current_heap_size / 2));
}

**Comment by hanwen** [comment]
(when I say GC cost, I mean wall clock runtime)

**Comment by ivmai** [comment]
>  is there something I could do to make the heap grow faster?

GC_expand_hp

> but GC can then only reclaim 20% of the heap.

Do you mean old GC could was able to reclaim much more than 20%?
In this case, it is better to investigate why particular memory is not reclaimed.

> Is there a tuning mechanism I have overlooked, and if not, could one be added? Maybe a GC_free_space_numerator?

I'm ready to accept new API if needed.

I think min_bytes_allocd() needs tuning for your case. E.g.
    result = scan_size / GC_free_space_divisor;
->
    result = scan_size * GC_free_space_multiplier / GC_free_space_divisor;

**Comment by hanwen** [comment]
On Fri, Jan 31, 2020 at 2:55 PM Ivan Maidanski <notifications@github.com>
wrote:

> is there something I could do to make the heap grow faster?
>
> GC_expand_hp
>
> but GC can then only reclaim 20% of the heap.
>
> Do you mean old GC could was able to reclaim much more than 20%?
>

No, I mean that the old GC could be tuned to increase heap size more quickly

Thanks for the pointer on GC_expand_hp; I'll see if I can use that in a
kludge. For deployment, it's easier if we don't require installing the
latest version of dependencies.

-- 
Han-Wen Nienhuys - hanwenn@gmail.com - http://www.xs4all.nl/~hanwen

**Comment by hanwen** [comment]
I tried building something that calls GC_expand_heap(), but I failed. I want to size the heap such that after full GC, about 50% of the heap is in use, as this leads to reasonable runtimes ( [benchmarks](https://lists.gnu.org/archive/html/lilypond-devel/2020-02/msg00448.html).

I tried hooking into the GC events callback, but it turns out that I can't get at the amount of memory in use from the statistics. Here is an example dump.

```
GC #7 freed 32163424 bytes, heap 74944 KiB
World-stopped marking took 95 msecs (24 in average)
In-use heap: 54% (37084 KiB pointers + 3850 KiB other)
65128 finalization entries; 88121/0 short/long disappearing links alive
38836 finalization-ready objects; 16815/0 short/long links cleared
Finalize plus initiate sweep took 22 + 0 msecs
Complete collection took 121 msecs
unmapped sz 0M           /* prof stats */
free sz 8M
heap sz 73M
reclaimed after 8M
non gc 0M
alloced 0M
alloced before 229M
```
Somehow, I'd like to get the information that 30M was freed, or that 40M is still in use, but it looks like GC_get_prof_stats won't tell me what is going on.

Do you have a suggestion on how to do that?

**Comment by hanwen** [comment]
One of our contributors dug deeper and found the root cause.

We are using "Smobs" (a FFI in GUILE Scheme for C structs), and we need to call STL destructors to clean them up properly.  This is achieved with "smob_free" callbacks, which are essentially GC finalizers.

BDWGC assumes here

  https://github.com/ivmai/bdwgc/blob/v8.0.4/alloc.c#L1435

that if there are more than 500 finalizers to call, it's not worth trying to expand the heap. Since all of our objects have finalizers, this is often not the right choice. Removing that condition fixes our performance problem. 

Perhaps you could consider making this threshold scale with the total number of objects that have finalizers?

In any event, we managed to solve our immediate problem by taking the number of smobs as a proxy for the set of live objects, and expand the heap based on that number.

**Comment by ivmai** [comment]
> BDWGC assumes here
> https://github.com/ivmai/bdwgc/blob/v8.0.4/alloc.c#L1435
> that if there are more than 500 finalizers to call, it's not worth trying to expand the heap. Since all of our objects have finalizers, this is often not the right choice. Removing that condition fixes our performance problem.
> Perhaps you could consider making this threshold scale with the total number of objects that have finalizers?

I see. I'm fine to make it more flexible. Do you mean to make the condition like?
GC_fo_entries > last_fo_entries + GC_bytes_allocd / <tunable_value>
What's tunable_value OK for you?

Alternatively, you could make some draft commit.

**Comment by hanwen** [comment]
i'll try (I'm a little intimidated by the GC source code :-)

**Comment by ivmai** [comment]
The above commit should solve this issue.
E.g. GC_set_allocd_bytes_per_finalizer(0) should be as-if GC_fo_entries > (last_fo_entries + 500) is removed.
