### ISSUE TITLE
Improved method to find main stack bottom on HP-UX

### ISSUE THREAD

**Issue by danglin44** [ivmai/bdwgc#308]
Hi Ivan,

In trying to debug issues with guile, I found that the faults generated by HEURISTIC2 interfere with debugging.  In thinking about this, I noticed the technique used to find the register stack bottom on ia64 HP-UX.  I did some investigation and found that the same technique can be used to find the main stack bottom on HP-UX.  It is identified by the pst_type, PS_STACK.

The attached change implements this approach.

The pstat_getprocvm() call also provides the length of each vm region.  I wondered about checking whether GC_approx_sp() is in the region but I think there can only be one main stack region.

Regards,
Dave

[hpux-main-stackbottom.patch.txt](https://github.com/ivmai/bdwgc/files/4334432/hpux-main-stackbottom.patch.txt)

**Comment by ivmai** [comment]
> The attached change implements this approach.

Thank you, I will review in a week or so.

> The pstat_getprocvm() call also provides the length of each vm region. I wondered about checking whether GC_approx_sp() is in the region but I think there can only be one main stack region.

I see. I have no opinion about this approach.

**Comment by hboehm** [comment]
I looked at it quickly. I'm no longer an expert and can't test, but it
looks fine to me.  I'm not sure performance is great in all cases, since
there may presumably be a lot of mappings. But we should only take that hit
once.

**Comment by danglin44** [comment]
On 2020-03-19 1:23 p.m., Hans Boehm wrote:
> I looked at it quickly. I'm no longer an expert and can't test, but it
> looks fine to me. I'm not sure performance is great in all cases, since
> there may presumably be a lot of mappings. But we should only take that hit
> once.
In a typical application, there aren't many mappings.  Here is a dump for guile 3.0
which uses bdwgc:

-bash-4.4$ vm_status -v 25379
VIRT/PHYS/LOCKED/SWAP summaries in pages.
System page size is 4096 or 0x1000 bytes.
Object 1:  TEXT  at VA 0x1000 to VA 0x3fff.
                VIRT: 576460886919004224        PHYS: 0         LOCKED: 0
Object 2:  DATA/HEAP  at VA 0x40001000 to VA 0x40007fff.
                VIRT: 576460886919004224        PHYS: 0         LOCKED: 0
Object 3:  MMAP  at VA 0x7b02e000 to VA 0x7b02ffff.
                VIRT: 576460886919004224        PHYS: 0         LOCKED: 0
Object 4:  MMAP  at VA 0x7b030000 to VA 0x7b033fff.
                VIRT: 576460886919004224        PHYS: 0         LOCKED: 0
Object 5:  MMAP  at VA 0x7b034000 to VA 0x7b034fff.
                VIRT: 576460886919004224        PHYS: 0         LOCKED: 0
Object 6:  MMAP  at VA 0x7b035000 to VA 0x7b038fff.
                VIRT: 576460886919004224        PHYS: 0         LOCKED: 0
Object 7:  MMAP  at VA 0x7b039000 to VA 0x7b040fff.
                VIRT: 576460886919004224        PHYS: 0         LOCKED: 0
Object 8:  MMAP  at VA 0x7b041000 to VA 0x7b04bfff.
                VIRT: 576460886919004224        PHYS: 0         LOCKED: 0
Object 9:  MMAP  at VA 0x7b04c000 to VA 0x7b04cfff.
                VIRT: 576460886919004224        PHYS: 0         LOCKED: 0
Object 10:  MMAP  at VA 0x7b04d000 to VA 0x7b04efff.
                VIRT: 576460886919004224        PHYS: 0         LOCKED: 0
Object 11:  MMAP  at VA 0x7b04f000 to VA 0x7b053fff.
                VIRT: 576460886919004224        PHYS: 0         LOCKED: 0
Object 12:  MAIN STACK  at VA 0x7eff0000 to VA 0x7eff7fff.
                VIRT: 576460886919004224        PHYS: 0         LOCKED: 0
Object 13:  MMAP  at VA 0xc0004000 to VA 0xc0004fff.
                VIRT: 576460886919004224        PHYS: 0         LOCKED: 0
Object 14:  MMAP  at VA 0xc0005000 to VA 0xc0007fff.
                VIRT: 576460886919004224        PHYS: 0         LOCKED: 0
Object 15:  MMAP  at VA 0xc0010000 to VA 0xc0044fff.
                VIRT: 576460886919004224        PHYS: 0         LOCKED: 0
Object 16:  MMAP  at VA 0xc0100000 to VA 0xc024bfff.
                VIRT: 576460886919004224        PHYS: 0         LOCKED: 0
PID 0:
 UNUSED TYPE  consumes 0 VIRT, 0 PHYS, and 0 LOCKED
 UAREA  consumes 0 VIRT, 0 PHYS, and 0 LOCKED
 TEXT  consumes 3 VIRT, 3 PHYS, and 0 LOCKED
 DATA/HEAP  consumes 7 VIRT, 6 PHYS, and 0 LOCKED
 MAIN STACK  consumes 8 VIRT, 8 PHYS, and 0 LOCKED
 SYSV SHMEM  consumes 0 VIRT, 0 PHYS, and 0 LOCKED
 NULL DEREF  consumes 0 VIRT, 0 PHYS, and 0 LOCKED
 MEM MAPPED I/O  consumes 0 VIRT, 0 PHYS, and 0 LOCKED
 MMAP  consumes 427 VIRT, 355 PHYS, and 0 LOCKED
 GRAPHICS SPECIFIC  consumes 0 VIRT, 0 PHYS, and 0 LOCKED
 GRAPHICS SPECIFIC  consumes 0 VIRT, 0 PHYS, and 0 LOCKED

Dave

-- 
John David Anglin  dave.anglin@bell.net

**Comment by ivmai** [comment]
Looks good. I will do a bit of refactoring and push to master next week.

**Comment by ivmai** [comment]
> pstat_getprocvm(&vm_status, sizeof(vm_status), 0, i++)

Why is elem_count zero?

**Comment by danglin44** [comment]
On 2020-04-13 4:57 a.m., Ivan Maidanski wrote:
>
>     pstat_getprocvm(&vm_status, sizeof(vm_status), 0, i++)
>
> Why is elem_count zero?
>
This is what the man page for pstat(2) says:

The elemcount parameter identifies the process for which address space information is to be returned.
An elemcount parameter of zero indicates that address space information for the currently executing
process should be returned.

-- 
John David Anglin  dave.anglin@bell.net
