### ISSUE TITLE
"mmap(PROT_NONE) failed" compiling Guile 2.2.7 on Haiku

### ISSUE THREAD

**Issue by mgubi** [ivmai/bdwgc#311]
While compiling GNU Guile 2.2.7 on Haiku (www.haiku-os.org) the following error is encountered
```
mmap(PROT_NONE) failed
```
with the version 0.8.4 of the GC from Haikuports: 
(https://github.com/haikuports/haikuports/tree/master/dev-libs/boehm_gc)

I found that adding `|| defined (__HAIKU__)` at the end of line 2578 of

https://github.com/ivmai/bdwgc/blob/master/os_dep.c

seems to correct the problem.

**Comment by mgubi** [comment]
I have submitted a PR to Haikuports to correct the issue. However I would like you to comment if the workaround is sound or not.

**Comment by ivmai** [comment]
PR ofg @mgubi  in Haiku: https://github.com/haikuports/haikuports/commit/485182977332463c87bc301ed83f92505e7edf3c

**Comment by ivmai** [comment]
Yes, seems to be OK, I will cherry-pick your commit to upstream master

**Comment by ivmai** [comment]
However, it might signal some issue in Haiku itselft, I don't know though.

**Comment by mgubi** [comment]
Unfortunately I'm not knowledgable enough to understand precisely what is going on. I could ask to Haiku developers to look on it a moment. It would be good to have some extensive testing for the GC to use to check. At the moment and as far as I know the only software in Haiku using Boehm GC is Guile.

**Comment by mgubi** [comment]
I've posted in Haiku forum to ask an opinion.

**Comment by ivmai** [comment]
I've pushed your fix to bdwgc master. Thank you

**Comment by ivmai** [comment]
Modified a bit. Please test on Haiku.

**Comment by ivmai** [comment]
Hello @mgubi,
I have a question whether memory unmapping really happens with this fix.
Could you please make a small experiment on Haiku target?
1. checkout bdwgc d3c9003
2. modify tests/test.c by adding an infinitely loop ( for(;;){} ) to the end of file (before "return(0);")
3. compile bdwgc as usual, build gctest (make gctest)
4. run ./gctest - it will print summary and hang
5. run top and get VIRT and RES values for gctest process
6. if RES is much smaller than VIRT, then unmapping really happens
