### ISSUE TITLE
CMake fails to find Threads on 64bit macOS Catalina

### ISSUE THREAD

**Issue by mahrud** [ivmai/bdwgc#319]
I traced the problem to the following cached variable:
https://github.com/ivmai/bdwgc/blob/98ac50b6311219b8f57a794deb9a72d2a25b23ce/CMakeLists.txt#L72-L75
This line causes cmake to add `-arch x86_64 -arch i386` to the flags for checking whether pthread is usable, which then leads to the following linker error:
```
ld: dynamic main executables must link with libSystem.dylib for architecture i386
```
TARGET is `x86_64-unknown-darwin-19.3.0` (macOS 10.15.3) and compiler is AppleClang 11.

Removing that section, or setting the variable to x86_64 solves the issue.

**Comment by ivmai** [comment]
Related issue #275

**Comment by ivmai** [comment]
I think I will change it to x86_64

**Comment by ivmai** [comment]
> Removing that section, or setting the variable to x86_64 solves the issue.

I've removed it finally.
