### ISSUE TITLE
Parallel mark seems to make programs slower on machines with more cores

### ISSUE THREAD

**Issue by CaviarChen** [ivmai/bdwgc#320]
Hi, 
I work on a project called wybe which uses bdwgc. Recently, I noticed a performance issue and I believe it's related to bdwgc(https://github.com/pschachte/wybe/issues/59). 
We use bdwgc in a sample way. Only `GC_init`, `GC_malloc`, `GC_malloc_atomic`, and `GC_realloc` are used and the program is single-threaded. The problem is that it runs a lot slower when there are more cores available (eg. 54s on a 1-core machine and 220s on a 12-core machine). We didn't build bdwgc by ourselves. We installed it using package managers such as `homebrew` and `apt`.

The problem can be mitigated by using `export GC_NPROCS=1`.

So my questions are:
Is this an expected behavior?
If so, what are the approaches that can avoid this behavior other than using `export GC_NPROCS=1` or build a custom version of bdwgc?

**Comment by ivmai** [comment]
> eg. 54s on a 1-core machine and 220s on a 12-core machine
> The problem can be mitigated by using export GC_NPROCS=1.

Could you please check the performance with various values of GC_MARKERS
export GC_MARKERS=1
export GC_MARKERS=2
export GC_MARKERS=4
...

**Comment by ivmai** [comment]
> build a custom version of bdwgc?
configure --disable-parallel-marker
or
cmake -Denable_parallel_marker=OFF

**Comment by CaviarChen** [comment]
> > eg. 54s on a 1-core machine and 220s on a 12-core machine
> > The problem can be mitigated by using export GC_NPROCS=1.
> 
> Could you please check the performance with various values of GC_MARKERS
> export GC_MARKERS=1
> export GC_MARKERS=2
> export GC_MARKERS=4
> ...

I used a simple c program to reproduce this so we can forget about wybe.
```
#include <stdio.h>
#include <stdlib.h>
#include <gc.h>


int main(int argc, char *argv[]) {
    GC_init();
    int *mem = (int*)GC_MALLOC(10 * sizeof(int));
    for (int i = 0; i < 10; i++) {
        mem[i] = i;
    }

    for (int r = 0; r < 100000000; r++) {
        int *memt = (int*)GC_MALLOC(10 * sizeof(int));
        for (int i = 0; i < 10; i++) {
            memt[i] = mem[i] + 1;
        }
        mem = memt;
    }
    
    for (int i = 0; i < 10; i++) {
        printf("%d ", mem[i]);
    }
    printf("\n");
    return 0;
}
```

The results are:
```
$ time GC_NPROCS=1 ./a.out 
100000000 100000001 100000002 100000003 100000004 100000005 100000006 100000007 100000008 100000009 

real    0m3.487s
user    0m3.485s
sys     0m0.002s
$ time GC_NPROCS=2 ./a.out 
100000000 100000001 100000002 100000003 100000004 100000005 100000006 100000007 100000008 100000009 

real    0m4.009s
user    0m0.312s
sys     0m3.922s
$ time GC_NPROCS=4 ./a.out 
100000000 100000001 100000002 100000003 100000004 100000005 100000006 100000007 100000008 100000009 

real    0m7.790s
user    0m0.285s
sys     0m8.891s
$ time GC_NPROCS=8 ./a.out 
100000000 100000001 100000002 100000003 100000004 100000005 100000006 100000007 100000008 100000009 

real    0m16.059s
user    0m0.509s
sys     0m30.571s
$ time GC_MARKERS=1 ./a.out 
100000000 100000001 100000002 100000003 100000004 100000005 100000006 100000007 100000008 100000009 

real    0m3.493s
user    0m3.484s
sys     0m0.009s
$ time GC_MARKERS=2 ./a.out 
100000000 100000001 100000002 100000003 100000004 100000005 100000006 100000007 100000008 100000009 

real    0m4.007s
user    0m0.270s
sys     0m3.960s
$ time GC_MARKERS=4 ./a.out 
100000000 100000001 100000002 100000003 100000004 100000005 100000006 100000007 100000008 100000009 

real    0m7.719s
user    0m0.377s
sys     0m8.640s
$ time GC_MARKERS=8 ./a.out 
100000000 100000001 100000002 100000003 100000004 100000005 100000006 100000007 100000008 100000009 

real    0m15.316s
user    0m0.542s
sys     0m31.350s
```

Is there any API I can use to set "GC_MARKERS" and "GC_NPROCS"?
Also I found [this page](https://www.hboehm.info/gc/faq.html) mentioned something about using `gc_local_alloc.h` but I can't find it.

Thanks a lot.

**Comment by ivmai** [comment]
> Is there any API I can use to set "GC_MARKERS" and "GC_NPROCS"?

No way currently. But you can disable the parallel marking at runtime by GC_set_time_limit(<some big value, e.g. 10000>) if you call it before GC initialization. (Please try if it works for your bdwgc version)

**Comment by ivmai** [comment]
> time GC_MARKERS=8 ./a.out 
> 100000000 100000001 100000002 100000003 100000004 100000005 100000006 100000007 100000008 100000009 
>
> real    0m15.316s
> user    0m0.542s
> sys     0m31.350s

Definitely, it should be investigate why parallel marker leads to big performance degradation.

**Comment by CaviarChen** [comment]
> > Is there any API I can use to set "GC_MARKERS" and "GC_NPROCS"?
> 
> No way currently. But you can disable the parallel marking at runtime by GC_set_time_limit(<some big value, e.g. 10000>) if you call it before GC initialization. (Please try if it works for your bdwgc version)

Thanks! My current workaround is using `setenv("GC_MARKERS", "1", false);`.
`GC_set_time_limit(GC_TIME_UNLIMITED)` doesn't seem to work for the version I'm using.

Sorry that I am not familiar this project and couldn't be helpful. But I do notice something interesting.
```
$ time GC_MARKERS=8  taskset -c 0 ./a.out 
100000000 100000001 100000002 100000003 100000004 100000005 100000006 100000007 100000008 100000009 

real    0m6.031s
user    0m4.326s
sys     0m1.705s
```
Forcing all threads to running on a single core makes it run a bit faster (I thought the other way around since there are still 7 marking thread).

**Comment by hboehm** [comment]
The problem here may be that the test program only has one object live at a
time, and a small root set, so in the single-threaded-marker case, it runs
with a very small heap and very cheap collections. With multiple markers,
the heap may still be tiny, but we now have all the synchronization
overhead required to coordinate a larger number of threads. There may not
be enough work to do for all those markers to do anything useful. Perhaps a
tiny heap should decrease the number of marker threads?

In any case, I wouldn't assume that performance on this benchmark is
indicative of a real application.

**Comment by CaviarChen** [comment]
Thanks for the explanation. I totally agree that the code I provide is an extreme case. We use bdwgc in the runtime of a programming language called Wybe and all data structures in it are immutable. Thus it's not too rare for a program to create tons of objects with a relatively small heap.

My idea might be pretty naive. I feel that there could be some approaches other than making the default number of markers equal to the number of cores, especially recent machines usually have quite a lot of cores. Maybe having some API that can adjust the number of markers in runtime so I can change it when users create more threads or the heap becomes larger.

**Comment by ivmai** [comment]
> GC_set_time_limit(GC_TIME_UNLIMITED) doesn't seem to work for the version I'm using.

This won't work on any version, try some big value but not GC_TIME_UNLIMITED.

> Forcing all threads to running on a single core makes it run a bit faster.

Definitely we don't want to run more than 1 marker thread on CPU core. (That's the idea of the parallel marker - if you have many core then you could distribute the marker work across the cores.)

> the default number of markers equal to the number of cores, especially recent machines usually have quite a lot of cores

The number of markers is limited by MAX_MARKERS, currently 16. Probably it is not optimal.

We could add the API to limit the number of cores at GC init.

> Perhaps a tiny heap should decrease the number of marker threads?

We could avoid unfreeze of some amount of markers during GC if the size of allocated objects is small. Measurements should be done with various heap sizes to implement this heuristic.

**Comment by ivmai** [comment]
I've added GC_set_markers_count API function to adjust number of markers at GC initialization - see ee900ca.
The task of changing amount of markers dynamically depending on the heap size is moved to #328 .
