### ISSUE TITLE
Unmapping creates many memory map areas

### ISSUE THREAD

**Issue by wangp** [ivmai/bdwgc#324]
I've encountered a problem where enabling munmap support can result in a profusion of memory map areas. When the number of areas exceeds `vm.max_map_count` on Linux (by default 65536) then the `mmap` call in `GC_unmap` fails with ENOMEM and the process aborts:
```c
          void * result = mmap(start_addr, len, PROT_NONE,
                               MAP_PRIVATE | MAP_FIXED | OPT_MAP_ANON,
                               zero_fd, 0/* offset */);

          if (result != (void *)start_addr)
            ABORT("mmap(PROT_NONE) failed");
```

Increasing `vm.max_map_count` avoids mmap() failing, and continuing to allocate normally does bring the number of memory map areas back down. However, I wonder if this is expected behaviour in the first place, or if there is an more robust solution available?

Originally I hit this problem by calling GC_gcollect_and_unmap() repeatedly, but that turns out not to be necessary. I will try to provide a test case once I reproduce it with a small C program.

A sample of a process map with too many map areas looks like this: (`pmap $pid |grep anon`)
```
0000000001817000  67212K rw---   [ anon ]
00007fff79847000  17676K rw---   [ anon ]
00007fff7a98a000      4K -----   [ anon ]
00007fff7a98b000      4K rw---   [ anon ]
00007fff7a98c000      4K -----   [ anon ]
00007fff7a98d000     12K rw---   [ anon ]
00007fff7a990000      4K -----   [ anon ]
00007fff7a991000      8K rw---   [ anon ]
00007fff7a993000      4K -----   [ anon ]
00007fff7a994000      8K rw---   [ anon ]
00007fff7a996000      4K -----   [ anon ]
00007fff7a997000     16K rw---   [ anon ]
00007fff7a99b000      4K -----   [ anon ]
00007fff7a99c000      4K rw---   [ anon ]
00007fff7a99d000      4K -----   [ anon ]
00007fff7a99e000     20K rw---   [ anon ]
00007fff7a9a3000      4K -----   [ anon ]
00007fff7a9a4000      4K rw---   [ anon ]
00007fff7a9a5000      4K -----   [ anon ]
00007fff7a9a6000     12K rw---   [ anon ]
00007fff7a9a9000      4K -----   [ anon ]
00007fff7a9aa000      8K rw---   [ anon ]
00007fff7a9ac000      4K -----   [ anon ]
00007fff7a9ad000     12K rw---   [ anon ]
00007fff7a9b0000      4K -----   [ anon ]
00007fff7a9b1000      8K rw---   [ anon ]
00007fff7a9b3000      4K -----   [ anon ]
00007fff7a9b4000      8K rw---   [ anon ]
00007fff7a9b6000      4K -----   [ anon ]
00007fff7a9b7000     12K rw---   [ anon ]
00007fff7a9ba000      4K -----   [ anon ]
00007fff7a9bb000     16K rw---   [ anon ]
00007fff7a9bf000      4K -----   [ anon ]
00007fff7a9c0000      8K rw---   [ anon ]
00007fff7a9c2000      4K -----   [ anon ]
00007fff7a9c3000      8K rw---   [ anon ]
00007fff7a9c5000      4K -----   [ anon ]
00007fff7a9c6000     12K rw---   [ anon ]
00007fff7a9c9000      4K -----   [ anon ]
00007fff7a9ca000      4K rw---   [ anon ]
00007fff7a9cb000      4K -----   [ anon ]
00007fff7a9cc000     16K rw---   [ anon ]
00007fff7a9d0000      4K -----   [ anon ]
00007fff7a9d1000      4K rw---   [ anon ]
00007fff7a9d2000      4K -----   [ anon ]
00007fff7a9d3000     16K rw---   [ anon ]
00007fff7a9d7000      4K -----   [ anon ]
00007fff7a9d8000      8K rw---   [ anon ]
00007fff7a9da000      4K -----   [ anon ]
00007fff7a9db000      4K rw---   [ anon ]
00007fff7a9dc000      4K -----   [ anon ]
00007fff7a9dd000     12K rw---   [ anon ]
00007fff7a9e0000      4K -----   [ anon ]
00007fff7a9e1000      8K rw---   [ anon ]
00007fff7a9e3000      4K -----   [ anon ]
00007fff7a9e4000     12K rw---   [ anon ]
00007fff7a9e7000      4K -----   [ anon ]
00007fff7a9e8000     12K rw---   [ anon ]
00007fff7a9eb000      4K -----   [ anon ]
00007fff7a9ec000      4K rw---   [ anon ]
00007fff7a9ed000      4K -----   [ anon ]
00007fff7a9ee000     12K rw---   [ anon ]
00007fff7a9f1000      4K -----   [ anon ]
00007fff7a9f2000     12K rw---   [ anon ]
00007fff7a9f5000      4K -----   [ anon ]
00007fff7a9f6000      8K rw---   [ anon ]
... etc ...
```

**Comment by wangp** [comment]
I can trigger the assertion failure reliably with this test program that calls `GC_gcollect_and_unmap`.
Linux 5.7.7 x86-64, 16 GB RAM, bdwgc master branch

[unmap_test.c.txt](https://github.com/ivmai/bdwgc/files/4970563/unmap_test.c.txt)

**Comment by ivmai** [comment]
I failed to reproduce the failure on my Linux host.

But I understand the issue - I think we could implement some algorithm to shrink number of unmapped regions if ENOMEM encountered or count and a void unmapping of more regions than some limit (or maybe implement some more complex algorithm to avoid unmapping of small regions if the number of regions is getting high).

**Comment by wangp** [comment]
Placing a limit on the number of unmapped regions sounds like a good place to start. Here is my first attempt:
https://github.com/wangp/bdwgc/tree/unmap-limit
I don't exactly know what I'm doing though, so any hints would be very welcome.

**Comment by ivmai** [comment]
OK, I will look at it within a week

**Comment by ivmai** [comment]
The idea looks good. Please go on. What's the typical maximum unmapped_regions value during gc tests?
I have posted small remarks about the code.

**Comment by wangp** [comment]
Sorry for the delay. I've  updated the branch with some more work.
On gctest, I'm seeing a maximum value of GC_num_unmapped_regions between 260 to 300.

**Comment by ivmai** [comment]
Review comments (stylistic ones):
* GC_get_block_ending_at, GC_next_block - delete these function (similar functions already exist, please add an argument to them)
* GC_num_unmapped_regions - it should be part of GC_arrays
* GC_calc_num_unmapped_regions - I think it should return delta value (i.e. don't access GC_num_unmapped_regions)
* GC_maintain_num_unmapped_regions - please declare as GC_INLINE

**Comment by ivmai** [comment]
Note that GC_UNMAPPED_REGIONS_SOFT_LIMIT is platform-specific (do we have any practical limit on Windows?).

**Comment by ivmai** [comment]
Probably, later, we could improve the algorithm to stop unmapping of small regions if we already have a lot of areas. E.g. if we have 1024 unmapped areas then we allow to unmap only 2+ pages in a row, if 2048 unmapped areas then allow only 4+ pages to be unmapped, and so on.

**Comment by ivmai** [comment]
One more remark about the code: GC_calc_num_unmapped_regions is called first by GC_unmap_old and then by GC_maintain_num_unmapped_regions - is it possible to avoid computation of unmapped regions twice?

**Comment by wangp** [comment]
> * GC_get_block_ending_at, GC_next_block - delete these function (similar functions already exist, please add an argument to them)

I made GC_next_used_block call GC_next_block, where GC_next_block takes a boolean flag. I don't think the flag is very clear but there is only one place where GC_next_block is called directly.

I have made GC_free_block_ending_at call GC_get_block_ending_at, then impose the additional constraint that the block is free.

> * GC_num_unmapped_regions - it should be part of GC_arrays

Done.

> * GC_calc_num_unmapped_regions - I think it should return delta value (i.e. don't access GC_num_unmapped_regions)

Done.

> * GC_maintain_num_unmapped_regions - please declare as GC_INLINE

Done.

**Comment by wangp** [comment]
> One more remark about the code: GC_calc_num_unmapped_regions is called first by GC_unmap_old and then by GC_maintain_num_unmapped_regions - is it possible to avoid computation of unmapped regions twice?

I don't think there is any redundant computation.
GC_unmap_old is called by GC_finish_collection.
Whereas GC_maintain_num_unmapped_regions is called during allocation by
- GC_alloc_large -> GC_merge_unmapped -> GC_maintain_num_unmapped_regions
- GC_allochblk_nth -> GC_maintain_num_unmapped_regions

**Comment by wangp** [comment]
> Note that GC_UNMAPPED_REGIONS_SOFT_LIMIT is platform-specific (do we have any practical limit on Windows?).

Looking around:
- FreeBSD used to have a `vm.max_proc_mmap` knob but it seems the restriction was lifted in FreeBSD 9
- DragonFly BSD still has `vm.max_proc_mmap`, according to its mmap(2) man page
- OpenBSD does not describe a limit in its man page
- NetBSD does not describe a limit in its man page

See also the top of https://golang.org/src/cmd/internal/bio/buf_mmap.go

I cannot find any reference to a similar limit on Windows.

The behaviour of merging unmapped regions is likely specific to Linux. Therefore I have made the unmapped region counting and limit specific to Linux only. It could be enabled on DragonFly BSD if required.

**Comment by ivmai** [comment]
Yes, I have continued to look at your code today.

**Comment by ivmai** [comment]
I've finally finished review and polished the code - please test (commit 9245e11)

**Comment by wangp** [comment]
Thank you, it looks good.

**Comment by ivmai** [comment]
Good. I've also enabled it for DragonFly.

**Comment by ivmai** [comment]
> Placing a limit on the number of unmapped regions sounds like a good place to start

BTW. @wangp, after commit 85886f39 do we still need the fix proposed in this issue?

**Comment by wangp** [comment]
It should not be needed I think. With the test program I posted above, there is just one large rw memory map area. Here is a sample of the `pmap -x` output:
```
Address           Kbytes     RSS   Dirty Mode  Mapping
00005607bf3ee000       8       8       0 r---- unmap_test.85886f39
00005607bf3f0000     100     100       0 r-x-- unmap_test.85886f39
00005607bf409000      40      40       0 r---- unmap_test.85886f39
00005607bf413000       4       4       4 r---- unmap_test.85886f39
00005607bf414000       4       4       4 rw--- unmap_test.85886f39
00005607bf415000     248      56      56 rw---   [ anon ]
00005607c08b3000     132       8       8 rw---   [ anon ]
00007fd45b348000 3788400 2742852 2742852 rw---   [ anon ]
00007fd5426e4000       4       0       0 -----   [ anon ]
00007fd5426e5000    8192      12      12 rw---   [ anon ]
00007fd542ee5000       4       0       0 -----   [ anon ]
00007fd542ee6000    8192      12      12 rw---   [ anon ]
00007fd5436e6000       4       0       0 -----   [ anon ]
00007fd5436e7000    8192      12      12 rw---   [ anon ]
00007fd543ee7000       4       0       0 -----   [ anon ]
00007fd543ee8000    8192      12      12 rw---   [ anon ]
00007fd5446e8000       4       0       0 -----   [ anon ]
00007fd5446e9000    8192      16      16 rw---   [ anon ]
00007fd544ee9000       4       0       0 -----   [ anon ]
00007fd544eea000    8192      12      12 rw---   [ anon ]
00007fd5456ea000       4       0       0 -----   [ anon ]
00007fd5456eb000    8396     188     188 rw---   [ anon ]
00007fd545f1e000     152     148       0 r---- libc-2.32.so
00007fd545f44000    1320     920       0 r-x-- libc-2.32.so
00007fd54608e000     304     136       0 r---- libc-2.32.so
00007fd5460da000      12      12      12 r---- libc-2.32.so
00007fd5460dd000      12      12      12 rw--- libc-2.32.so
00007fd5460e0000      16       8       8 rw---   [ anon ]
00007fd5460e4000      28      28       0 r---- libpthread-2.32.so
00007fd5460eb000      60      60       0 r-x-- libpthread-2.32.so
00007fd5460fa000      20      20       0 r---- libpthread-2.32.so
00007fd5460ff000       4       4       4 r---- libpthread-2.32.so
00007fd546100000       4       4       4 rw--- libpthread-2.32.so
00007fd546101000      24      12      12 rw---   [ anon ]
00007fd546111000      64      44      44 rw---   [ anon ]
00007fd546121000       4       4       0 r---- ld-2.32.so
00007fd546122000     128     128       0 r-x-- ld-2.32.so
00007fd546142000      32      32       0 r---- ld-2.32.so
00007fd54614b000       4       4       4 r---- ld-2.32.so
00007fd54614c000       8       8       8 rw--- ld-2.32.so
00007ffda278d000     136      32      32 rw---   [ stack ]
00007ffda27e8000      16       0       0 r----   [ anon ]
00007ffda27ec000       8       4       0 r-x--   [ anon ]
ffffffffff600000       4       0       0 r-x--   [ anon ]
```

**Comment by ivmai** [comment]
> It should not be needed I think.

I think the same. (madvise(NOTNEEDED) should be related in kernel only to phys addr not protection bits.)

Committed as 1991159ec
