### ISSUE TITLE
Compiler TLS not used on BSD platforms

### ISSUE THREAD

**Issue by myfreeweb** [ivmai/bdwgc#325]
When debugging an unrelated issue (also involving `pthread_getspecific`) in a consumer of bdwgc, I've discovered that bdwgc uses `pthread_getspecific` instead of real TLS on FreeBSD!

https://github.com/ivmai/bdwgc/blob/802e47d5e8dcbddd2e80cd4587eacc5f4ffbc745/include/private/thread_local_alloc.h#L55-L68

That's not good, there's no reason not to `USE_COMPILER_TLS` on any `FREEBSD`, and probably all the other BSDs too.

**Comment by ivmai** [comment]
Does the following change solve the issue?

        || (defined(FREEBSD) && defined(__GLIBC__) /* kFreeBSD */ \
->
        || (defined(FREEBSD) \

**Comment by ivmai** [comment]
> and probably all the other BSDs too.

Yes, probably, I think it is worth to enable it for OpenBSD and NetBSD as well (and fix the bugs later if any)

**Comment by myfreeweb** [comment]
Well, if `GC_GNUC_PREREQ(4, 4)` is true on clang, this would be enough..

**Comment by ivmai** [comment]
> Well, if GC_GNUC_PREREQ(4, 4) is true on clang, this would be enough..

Please check it with the version of compiler that you use.

**Comment by myfreeweb** [comment]
No, turns out clang 10 reports itself as gcc 4.2. We do need `|| defined(__clang__)` (or just drop that conditional, who's going to use a compiler that doesn't support TLS??)

**Comment by ivmai** [comment]
NetBSD supports TLS starting from 6.0 (from https://www.linux.org.ru/tag/netbsd?section=1), I see more dated messages with complains about TLS on NetBSD. So, I think we could enable TLS for NetBSD 6.0+.
