### ISSUE TITLE
Undefined reference to GC_dlopen()

### ISSUE THREAD

**Issue by mahge** [ivmai/bdwgc#335]
Environment : WSL - Ubuntu 18.04

Steps to reproduce:
- Compile static version of _gc_ with the **CMake** configuration.
- Include gc.h in another source and compile.

Probable cause:
- Missing `gc_dlopen.c` source in the CMakeLists `SRC `variable.
  https://github.com/ivmai/bdwgc/blob/57b97be07c514fcc4b608b13768fd2bf637a5899/CMakeLists.txt#L99-L102

Issue does not happen for shared library builds because the `SRC `variable is overridden to the combined source variable _extra/gc.c_

https://github.com/ivmai/bdwgc/blob/57b97be07c514fcc4b608b13768fd2bf637a5899/CMakeLists.txt#L291

---
Related PR #336

**Comment by ivmai** [comment]
Solved in #336
