### ISSUE TITLE
Unable to configure custom flags when building the GC

### ISSUE THREAD

**Issue by CaspianA1** [ivmai/bdwgc#339]
I want to trace where I am allocating memory, and for this I wish to use the `GC_PRINT_VERBOSE_STATS` flag. Unfortunately, I do not know how to enable it. I ran `./configure --help` to see if there was any information on enabling this option but I could not find out how. Could someone who has enabled this flag before let me know how they did it?

Here is my process that I used to build the GC. I am on macOS if that helps.

```sh
version="gc-8.0.4"
cd lib/GC
tar xvfz "${version}.tar.gz"
cd $version
./configure --prefix=/usr/local/bin --disable-threads
make
make check
make install
```

**Comment by CaspianA1** [comment]
Note: I tried adding `-enable-FEATURE=GC_PRINT_VERBOSE_STATS` to `./configure` above but it didn't do anything.

**Comment by ivmai** [comment]
Way 1: CFLAGS_EXTRA="-DGC_PRINT_VERBOSE_STATS" ./configure && make
Way 2: ./configure && make CFLAGS_EXTRA="-DGC_PRINT_VERBOSE_STATS"
