### ISSUE TITLE
Why does make check fail for i586 and x32 ABI if stack size is limited?

### ISSUE THREAD

**Issue by svenha** [ivmai/bdwgc#342]
`make check` shows 5 failures when compiling for i586 or x32 ABI on a 64bit machine (Ubuntu 20.10 and older). If I issue

    ulimit -S -s unlimited

all tests pass. I have seen such behavior in many contexts, but could never find a plausible explanation.

**Comment by svenha** [comment]
Some more details. The following 5 tests fail (looks like a common error reason):

    disclaim_test (in log: Failed to create thread #2: Resource temporarily unavailable)
    disclaim_weakmap_test (in log: Failed to create thread #2: Resource temporarily unavailable)
    gctest (in log: thread 2 creation failed 11)
    subthreadcreate_test.log (in log: Thread #1 creation failed)
    threadleaktest.log (in log: Thread creation failed 11)

**Comment by ivmai** [comment]
Got it. Looks like a limitation of the OS level. The potential fix could be checking of errno after pthread create, issue a warning and skip further calls of pthread create.

**Comment by ivmai** [comment]
At the same time, it is quite strange the OS does not allow to create a thread if stack is limited. Could you please try as simple code creating threads in a loop (w/o bdwgc)?

**Comment by ivmai** [comment]
> At the same time, it is quite strange the OS does not allow to create a thread if stack is limited. Could you please try as simple code creating threads in a loop (w/o bdwgc)?

E.g. try to run this code:

```
#include <stdio.h>
#include <string.h>
#include <pthread.h>

#define NTHREADS 100

void *test(void *arg) {
  if (!arg) for (;;) {}
  return arg;
}

int main(void) {
  int i;
  for (i = 0; i < NTHREADS; ++i) {
    pthread_t t;
    int err = pthread_create(&t, 0, test, 0);
    if (err != 0) {
      fprintf(stderr, "Thread #%d creation failed: %s\n",
              i, strerror(err));
      return 1;
    }
  }
  printf("Threads created: %d\n", i);
  return 0;
}
```

**Comment by ivmai** [comment]
https://man7.org/linux/man-pages/man3/pthread_create.3.html says:
```
       EAGAIN Insufficient resources to create another thread.

       EAGAIN A system-imposed limit on the number of threads was
              encountered.  There are a number of limits that may
              trigger this error: the RLIMIT_NPROC soft resource limit
              (set via setrlimit(2)), which limits the number of
              processes and threads for a real user ID, was reached; the
              kernel's system-wide limit on the number of processes and
              threads, /proc/sys/kernel/threads-max, was reached (see
              proc(5)); or the maximum number of PIDs,
              /proc/sys/kernel/pid_max, was reached (see proc(5)).
```

**Comment by ivmai** [comment]
I've reproduced it with NTHREADS=1000 on Ubuntu 20/x86_64:
$ clang -m32 -O3 t.c -lpthread && ./a.out
Thread #510 creation failed: Resource temporarily unavailable

**Comment by svenha** [comment]
@ivmai Thanks for the test program. The limit of 1000 is the same on my Ubuntu 21.04. If I use a moderate `ulimit -S -s` of 65536 the failing number of threads is 62.

How many threads do the mentioned bdwgc tests use?

**Comment by svenha** [comment]
If we know the number of needed threads, one could catch the error and recommend increasing the stack limit to a value (that we will find out soon :-) ).

**Comment by ivmai** [comment]
> disclaim_test (in log: Failed to create thread #2: Resource temporarily unavailable)

It failed after 2 threads were created.

**Comment by ivmai** [comment]
Please try latest master, failure should not happen any more.

**Comment by svenha** [comment]
I tested this version. The failures are gone for i586 and x32 ABI. Thanks!
