### ISSUE TITLE
Need version 5.0.2

### ISSUE THREAD

**Issue by blakemcbride** [ivmai/bdwgc#345]
Greetings,

Short version:

I have need for version 5.0.2 of the GC.  Can someone give me a copy of that?

Long version:

I am attempting to port an old 32-bit program to a modern 64-bit platform.  The system uses a modified version of GC 5.0.2.  I want to know what changes were made to 5.0.2 but I need the original source to diff them.  Once I get those diffs I can, hopefully, port them to a current GC.

I think the file may be named gc5.0alpha2.tar.gz

Thanks!

Blake McBride

**Comment by ivmai** [comment]
Sorry for a long delay. Here it is: https://github.com/ivmai/bdwgc/releases/tag/gc5_0alpha2
