### ISSUE TITLE
gctest sometimes hangs on Linux/arm64

### ISSUE THREAD

**Issue by bhaible** [ivmai/bdwgc#350]
On a Linux/arm64 machine (Linux 3.13.0, Ubuntu EGLIBC 2.19-0ubuntu6.15),
with the gc-8.0.4 package configured with defaults, the gctest hangs.

When I retry it, it works:

```
$ ./gctest 
Completed 6 tests
Allocated 11588886 collectable objects
Allocated 1224 uncollectable objects
Allocated 8220420 atomic objects
Reallocated 36 objects
Finalized 13075/13075 objects - finalization is probably ok
Total number of bytes allocated is 654829050
Total memory use by allocated blocks is 3145728 bytes
Final heap size is 806912 bytes
Final number of reachable objects is 4239
Completed 223 collections in 1693 msecs (using 8 marker threads)
Collector appears to work
```

**Comment by ivmai** [comment]
Is it reproducible with GC_RETRY_SIGNALS?
GC_RETRY_SIGNALS=1 ./gctest

**Comment by bhaible** [comment]
`GC_RETRY_SIGNALS=1` doesn't help.
Without it:
  - hangs: 2x
  - ok: 12x
With GC_RETRY_SIGNALS=1:
  - hangs: 3x
  - ok: 16x
You can see, it's a similar hang probability.

To reproduce, you can use the machine gcc113.fsffrance.org on the GCC compile farm https://cfarm.tetaneutral.net/ .

**Comment by ivmai** [comment]
> To reproduce, you can use the machine gcc113.fsffrance.org on the GCC compile farm

Unfortunately, it seems to take time to get the access (I've sent a request).
Meanwhile, could you please retry on latest master (and latest release-8_0 branch), and post the stack trace, if reproduced.

**Comment by ivmai** [comment]
I failed to reproduce it on travis (https://app.travis-ci.com/github/ivmai/bdwgc/builds/238450296) on latest release-8_0 branch (commit 5b05db68955 plus GC_RETRY_SIGNALS=1) running gctest in a loop (>60 times).
Host: Ubuntu 16.04.6 LTS / arm64

**Comment by ivmai** [comment]
I think this issue is fixed, please let me know if not.
