### ISSUE TITLE
Autotools-based build failed on FreeBSD because of libgc.la

### ISSUE THREAD

**Issue by ivmai** [ivmai/bdwgc#361]
Source: master (https://github.com/ivmai/bdwgc/commit/69495eb00ef18b0c19fbcbc36472570bb39e90ef)
OS: FreeBSD 12/x86_64
Build link: https://travis-ci.com/github/ivmai/bdwgc/jobs/516766446

$ configure --enable-cplusplus
$ make -j32 check
--- check-recursive ---
--- extra/.dirstamp ---
--- extra/.deps/.dirstamp ---
make[1]: make[1]: don't know how to make ./libgc.la. Stop

**Comment by ivmai** [comment]
\+ @wangp

**Comment by wangp** [comment]
The problem doesn't occur with GNU make.

The problem occurs with FreeBSD make only with -jN.

This seems to "fix" it, but I don't really know anything about automake:
```diff
diff --git a/cord/cord.am b/cord/cord.am
index c2ea532d..aaa976bb 100644
--- a/cord/cord.am
+++ b/cord/cord.am
@@ -7,7 +7,7 @@ LIBCORD_VER_INFO = 5:0:4
 
 lib_LTLIBRARIES += libcord.la
 
-libcord_la_LIBADD = $(top_builddir)/libgc.la
+libcord_la_LIBADD = libgc.la
 libcord_la_LDFLAGS = -version-info $(LIBCORD_VER_INFO) -no-undefined
 libcord_la_CPPFLAGS = $(AM_CPPFLAGS)
 
@@ -19,12 +19,12 @@ libcord_la_SOURCES = \
 TESTS += cordtest$(EXEEXT)
 check_PROGRAMS += cordtest
 cordtest_SOURCES = cord/tests/cordtest.c
-cordtest_LDADD = $(top_builddir)/libcord.la
+cordtest_LDADD = libcord.la
 
 ## In case of static libraries build, libgc.a is already referenced in
 ## dependency_libs attribute of libcord.la file.
 if ENABLE_SHARED
-cordtest_LDADD += $(top_builddir)/libgc.la
+cordtest_LDADD += libgc.la
 endif
 
 EXTRA_DIST += \
```

**Comment by ivmai** [comment]
> The problem occurs with FreeBSD make only with -jN.

Hmm. I tried with -j1 but the issue still occurs, e.g. https://www.travis-ci.com/github/ivmai/bdwgc/jobs/522909962

**Comment by wangp** [comment]
Perhaps I just got lucky with my `-j1` runs.

Anyway, looking slightly deeper into it, Automake generates a Makefile in the top-level directory containing the rule:
```
libgc.la: $(libgc_la_OBJECTS) $(libgc_la_DEPENDENCIES) $(EXTRA_libgc_la_DEPENDENCIES)
        $(AM_V_CCLD)$(libgc_la_LINK) -rpath $(libdir) $(libgc_la_OBJECTS) $(libgc_la_LIBADD) $(LIBS)
```
For some reason, BSD make won't use that rule to satisfy a dependency on `./libgc.la`. If the file `libgc.la` already exists then that dependency *is* satisfied. The patch above deletes the `$(top_builddir)/` prefix so that the dependency is on `libgc.la`, which can then be satisfied by the rule above.

**Comment by ivmai** [comment]
>  The patch above deletes the $(top_builddir)/ prefix so that the dependency is on libgc.la, which can then be satisfied by the rule above.

No, it does not work (https://travis-ci.com/github/ivmai/bdwgc/builds/233168467).

**Comment by ivmai** [comment]
But the patch works if --disable-cplusplus: https://travis-ci.com/github/ivmai/bdwgc/builds/233169476

**Comment by ivmai** [comment]
OK, I've committed your suggestion with some modifications. Thank you.
