### ISSUE TITLE
Visual Studio 2019 Unresolved External

### ISSUE THREAD

**Issue by RottenBlock** [ivmai/bdwgc#367]
I've compiled stable version 8.0.4 as instructed by README.win32.  Here are my steps just to be clear:

- Boot Visual Studio 2019 developer command prompt.
- Navigate to folder.
- Use command "nmake -f NT_MAKEFILE cpu=i386 make_as_lib=1 nothreads=1 nodebug=1"

Everything runs fine and test.cpp runs correctly. But when I try to use the resulting gc.lib in visual studio, I invariably get an unresolved external error. Any ideas what I'm doing wrong?

Attempting to follow the instructions in README.win64 does not work. It eventually returns the error:

"[...]\private\gcconfig.h(1362): fatal error C1189: #error:  This should be handled as X86_64
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX86\x86\cl.EXE"' : return code '0x2'"

**Comment by ivmai** [comment]
> Everything runs fine and test.cpp runs correctly. But when I try to use the resulting gc.lib in visual studio, I invariably get an unresolved external error. Any ideas what I'm doing wrong?

Which error message exactly? Probably calling convention differs. Check the value of GC_CALL during build and during usage.

> "[...]\private\gcconfig.h(1362): fatal error C1189: #error: This should be handled as X86_64

You try to build x86_64 library but you use x86 compiler (32-bit).

**Comment by ivmai** [comment]
Alternatively you could build the compiler directly from your project (as a part of your project):
E.g. to build single-threaded collector using command line (it will produce gc.obj):
cl -I include -c extra/gc.c

**Comment by ivmai** [comment]
Got it.

> Use command "nmake -f NT_MAKEFILE cpu=i386 make_as_lib=1 nothreads=1 nodebug=1"

You build GC as static library (because make_as_lib=1).

> But when I try to use the resulting gc.lib in visual studio, I invariably get an unresolved external error
> error LNK2001: unresolved external symbol __imp__GC_malloc

Your app wants GC_malloc residing in gc.dll (i.e. shared library, not static).

You need to add -D GC_NOT_DLL option to your app configuration. (See "Microsoft Tools" section in README.win32).

**Comment by RottenBlock** [comment]
Thank you, I may try those other options in the future!
