### ISSUE TITLE
When is the new release coming?

### ISSUE THREAD

**Issue by Sija** [ivmai/bdwgc#368]
The last release is from March 2019 and there were many important changes to this date that ought to be packaged and shipped. Could we expect a new release in the upcoming future? And if so, when?

**Comment by ivmai** [comment]
Sorry for a very long delay.
I'm thinking of making a release candidate (8.2.0) in 2 weeks.
Also, v8.0.6 will be released at the same time.

**Comment by ivmai** [comment]
The 1st stable 8.2.x version is expected to come in Nov.

**Comment by straight-shoota** [comment]
@ivmai Any progress on the releases? =)

**Comment by ivmai** [comment]
One week delay. A couple of bugs prevents the release(

**Comment by ivmai** [comment]
The releases are prepared:
1. Legacy ones: v7.2o, v7.4.20, v7.6.14
2. Recent stable one: [v8.0.6](https://github.com/ivmai/bdwgc/releases/tag/v8.0.6)
3. Experimental: [v8.2.0](https://github.com/ivmai/bdwgc/releases/tag/v8.2.0)

**Comment by ivmai** [comment]
v8.2.0 is currently building on [Travis CI](https://app.travis-ci.com/github/ivmai/bdwgc/builds/238707703) - I will add the release notes later today.

**Comment by ivmai** [comment]
Next plan - v8.2.2 (stable release) in Dec 2021.
Remaining issues to fix before the release:

- #373 - linux/ppc64le: cmake: assert in test_cpp
- #316 - linux/arm64 and linux/s390x: sigsegv in threadkey_test
- #238 - llinux/x64: threadkey_test sigsegv
- #256 - cygwin64: gctest child process failed
- #237 - linux/x64: Race between GC_remove_counts and GC_find_header

**Comment by ivmai** [comment]
> Next plan - v8.2.2 (stable release) in Dec 2021.

Very long delay and not all outlined issues fixed( but here's the first stable 8.2.x release - https://github.com/ivmai/bdwgc/releases/tag/v8.2.2
