### ISSUE TITLE
Not found package on freebsd.pkgs.org

### ISSUE THREAD

**Issue by 78Star** [ivmai/bdwgc#385]
I tried to install boehm-gc-threaded package on freebsd 12.
Command:
`pkg add https://pkg.freebsd.org/FreeBSD:12:amd64/quarterly/All/boehm-gc-threaded-8.0.4_1.txz`
Response:
`pkg: https://pkg.freebsd.org/FreeBSD:12:amd64/quarterly/All/boehm-gc-threaded-8.0.4_1.txz: Not Found`

**Comment by 78Star** [comment]
Looks like I just solved it. The page bellow needs to be updated to use version 8.0.6.txz like wise for the page bellow that for boehm-gc
https://freebsd.pkgs.org/12/freebsd-amd64/boehm-gc-threaded-8.0.4_1.txz.html
https://freebsd.pkgs.org/12/freebsd-amd64/boehm-gc-8.0.4_1.txz.html

**Comment by ivmai** [comment]
This is downstream issue, i.e. should be handled by FreeBSD folks.

@wangp, could you please help with the html pages update?
