### ISSUE TITLE
doc folder layout redesign

### ISSUE THREAD

**Issue by rdp** [ivmai/bdwgc#386]
This directory: https://github.com/ivmai/bdwgc/tree/master/doc
Seems a bit crowded, with configuration mixed in with platform specific docs.  Maybe it could be split into separate directories somehow, or child directories?  Just a thought.

**Comment by ivmai** [comment]
Hello.
I don't see currently how changing doc/README_* to doc/*/README improve understanding of the content or make it easier to find particular information. If I don't get or you have more details about your though, please share. I'm not closing this issue. (Definitely the bdwgc documentation is not perfect, it worth paying attention to. I've already posted some ideas in the issues about potential improvements.)

**Comment by rdp** [comment]
I was imagining doc/{overview, porting, scale}.md and then doc/platforms/README.* or something, just to make the doc dir less overwhelming, but I mean whatever you'd like to do, thanks!

**Comment by ivmai** [comment]
Okay, got it, you could try.
Note: before submitting a PR please test the build and installation process with both build systems (configure and cmake), like make install.

**Comment by ivmai** [comment]
I agree this will make it less overwhelming

**Comment by ivmai** [comment]
Related #387

**Comment by ivmai** [comment]
Seems to be done, closing the issue.
