### ISSUE TITLE
Missing headers like gc_pthread_redirects.h if installing with --enable-single-obj-compilation

### ISSUE THREAD

**Issue by jakub-w** [ivmai/bdwgc#388]
Some header files, like `include/gc_pthread_redirects.h` are missing if installing with `--enable-single-obj-compilation` (the default) even though options like `--enable-threads=posix` were specified.

The problem is that 06e4efff9949a670d41e4455ca1d4eee3d9ba58c put the specification of header inclusion inside the `!SINGLE_GC_OBJ` block in `Makefile.am`, which means that these headers won't ever be included in the installed package if using single object compilation.

**Comment by ivmai** [comment]
Duplicates (should be solved by) PR #389
