### ISSUE TITLE
7.4.0: include/gc_cpp.h: Declaring and assigning breaks non gcc compiles

### ISSUE THREAD

**Issue by marksolaris** [ivmai/bdwgc#39]
The immediate setting of a variable when declaring it in include/gc_cpp.h breaks the Sun Studio compiler as invalid syntax. On Solaris at least all values are already zero'd at declaration anyway so it's not required.

```
host:/var/tmp/bdw-gc-7.4.0/include root# grep ' = 0' gc_cpp.h
                          GC_NS_QUALIFY(GCCleanUpFunc) cleanup = 0,
                          void* clientData = 0 );
                              GC_NS_QUALIFY(GCCleanUpFunc) cleanup = 0,
                              void* clientData = 0 );
```

I use this to fix for compiling, note the space before the equals, so the normal assigns still work in the header file.

```
perl -pe 's# = 0##' -i include/gc_cpp.h
```

Packages for 7.4.0 on Solaris can be found at:
http://www.ibiblio.org/pub/packages/solaris/sparc/

**Comment by ivmai** [comment]
Cannot reproduce. I used: Studio 12.5 Sun C++ 5.14 SunOS_i386 2016/05/31
