### ISSUE TITLE
__stack_base__ undefined on Win32/arm64 with llvm-mingw

### ISSUE THREAD

**Issue by woollybah** [ivmai/bdwgc#405]
While attempting to build my project on Windows 11 ARM, targeting `arm64`, with the [llvm-mingw project](https://github.com/mstorsjo/llvm-mingw), there was an error during linkage, with an undefined symbol - `__stack_base__`.

A dig into the sources revealed this is related to `NOSYS`.

Adding `&& !defined(_WIN32)` to the machine type section, here :
https://github.com/ivmai/bdwgc/blob/cfd78a42ebea3fe071476a0a964cdd2d2a2c62dc/include/private/gcconfig.h#L148-L156
appears to resolve the issue, for me.

**Comment by ivmai** [comment]
Good catch! I will make the patch.
