### ISSUE TITLE
GC_init SEGV while in gdb

### ISSUE THREAD

**Issue by yjwen** [ivmai/bdwgc#409]
Hi,

  I recently updated my ArchLinux and found my program built on libgc always caught SEGV while running in gdb. There wasn't such SEGV before and there isn't such SEGV when running just in command line, not in gdb. Not sure it is related to libgc or gdb. But any hint will be deeply appreciated.

libgc version: 8.2.0
gdb version: 11.1

The SEGV was reproduced by compiling the example [loop.c](https://www.hboehm.info/gc/simple_example.html) and `file loop` and `run` in gdb. Crash at os_dep.c, line 1020, code `GC_noop1((word)(*result))`. 

What I noticed is the different value of `_end` inside and out of gdb. `_end` value changes at each run. But some typical values looks like:

- in gdb: 0x5555555b89c0
- out of gdb: 0x555bc1bea9c0

`result` decreased multiple times at both case, but result in memory access violation in gdb, while jumped(?) out without error when out of gdb.

Could you please give some suggestion on resolving this issue? Thanks.

**Comment by ivmai** [comment]
SEGV you are describing is not a bug, it is a way to determine beginning of data roots. You could ignore it in the gdb by:
handle SIGSEGV pass noprint nostop

Alternatively, you could compile libgc with CFLAGS_EXTRA=-DUSE_PROG_DATA_START
(provided you don't pass -Bsymbolic-functions).

The issue related to you question - issue #321

> What I noticed is the different value of _end inside and out of gdb. _end value changes at each run.

This should be OK too.

**Comment by yjwen** [comment]
I see. Tried ignoring SIGSEGV in gdb and it did work. Thanks for the explaination.

**Comment by fweimer-rh** [comment]
@ivmai Is there a reason why you do not use [`dl_iterate_phdr`](https://man7.org/linux/man-pages/man3/dl_iterate_phdr.3.html) or similar interfaces? Thanks.

**Comment by ivmai** [comment]
> @ivmai Is there a reason why you do not use [`dl_iterate_phdr`](https://man7.org/linux/man-pages/man3/dl_iterate_phdr.3.html) or similar interfaces? Thanks.

What do you mean by "do not use"? Please see https://github.com/ivmai/bdwgc/search?q=dl_iterate_phdr

**Comment by ivmai** [comment]
> Sorry, I meant that dl_iterate_phdr should already give you the segment boundaries, without the need for probing.

Right, but it is how it works now (at least in master).
GC_register_data_segments() (which does the probing) is called only if dl_iterate_phdr is 0 (i.e. dl_iterate_phdr is not available).
See GC_register_main_static_data() in dyn_load.c.

**Comment by fweimer-rh** [comment]
@yjwen What's your glibc version? Thanks.

**Comment by yjwen** [comment]
Mine is glibc 2.35 and GCC 11.2, Arch Linux

**Comment by T-J-Teru** [comment]
> > Sorry, I meant that dl_iterate_phdr should already give you the segment boundaries, without the need for probing.
> 
> Right, but it is how it works now (at least in master). GC_register_data_segments() (which does the probing) is called only if dl_iterate_phdr is 0 (i.e. dl_iterate_phdr is not available). See GC_register_main_static_data() in dyn_load.c.
> 
> Please check on your target if dl_iterate_phdr is available and non-zero (and, if so, the probing should not happen).

I'm running on Fedora Linux with glibc 2.30.  `dl_iterate_phdr` is definitely available, I can see `GC_register_main_static_data` return `FALSE`, which means that `GC_register_dynamic_libraries_dl_iterate_phdr` does NOT take the quick exit path, and performs the full scan.

However, I still see a segfault, and this is before `GC_register_data_segments` is even called.  Here's the backtrace at the time of the segfault:

```
#0  0x00007ffff70e207e in GC_find_limit_with_bound (p=0x2cf20f0 "", up=0, bound=0x0) at ../src/extra/../os_dep.c:1028
#1  0x00007ffff70e20ee in GC_find_limit (p=0x2cf20f0, up=0) at ../src/extra/../os_dep.c:1040
#2  0x00007ffff70e1edc in GC_init_linux_data_start () at ../src/extra/../os_dep.c:472
#3  0x00007ffff70e03d3 in GC_init () at ../src/extra/../misc.c:1217
#4  0x00007ffff7dfae9f in scm_storage_prehistory () from /lib64/libguile-2.0.so.22
#5  0x00007ffff7e0a8ff in scm_i_init_guile () from /lib64/libguile-2.0.so.22
#6  0x00007ffff7e6576f in scm_i_init_thread_for_guile.part () from /lib64/libguile-2.0.so.22
#7  0x00007ffff7e65876 in with_guile_and_parent () from /lib64/libguile-2.0.so.22
#8  0x00007ffff70e12e7 in GC_call_with_stack_base (fn=0x7ffff7e657c0 <with_guile_and_parent>, arg=0x7fffffffab70)
    at ../src/extra/../misc.c:2181
#9  0x00007ffff7e65cac in scm_with_guile () from /lib64/libguile-2.0.so.22
#10 0x00000000008ae7ea in gdbscm_initialize (extlang=0x17ca920 <extension_language_guile>)
    at ../../src.dev-1/gdb/guile/guile.c:681
#11 0x0000000000841528 in ext_lang_initialization () at ../../src.dev-1/gdb/extension.c:338
#12 0x00000000009e08e4 in captured_main_1 (context=0x7fffffffb130) at ../../src.dev-1/gdb/main.c:1055
#13 0x00000000009e165c in captured_main (data=0x7fffffffb130) at ../../src.dev-1/gdb/main.c:1341
#14 0x00000000009e16c7 in gdb_main (args=0x7fffffffb130) at ../../src.dev-1/gdb/main.c:1366
#15 0x00000000004175bd in main (argc=3, argv=0x7fffffffb238) at ../../src.dev-1/gdb/gdb.c:32
```

This is using current HEAD of the master branch, commit a6e21c52.  Given this didn't seem to align with your comments about the segfault not being needed if dl_iterate_phdr is available, I wonder what I might be doing wrong here?  Any insight into avoiding the need to probe would be great, thanks.

**Comment by ivmai** [comment]
> This is using current HEAD of the master branch, commit https://github.com/ivmai/bdwgc/commit/a6e21c52d378a6ce617660bb9383069e8b9dd8a7. Given this didn't seem to align with your comments about the segfault not being needed if dl_iterate_phdr is available

Agree! I've created #432
