### ISSUE TITLE
Do not use probing to determining main data root start if dl_iterate_phdr is available (Linux)

### ISSUE THREAD

**Issue by ivmai** [ivmai/bdwgc#432]
On behalf of @fweimer-rh (copied from #409):

dl_iterate_phdr should already give you the segment boundaries, without the need for probing.
These segfaults are really confusing to developers, so we would really like to find a way to eliminate them. Why are they needed?

I'm running on Fedora Linux with glibc 2.30. dl_iterate_phdr is definitely available, I can see GC_register_main_static_data return FALSE, which means that GC_register_dynamic_libraries_dl_iterate_phdr does NOT take the quick exit path, and performs the full scan.
However, I still see a segfault, and this is before GC_register_data_segments is even called. Here's the backtrace at the time of the segfault:
```
#0  0x00007ffff70e207e in GC_find_limit_with_bound (p=0x2cf20f0 "", up=0, bound=0x0) at ../src/extra/../os_dep.c:1028
#1  0x00007ffff70e20ee in GC_find_limit (p=0x2cf20f0, up=0) at ../src/extra/../os_dep.c:1040
#2  0x00007ffff70e1edc in GC_init_linux_data_start () at ../src/extra/../os_dep.c:472
#3  0x00007ffff70e03d3 in GC_init () at ../src/extra/../misc.c:1217
...
```

**Comment by ivmai** [comment]
@fweimer-rh, please check the above commit - it should not cause Sigsegv.

**Comment by sasshka** [comment]
I confirm there's no SIGSEGV anymore when running gdb under gdb during the gc initialization
