### ISSUE TITLE
Questions regarding debugging

### ISSUE THREAD

**Issue by aboeglin** [ivmai/bdwgc#437]
Hello, I'm currently debugging a hard-to-reproduce issue. The setup is not simple and the app runs with libuv and libcurl. I have a segmentation fault on a program that happens like every 50-500 runs. I just built all libs with debug symbols and I have now added `GC_DEBUG` and use `GC_MALLOC_UNCOLLECTABLE` for pretty much everything for now. I also enable assertions and two things came out of this:

From time to time I have an assertion that fails from alloc.c:
```C
1763|      /* Sweep blocks for objects of this size */
1764|        GC_ASSERT(!GC_is_full_gc
1765|                  || NULL == GC_obj_kinds[kind].ok_reclaim_list
1766|                  || NULL == GC_obj_kinds[kind].ok_reclaim_list[gran]);
```
I think that might now fail before the program would segfault. What can this assertion tell me? Where should I be looking for next given this fails?

The second one is that I now get a lot of these messages:
```
GC_check_heap_block: found 9 smashed heap objects:
...
```
They all point to that line of code ( that's my code ):
```c
char **encodedChars = (char **)GC_MALLOC_UNCOLLECTABLE(sizeof(char *) * i);
```
What is a smashed object?

Last one. I somehow just managed to get this assertion error:
```
// malloc.c
593|    GC_ASSERT(GC_base(p) == p);
```
Which, going up a few stack frames comes from libuv calling GC_free. That one I could just fix by giving a noop as the free function when setting up allocation functions for libuv. Also I'm not sure how that could happen, would that be a bug in libuv freeing a wrong pointer? After comparing `GC_base(p)` and `p` there was like a small offset between the two.

**Comment by ivmai** [comment]
> What is a smashed object?

It's an object which was detected to be used after manual free().

**Comment by ivmai** [comment]
To simplify debugging I recommend to use latest bdwgc (master) and compile it in single-threaded mode (if your app is not multi-threaded).

**Comment by ivmai** [comment]
Is the issue reproduced when your app uses GC_free?

**Comment by ivmai** [comment]
> From time to time I have an assertion that fails from alloc.c:
> 1763|      /* Sweep blocks for objects of this size */
> 1764|        GC_ASSERT(!GC_is_full_gc

Is this reproducible even if bdwgc is compiled with --disable-disclaim passed to configure?

**Comment by ivmai** [comment]
> After comparing GC_base(p) and p there was like a small offset between the two.

p passed to free should be exactly the same as obtained from malloc, it is the responsibility of the client.

**Comment by aboeglin** [comment]
Thanks for your answers, they helped a lot!

> p passed to free should be exactly the same as obtained from malloc, it is the responsibility of the client.
What I thought. I think I found what caused that to happen. After looking at my code I was very surprised as that pointer was not altered in any way. What happened is that I still had an occurence of `GC_free` mixed with `GC_MALLOC` and debug turned on.

Finally I think the main issue I had was with libcurl holding a pointer that was GC_malloc'd in a structure allocated with malloc. That caused ( very rarely ) a segmentation fault when GC was triggered right between these few instructions. I managed to fix it all by using this function: https://curl.se/libcurl/c/curl_global_init_mem.html and passing allocation functions from bdwgc. After that I managed to get the program to repeatedly run for 48h without a crash ( where before it'd always fail within 4-6 hours but would usually occur every 30 minutes or so ). Closing it as the issue is fixed.

NB: To anyone using bdwgc with libcurl and having issues feel free to ping me if you need assistance.
