### ISSUE TITLE
Question: Interpreting GC_prof_stats_s

### ISSUE THREAD

**Issue by z64** [ivmai/bdwgc#438]
I have an application that is returning the following `GC_prof_stats` object (JSON-ified here)

```json
{
  "heap_size": "2.41G",
  "free_bytes": "61.7M",
  "unmapped_bytes": "52.4M",
  "bytes_since_gc": "31.2M",
  "bytes_before_gc": "418G",
  "non_gc_bytes": "0.0",
  "gc_no": 5595,
  "markers_m1": 1,
  "bytes_reclaimed_since_gc": "30.0M",
  "reclaimed_bytes_before_gc": "241G"
}
```

While the `heap_size` is reported as `2.86G`, the total VM memory is actually closer to 7.5G, at which it can remain stable for a very long time (days) 

`top` reports the following for the process in question:

```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
   1224 root      20   0 6533380   5.8g  26056 S   1.3  74.3 442:30.38 server
```

With regards to the documentation here:
```c
  GC_word heapsize_full;
            /* Heap size in bytes (including the area unmapped to OS).  */
            /* Same as GC_get_heap_size() + GC_get_unmapped_bytes().    */
```

---

My main question is: Where should I look to understand the makeup of the memory not accounted for in `heap_size`?

Is the only explanation memory allocated *outside* of `bdwgc`? Essentially I am observing a leak of some kind, but I can't tell if `bdwgc` is at play or some other code in the stack.

For further context I am using `bdwgc` inside a [Crystal](https://crystal-lang.org/) application runitme. But they don't have tools to profile, so I'm trying to find other methods to identify any issues.

**Comment by ivmai** [comment]
New field was added in v8.2.0 - obtained_from_os_bytes which accounts all memory allocated by bdwgc.
Mostly the momory not counted by heapsize_full is allocated by alloc_hdr() - such memory is never reused for any purpose other than hdr struct objects.

**Comment by z64** [comment]
@ivmai Thank you! I will investigate this.

**Comment by ivmai** [comment]
Closing the issue for now - feel free to reopen if needed.

**Comment by z64** [comment]
@ivmai We're still investigating, but I can update you that I have exposed the new 8.2.0 fields on our production server:

```json
{
  "heap_size": "1.61G",
  "free_bytes": "201M",
  "unmapped_bytes": "169M",
  "bytes_since_gc": "105M",
  "bytes_before_gc": "404G",
  "non_gc_bytes": "0.0",
  "gc_no": 2034,
  "markers_m1": 1,
  "bytes_reclaimed_since_gc": "98.2M",
  "reclaimed_bytes_before_gc": "195G",
  "expl_freed_bytes_since_gc": "35.1M",
  "obtained_from_os_bytes": "1.67G"
}
```
So it would seem there is still a large amount of memory to account for still.
