### ISSUE TITLE
CORD: Support for %zu (and possibly %zx, %zd) format specifier

### ISSUE THREAD

**Issue by KivApple** [ivmai/bdwgc#439]
Many C libraries support %zu format specifier for printf-family functions (some of them also support %zx and %zd). This allows portable printing of size_t/ssize_t values which width is platform-dependent. It would be nice if CORD_printf and friends would support these specifiers too. For the moment, CORD_printf, CORD_sprintf etc cannot parse %zu and return -1 error code if it occurs in the format string.

**Comment by ivmai** [comment]
Agree. I think we could modify extract_conv_spec() to return e.g. *long_arg==2 if 'z'.
Could you please contribute a patch (including a test)?

**Comment by ivmai** [comment]
I've made the patch - please test it.
