### ISSUE TITLE
Testsuite fail building for WebAssembly

### ISSUE THREAD

**Issue by skainz** [ivmai/bdwgc#440]
Hello,

i am currently trying to build boehm-gc for WebAssembly.
I need this for guile, which i need for lilypond later.

I am using Version 8.2.0, with the following configure line:

``CFLAGS="-s ASYNCIFY -s ASYNCIFY_STACK_SIZE=20000000 -s INITIAL_MEMORY=$(( 1024 * 1024 * 256))" LDFLAGS="-s ASYNCIFY -s ASYNCIFY_STACK_SIZE=20000000 -s INITIAL_MEMORY=$(( 1024 * 1024 * 256))" emconfigure ./configure --prefix=${TARGET_DIR} --enable-static=yes --enable-shared=no ``

After building i  modified ``test-driver``, line 107, to the following:

``node "$@" >$log_file 2>&1 ``

The i run make check, which results in: 
```
PASS: cordtest
FAIL: gctest
PASS: leaktest
PASS: middletest
PASS: smashtest
PASS: hugetest
PASS: realloc_test
PASS: staticrootstest
PASS: disclaim_test
PASS: disclaim_bench
PASS: disclaim_weakmap_test
```

The ``test-suite.log`` file contains the following:

 ```
================================
   gc 8.2.0: ./test-suite.log
================================

# TOTAL: 11
# PASS:  10
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: gctest
============

/tmp/gc-8.2.0/gctest:146
      throw ex;
      ^

RangeError: Maximum call stack size exceeded
    at <anonymous>:wasm-function[168]:0x4d048
    at <anonymous>:wasm-function[169]:0x4d7b4
    at <anonymous>:wasm-function[17]:0x1d15
    at <anonymous>:wasm-function[22]:0x2d70
    at <anonymous>:wasm-function[22]:0x2df2
    at <anonymous>:wasm-function[22]:0x2df2
    at <anonymous>:wasm-function[22]:0x2df2
    at <anonymous>:wasm-function[22]:0x2df2
    at <anonymous>:wasm-function[22]:0x2df2
    at <anonymous>:wasm-function[22]:0x2df2
FAIL gctest (exit status: 7)

```

What am I missing here?

Thank you very much!

Simon

**Comment by ivmai** [comment]
Could you please retry on master?

**Comment by skainz** [comment]
Hello,

just tried, sorry, exactly the same.

Regards,

Simon

**Comment by ivmai** [comment]
Is this reproduced if compiled with -DBIG=600 (or even with -DBIG=200)? See BIG definition in tests/gctest.c

**Comment by skainz** [comment]
Hello,

i added/changed the following, and then all check pass !

```
#   elif defined(OSF1) || defined(EMSCRIPTEN)                                                  
      /* OSF has limited stack space by default, and large frames. */                          
#     define BIG 200       
```

Do you want a pull request explicity for this, or how could we handle this issue? And is this the right way to do this anyway?

Regards,

Simon

**Comment by ivmai** [comment]
Got it. I'll make a patch on behalf of you (today or tomorrow) - it is a small fix, easy to handle myself

**Comment by ivmai** [comment]
I've just pushed it to master - please test.

**Comment by skainz** [comment]
Hello,

thanks, works now:

```
PASS: cordtest
PASS: gctest
PASS: hugetest
PASS: leaktest
PASS: middletest
PASS: realloctest
PASS: smashtest
PASS: staticrootstest
PASS: disclaimtest
PASS: disclaim_bench
PASS: weakmaptest
============================================================================
Testsuite summary for gc 8.3.0
============================================================================
# TOTAL: 11
# PASS:  11
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
```
