### ISSUE TITLE
implicit declaration of function ‘pthread_attr_get_np’ warning

### ISSUE THREAD

**Issue by Zopolis4** [ivmai/bdwgc#445]
On the gcc_boehmgc branch, while trying to compile it as part of the gcc tree it throws this error:
```
../../../gcj/boehm-gc/pthread_support.c: In function ‘GC_get_thread_stack_base’:
../../../gcj/boehm-gc/pthread_support.c:1153:7: warning: implicit declaration of function ‘pthread_attr_get_np’; did you mean ‘pthread_attr_getscope’? [-Wimplicit-function-declaration]
 1153 |   if (pthread_attr_get_np (my_pthread, &attr) != 0)
      |       ^~~~~~~~~~~~~~~~~~~
      |       pthread_attr_getscope
```
I've looked at commits related to it, but can't find a solution that works. Due to the way gcc bootstraps, it seems -Werror is silently enabled and this results in a generic Error 2 preventing me from building gcc further.

**Comment by ivmai** [comment]
gcc_boehmgc is not intended to be compilable, it serves a mirror of gcj folder of gcc repository (before abandoning gcj support in gcc).
You could either ignore warning, or use use master (or release-8_2, or release-8_0) branch instead. In the latter case you'd probably need the patch enabling the use of upstream bdwgc in gcj - see https://gcc.gnu.org/legacy-ml/java-patches/2016-q2/msg00019.html

I'm closing this issue for now, but if you find the issue on master or release branch then please reopen it.
