### ISSUE TITLE
Race between GC_calloc_explicitly_typed and GC_push_complex_descriptor

### ISSUE THREAD

**Issue by ivmai** [ivmai/bdwgc#449]
Build: https://app.travis-ci.com/github/ivmai/bdwgc/jobs/569448228
Source: master (247e735)
Host: Ubuntu/x64
How to reproduce: ./configure --disable-parallel-mark && make check CFLAGS_EXTRA="-fsanitize=thread -fno-omit-frame-pointer -D NTHREADS=10" && ./gctest
Occurrence: rare

Stack traces (sample):
```
 Read of size 8 at 0x7fd14e226328 by thread T4 (mutexes: write M4):
    // nelements = d -> ld.ld_nelements;
    #0 GC_push_complex_descriptor /home/travis/build/ivmai/bdwgc/extra/../typd_mlc.c:411:31 (libgc.so.1+0x3aaea)
    #1 GC_array_mark_proc /home/travis/build/ivmai/bdwgc/extra/../typd_mlc.c:477:26 (libgc.so.1+0x3a956)
    #2 GC_mark_from /home/travis/build/ivmai/bdwgc/extra/../mark.c:766:28 (libgc.so.1+0x3162d)
    #3 GC_mark_some /home/travis/build/ivmai/bdwgc/extra/../mark.c:379:17 (libgc.so.1+0x2b52f)
    #4 GC_collect_a_little_inner /home/travis/build/ivmai/bdwgc/extra/../alloc.c:707:17 (libgc.so.1+0xcc66)

Previous write of size 8 at 0x7fd14e226328 by main thread:
    // lp -> ld_nelements = leaf.ld_nelements;
    #0 GC_calloc_explicitly_typed /home/travis/build/ivmai/bdwgc/extra/../typd_mlc.c:679:28 (libgc.so.1+0x1eca7)
    #1 typed_test /home/travis/build/ivmai/bdwgc/tests/gctest.c:1291:29 (lt-gctest+0x4b19cc)
```

**Comment by ivmai** [comment]
Hello @hboehm 
Could you please advise me how to fix this race properly? (race between set and get of typed descriptor)

**Comment by hboehm** [comment]
I finally had a chance to look at this briefly.

I suspect the real problem is that we store the descriptor in the last word
of the object (lines 681 and 686), and then read it  in get_complex_descr
as ordinary data, but we need to make sure that the data in the descriptor
is visible to the GC reading it. So I think the stores (at 681 and 686)
need to be atomic release operations. By C++ rules, the reads should also
really be acquire operations. There may be hacks to avoid the latter, but
it's probably better to just make it a release operation.

Hans

**Comment by ivmai** [comment]
Agree. I've prepared the patch.

**Comment by ivmai** [comment]
>  By C++ rules, the reads should also really be acquire operations. There may be hacks to avoid the latter, but it's probably better to just make it a release operation.

There's a sem_post() call in Linux thread suspend handler and, assuming mark procedure is called when the world is stopped, there should be a barrier (according to specification of sem_post). Other cases: Darwin and Windows (I don't know, need to check it); marking when the world is not stopped (could see null descriptor, right? but should be not an issue as marking is redone later with the world stopped, correct?)

**Comment by ivmai** [comment]
>    # 3 GC_mark_some /home/travis/build/ivmai/bdwgc/extra/../mark.c:379:17 (libgc.so.1+0x2b52f)
>    # 4 GC_collect_a_little_inner /home/travis/build/ivmai/bdwgc/extra/../alloc.c:707:17 (libgc.so.1+0xcc66)

GC_mark_some here is called with the world running.

**Comment by ivmai** [comment]
Finally I used store_release() for simple descriptor (word) but acquire lock when writing pointer to leaf or complex descriptor.
```
GC_malloc_explicitly_typed:
    op = GC_malloc_kind(lb, GC_explicit_kind);
    AO_store_release((volatile AO_t *)op + nwords - 1, d)

GC_malloc_explicitly_typed_ignore_off_page:
    op = GENERAL_MALLOC_IOP(lb, GC_explicit_kind);
    AO_store_release((volatile AO_t *)op + nwords - 1, d)

GC_calloc_explicitly_typed:
    op = GC_malloc_kind(lb, GC_array_kind);
    if (descr_type == LEAF) {
      struct LeafDescriptor *lp = ...
      lp -> ld_tag = LEAF_TAG;
      lp -> ld_size = leaf.ld_size;
      lp -> ld_nelements = leaf.ld_nelements;
      lp -> ld_descriptor = leaf.ld_descriptor;
      LOCK();
      ((word *)op)[nwords - 1] = (word)lp;
      UNLOCK();
    } else { /* COMPLEX */
      LOCK();
      ((word *)op)[nwords - 1] = (word)complex_d;
      UNLOCK();
    }
```
