### ISSUE TITLE
-lrt linkage required for Linux

### ISSUE THREAD

**Issue by todd-richmond** [ivmai/bdwgc#450]
both configure.ac and CMakeLists.txt are missing logic to include -lrt for Linux 6/7 systems in the same way it included for other OS. i don't have Linux 8 to try at the moment but adding -lrt for the others resolves missing clock_gettime()

**Comment by ivmai** [comment]
Got it. A patch would be very helpful.

**Comment by ivmai** [comment]
Should be fixed now. Please test.
