### ISSUE TITLE
Moving GCJ away from in-tree bdwgc (export of GC_n_set_marks)

### ISSUE THREAD

**Issue by Zopolis4** [ivmai/bdwgc#460]
I'm working on a project that used to use an in-tree copy of bdwgc, but I'm trying to move to a copy installed by a package manager.
What would I replace the `private/dbg_mlc.h` include with? Some of the functions are supposed to be externally visible, such as `GC_n_set_marks`, but I don't know which header to use to include them.

**Comment by Zopolis4** [comment]
https://github.com/Zopolis4/gcj/blob/msterstable/libjava/gnu/gcj/util/natGCInfo.cc#L57

**Comment by ivmai** [comment]
Aha, this is GCJ. Some time ago (many years ago) I've proposed a patch to migrate GCJ to vanilla bdwgc, but unfortunately at that time the maintainers of GCC decided to drop GCJ support so my patch was not accepted. I will post a link to it here a bit later.

**Comment by ivmai** [comment]
> Aha, this is GCJ. Some time ago (many years ago) I've proposed a patch to migrate GCJ to vanilla bdwgc, but unfortunately at that time the maintainers of GCC decided to drop GCJ support so my patch was not accepted. I will post a link to it here a bit later.

Please see these commits to migrate gcc in-tree libgc to vanilla bdwgc: https://github.com/ivmai/gcc/commits/match-bdwgc-api?author=ivmai
Maybe it would be helpful to you.

**Comment by ivmai** [comment]
Which functions and macros do you miss? Could you please list them.

**Comment by Zopolis4** [comment]
> Please see these commits to migrate gcc in-tree libgc to vanilla bdwgc: https://github.com/ivmai/gcc/commits/match-bdwgc-api?author=ivmai Maybe it would be helpful to you.

These are quite helpful-- how do you want me to credit you? I feel a little odd just copying and pasting your code, even with attribution in the commit message. I suppose I could cherry-pick them, but I can't modify the changelog directly. You could PR them, if you want, although all the commits are going to be squashed in the end. What would you prefer?

**Comment by ivmai** [comment]
> These are quite helpful-- how do you want me to credit you? I feel a little odd just copying and pasting your code, even with attribution in the commit message. I suppose I could cherry-pick them, but I can't modify the changelog directly. You could PR them, if you want, although all the commits are going to be squashed in the end. What would you prefer?

You could add me like this, somewhere at the end of commit message:
Co-authored-by: Ivan Maidanski <ivmai@mail.ru>

I do like this when I use someone's commit heavily refactored, e.g.: https://github.com/ivmai/bdwgc/commit/9aa962ac70a1

**Comment by ivmai** [comment]
No, I don't want to PR them, please take care off.

**Comment by Zopolis4** [comment]
> Which functions and macros do you miss? Could you please list them.

I think its just the ones in natGCInfo.cc that were previously included by "private/dbg_mlc.h", so 
```
  int GC_n_set_marks(hdr* hhdr);
  ptr_t GC_clear_stack(ptr_t p);
  extern int GC_gcj_kind;
  extern int GC_gcj_debug_kind;
```

**Comment by ivmai** [comment]
GC_clear_stack is already public
GC_free_bytes: use GC_get_unmapped_bytes() instead.
hhdr is just a local var (or macro argument) - nothing to do about it.
hdr is short for struct hblkhdr (we need to think how to deal with the latter)

**Comment by ivmai** [comment]
Refined list of what to export additionally (or to propose a replacement):
Functions:
* GC_n_set_marks
* GC_is_black_listed
* GC_apply_to_all_blocks

Vars:
* GC_free_bytes[]
* GC_hblkfreelist[]

Types:
* struct hblkhdr

Macros:
* N_HBLK_FLS
* HBLKSIZE
* HDR
* mark_bit_from_hdr()

**Comment by ivmai** [comment]
Should be deleted from natGCInfo.cc:
```
/*
  this next section of definitions shouldn't really be here.
  copied from boehmgc/allchblk.c
*/

# define UNIQUE_THRESHOLD 32
# define HUGE_THRESHOLD 256
# define FL_COMPRESSION 8
# define N_HBLK_FLS ...
...
# ifdef USE_MUNMAP
#   define IS_MAPPED(hhdr) (((hhdr) -> hb_flags & WAS_UNMAPPED) == 0)
# else  /* !USE_MMAP */
#   define IS_MAPPED(hhdr) 1
# endif /* USE_MUNMAP */
```

**Comment by ivmai** [comment]
> Refined list of what to export additionally (or to propose a replacement): ...

All is needed only for debugging / verbose logging purpose (and only if HAVE_PROC_SELF_MAPS), thus it is OK to make the symbols exportable only if bdwgc is built with NO_DEBUGGING defined.

**Comment by ivmai** [comment]
BTW, the following 3 lines could be deleted from natGCInfo.cc:
```
#endif

#ifdef HAVE_PROC_SELF_MAPS
```

**Comment by ivmai** [comment]
I'm not going to export the following because libgc (8.0.0+) is built with USE_MUNMAP defined by default:
N_HBLK_FLS
GC_free_bytes[]
GC_large_free_bytes

**Comment by ivmai** [comment]
hb_sz could be replaced like this:
hdr * hhdr = HDR(h); ... hhdr->hb_sz  
->
GC_size(h)

**Comment by ivmai** [comment]
hb_flags and WAS_UNMAPPED: I will provide some API function for this.

**Comment by ivmai** [comment]
HBLKSIZE: I will provide some API function to get it.

**Comment by ivmai** [comment]
GC_is_black_listed() and GC_apply_to_all_blocks(): I will export these functions.

**Comment by ivmai** [comment]
GC_hblkfreelist[], N_HBLK_FLS, hb_next: I will add an interator:
void GC_iterate_free_hblks(fn, word client_data) where fn has same type as for GC_apply_to_all_blocks.

**Comment by ivmai** [comment]
mark_bit_from_hdr() could be replaced as:
hdr * hhdr = HDR(h);
mark_bit_from_hdr(hhdr,BYTES_TO_WORDS(i));
->
GC_is_marked((char*)h+i)

**Comment by ivmai** [comment]
GC_n_set_marks: I will add GC_count_set_marks_in_hblk(const void*), so that the replacement could be:
GC_n_set_marks(HDR(p))
->
GC_count_set_marks_in_hblk(p)

**Comment by Zopolis4** [comment]
So far so good, I've applied your suggestions and `GC_get_hblk_size` works perfectly.

**Comment by ivmai** [comment]
> hb_flags and WAS_UNMAPPED: I will provide some API function for this.

Will be in gc_mark.h:
```
#define GC_WAS_UNMAPPED 2
unsigned GC_hblk_flags(const void *obj);
```

So, you could replace
hdr * hhdr = HDR(h); hdr->hb_flags
to GC_hblk_flags(h)

**Comment by ivmai** [comment]
I will continue next week (maybe earlier).

**Comment by Zopolis4** [comment]
Thanks! `GC_hblk_flags()` looks like it'll resolve 10 out of the 13 errors, then exporting `N_HBLK_FLS`, `GC_hblkfreelist[]` and `GC_is_black_listed()` look like they'll solve the rest. No rush, GCJ doesn't even get to `natGCInfo.cc` yet due to a gcc upstream [issue](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=69410).

**Comment by ivmai** [comment]
> hb_flags and WAS_UNMAPPED: I will provide some API function for this.

I don't see any use of hb_flags and WAS_UNMAPPED (these were used in IS_MAPPED but this one is never used and now removed). So, I will not export GC_get_hblk_flags.

**Comment by ivmai** [comment]
> GC_hblkfreelist[], N_HBLK_FLS, hb_next: I will add an interator:
> void GC_iterate_free_hblks(fn, word client_data) where fn has same type as for GC_apply_to_all_blocks.

This is the only remaining item to do, right?

**Comment by Zopolis4** [comment]
Yup.

**Comment by ivmai** [comment]
Done. Please check it.

**Comment by Zopolis4** [comment]
Having a little trouble adapting the code to the function, mainly because I can't find the function to call the loop with (i.e. GC_print_debug_callback like i did for GC_apply_to_all_blocks).

**Comment by ivmai** [comment]
Do you mean  you want to print  "Free list <index>"?
Okay, let's change fn type to:
void (GC_CALLBACK *)(struct GC_hblk_s *, int index, GC_word /* client_data */)

In this case, you need to keep prev_index in client_data, if current index deffers from prev_index then output "Free list <index>"

**Comment by Zopolis4** [comment]
Here's my current [attempt](https://gist.github.com/Zopolis4/c1b59ada14578f874a0949533ec63114) at moving it over, having difficulties with accessing the internal variables.

```
/home/zopolis4/gcjbuild/../gcj/libjava/gnu/gcj/util/natGCInfo.cc: In function ‘void GC_print_hblkfreelist_file_function(FILE*)’:
/home/zopolis4/gcjbuild/../gcj/libjava/gnu/gcj/util/natGCInfo.cc:60:12: error: ‘h’ was not declared in this scope
   60 |   if (0 != h)
      |            ^
/home/zopolis4/gcjbuild/../gcj/libjava/gnu/gcj/util/natGCInfo.cc:61:53: error: ‘i’ was not declared in this scope
   61 |     fprintf (fp, "Free list %ld:\n", (unsigned long)i);
      |                                                     ^
/home/zopolis4/gcjbuild/../gcj/libjava/gnu/gcj/util/natGCInfo.cc:62:10: error: ‘h’ was not declared in this scope
   62 |   while (h != 0)
      |          ^
/home/zopolis4/gcjbuild/../gcj/libjava/gnu/gcj/util/natGCInfo.cc: In function ‘void GC_print_hblkfreelist_file(FILE*)’:
/home/zopolis4/gcjbuild/../gcj/libjava/gnu/gcj/util/natGCInfo.cc:84:60: error: invalid use of void expression
   84 |   GC_iterate_free_hblks(GC_print_hblkfreelist_file_function(fp), fp);
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
```

**Comment by ivmai** [comment]
Got it, I will update bdwgc and provide you a sample.
BTW h is 1st argument of the callback function passed to GC_iterate_free_hblks

**Comment by ivmai** [comment]
I've change the callback of GC_iterate_free_hblks to pass also index. Should work for you.
See how I changed GC_print_hblkfreelist to use GC_iterate_free_hblks (in commit 4dca489).

**Comment by ivmai** [comment]
The code in natGCInfo.cc may look like:
```
struct print_hblkfl_s {
  FILE *fp;
  GC_word total_free;
  int prev_index;
};

static void GC_CALLBACK print_hblkfl_file_item(struct GC_hblk_s *h, int i,
                                               GC_word client_data)
{
  print_hblkfl_s *pdata = (print_hblkfl_s *)client_data;

  if (pdata->prev_index != i) {
    fprintf(pdata->fp, "Free list %d:\n", i);
    pdata->prev_index = i;
  }

  sz = GC_size(h);
  fprintf(pdata->fp, "\t0x%lx size %lu ", (unsigned long)h,
           (unsigned long)sz);
  pdata->total_free += sz;

  if (GC_is_black_listed(h, GC_get_hblk_size()) != 0)
    fprintf(pdata->fp, "start black listed\n");
  else if (GC_is_black_listed(h, sz) != 0)
    fprintf(pdata->fp, "partially black listed\n");
  else
    fprintf(pdata->fp, "not black listed\n");
}

static void
GC_print_hblkfreelist_file(FILE *fp)
{
  print_hblkfl_s data;
  data.fp = fp;
  data.total_free = 0;
  data.prev_index = -1;
    
  fprintf(fp, "---------- Begin free map ----------\n");
  GC_iterate_free_hblks(print_hblkfl_file_item, (word)&data);
  fprintf(fp, "Total of %lu bytes on free list\n",
           (unsigned long)data.total_free);
  fprintf(fp, "---------- End free map ----------\n");
}
```
