### ISSUE TITLE
Change in exported symbols from libgccpp causing failing builds on Debian 32-bit archs

### ISSUE THREAD

**Issue by ianw** [ivmai/bdwgc#472]
This is for discussing the build issues from https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1018924

Here are the builds in question

* https://buildd.debian.org/status/logs.php?arch=armel&pkg=libgc&ver=1%3A8.2.2-1
* https://buildd.debian.org/status/logs.php?arch=armhf&pkg=libgc&ver=1%3A8.2.2-1
* https://buildd.debian.org/status/logs.php?arch=i386&pkg=libgc&ver=1%3A8.2.2-1
* https://buildd.debian.org/status/logs.php?arch=mipsel&pkg=libgc&ver=1%3A8.2.2-1

It is failing due to to some symbols that seem to have changed in 8.2.2 v prior versions.  This didn't show up on the x86-64 build.

```
dpkg-gensymbols: warning: some new symbols appeared in the symbols file: see diff output below
dpkg-gensymbols: error: some symbols or patterns disappeared in the symbols file: see diff output below
dpkg-gensymbols: warning: debian/libgc1/DEBIAN/symbols doesn't match completely debian/libgc1.symbols
--- debian/libgc1.symbols (libgc1_1:8.2.2-1_i386)
+++ dpkg-gensymbolsf2Km8i	2022-08-31 07:23:33.015811392 +0000
@@ -293,10 +293,14 @@
 libgccpp.so.1 libgc1 #MINVER#
  _Z18GC_throw_bad_allocv@Base 1:8.0
  _ZdaPv@Base 1:7.2d
- _ZdaPvm@Base 1:7.6.4
+ _ZdaPvj@Base 1:8.2.2-1
+#MISSING: 1:8.2.2-1# _ZdaPvm@Base 1:7.6.4
  _ZdlPv@Base 1:7.2d
- _ZdlPvm@Base 1:7.6.4
- _Znam@Base 1:7.6.4
- _Znwm@Base 1:7.6.4
+ _ZdlPvj@Base 1:8.2.2-1
+#MISSING: 1:8.2.2-1# _ZdlPvm@Base 1:7.6.4
+ _Znaj@Base 1:8.2.2-1
+#MISSING: 1:8.2.2-1# _Znam@Base 1:7.6.4
+ _Znwj@Base 1:8.2.2-1
+#MISSING: 1:8.2.2-1# _Znwm@Base 1:7.6.4
 libgctba.so.1 libgc1 #MINVER#
  _Z18GC_throw_bad_allocv@Base 1:8.2.2
dh_makeshlibs: error: failing due to earlier errors
```

**Comment by danglin44** [comment]
On 2022-09-04 6:28 p.m., Ian Wienand wrote:
>
> Here are the builds in question
>
>   * https://buildd.debian.org/status/logs.php?arch=armel&pkg=libgc&ver=1%3A8.2.2-1
>     <https://buildd.debian.org/status/logs.php?arch=armel&pkg=libgc&ver=1%3A8.2.2-1>
>   * https://buildd.debian.org/status/logs.php?arch=armhf&pkg=libgc&ver=1%3A8.2.2-1
>     <https://buildd.debian.org/status/logs.php?arch=armhf&pkg=libgc&ver=1%3A8.2.2-1>
>   * https://buildd.debian.org/status/logs.php?arch=i386&pkg=libgc&ver=1%3A8.2.2-1
>     <https://buildd.debian.org/status/logs.php?arch=i386&pkg=libgc&ver=1%3A8.2.2-1>
>   * https://buildd.debian.org/status/logs.php?arch=mipsel&pkg=libgc&ver=1%3A8.2.2-1
>     <https://buildd.debian.org/status/logs.php?arch=mipsel&pkg=libgc&ver=1%3A8.2.2-1>
>
> It is failing due to to some symbols that seem to have changed in 8.2.2 v prior versions. This didn't show up on the x86-64 build.
>
> ||
and
https://buildd.debian.org/status/fetch.php?pkg=libgc&arch=hppa&ver=1%3A8.2.2-1&stamp=1661931658&raw=0

-- 
John David Anglin  ***@***.***

**Comment by ianw** [comment]
This was really introduced by 

https://salsa.debian.org/debian/libgc/-/commit/5d12713c738441fe97d67624c60a53264540496e

When I look at that more closely now; we do have filters for 32/64 bit on these C++ symbols in the old symbols file which have been dropped

https://salsa.debian.org/debian/libgc/-/commit/5d12713c738441fe97d67624c60a53264540496e#68e18e7cb81418958df5613799a7e0186f1a6da8

```
libgccpp.so.1 libgc1 #MINVER#
 _Z18GC_throw_bad_allocv@Base 1:8.0
 _ZdaPv@Base 1:7.2d
 (arch-bits=32)_ZdaPvj@Base 1:7.6.4
 (arch-bits=64)_ZdaPvm@Base 1:7.6.4
 _ZdaPvm@Base 1:7.6.4
 _ZdlPv@Base 1:7.2d
 (arch-bits=32)_ZdlPvj@Base 1:7.6.4
 (arch-bits=64)_ZdlPvm@Base 1:7.6.4
 (arch-bits=32)_Znaj@Base 1:7.6.4
 (arch-bits=64)_Znam@Base 1:7.6.4
 (arch-bits=32)_Znwj@Base 1:7.6.4
 (arch-bits=64)_Znwm@Base 1:7.6.4
 (arch=sparc sparc64)_etext@Base 1:7.2d
 (arch=kfreebsd-amd64 kfreebsd-i386)etext@Base 1:7.2d
 _ZdlPvm@Base 1:7.6.4
 _Znam@Base 1:7.6.4
 _Znwm@Base 1:7.6.4
```

I think we can add these back in to correct the build; it would be good to understand what was going on in a bit more detail though...

**Comment by ianw** [comment]
I can't really see that this would ever be called at all ...

```
$ echo "_Znwm" | c++filt
operator new(unsigned long)
$ echo "_Znwj" | c++filt
operator new(unsigned int)
```

(p.s. I know this is my Debian packaging issue, not libgc as such, just hoping for input)

**Comment by ianw** [comment]
I think that we have done the right thing with the C .so library, in reducing the exports to what is public.  Clearly the C++ side is different, I think we probably just want to put the symbols back per https://salsa.debian.org/debian/libgc/-/merge_requests/9

But I would welcome any input; C++ symbol exports is not my area of expertise :)

**Comment by ivmai** [comment]
Does adding or removal of no except (or throw()) change the mangled name? (according to gcc or clang rules)

**Comment by ivmai** [comment]
> Does adding or removal of no except (or throw()) change the mangled name? (according to gcc or clang rules)

No, it does not (according to gcc output on Linux/x64):

Same output regardless of GC_NOEXCEPT definition (empty, "noexcept", "throw()"):

```
g++ -I include -D GC_DLL -fPIC -s -shared -o libgccpp.so -D GC_NOEXCEPT=noexcept gc_cpp.
cc gc_badalc.cc -L. -lgc && nm -gD libgccpp.so | grep " T "
0000000000001359 T _Z18GC_throw_bad_allocv
00000000000012a0 T _ZdaPv
00000000000012e2 T _ZdaPvm
000000000000121d T _ZdlPv
00000000000012bf T _ZdlPvm
000000000000123c T _Znam
00000000000011b9 T _Znwm
```

Output with -m32 option (again, does not depend on GC_NOEXCEPT definition):
```
000013ed T _Z18GC_throw_bad_allocv
0000130c T _ZdaPv
00001362 T _ZdaPvj
00001277 T _ZdlPv
00001337 T _ZdlPvj
000012a2 T _Znaj
0000120d T _Znwj
```

**Comment by ivmai** [comment]
I confirm the issue is on Debian side, not here.

@ianw, I think all you need is to specify different mangled symbols for 32- and 64-bit targets.

**Comment by ianw** [comment]
@ivmai Thanks, I think that's what https://salsa.debian.org/debian/libgc/-/merge_requests/9/diffs?commit_id=73a48e41005b266374bd81ac8f801c38f386e362 does -- restores the old symbols for C++.

I'm now a bit worried about the one new symbol that seemed to appear in libgctba.so.1

```
libgctba.so.1 libgc1 #MINVER#
 _Z18GC_throw_bad_allocv@Base 1:8.2.2
```

if this is going to have different 32 and 64 bit symbols?  This just unmanges to ```GC_throw_bad_allocv()``` ... should this even be exported?

**Comment by ivmai** [comment]
> if this is going to have different 32 and 64 bit symbols? This just unmanges to GC_throw_bad_allocv() 

It should have same mangled name on 32- and 64-bit hosts.

> ... should this even be exported?

Yes, it should be exported. Both from libgccpp.so and from libgctba.so. Client should link either of these .so files but not both.
See my better explanation in https://github.com/andyli/libgc-cygwin/pull/9

**Comment by ivmai** [comment]
>  I think that's what https://salsa.debian.org/debian/libgc/-/merge_requests/9/diffs?commit_id=73a48e41005b266374bd81ac8f801c38f386e362

LGTM
