### ISSUE TITLE
GC WARNING for failed GC_text_mapping of libpthread obsolete after glibc 2.34 (which removes libpthread)?

### ISSUE THREAD

**Issue by plajjan** [ivmai/bdwgc#477]
glibc 2.34 removes libpthread, see https://developers.redhat.com/articles/2021/12/17/why-glibc-234-removed-libpthread

Using libgc with REDIRECT_MALLOC and threads on Linux, with dynamic library dlopen wrapping, there's some logic to find libpthread which prints a warning if it's unable to find it, https://github.com/ivmai/bdwgc/blob/master/malloc.c#L474

Since libpthread isn't a separate library anymore it won't show up and I'm faced with this warning. I guess the correct action is to first check glibc version and if >= 2.34 look for libc instead of libpthread?

**Comment by ivmai** [comment]
Do you observe only warnings about libpthread.so? (not the one about ld.so)

**Comment by ivmai** [comment]
> I guess the correct action is to first check glibc version and if >= 2.34 look for libc instead of libpthread?

If pthreads are inside libc, then, as I understand, then the caller cannot be a function of pthreads, because malloc called from such a function cannot be intercepted (because it is linked statically inside libc.so), thus it would be useless (yet harmless) to determine GC_libpthread_start/end.

**Comment by ivmai** [comment]
> first check glibc version

Yes, we have GC_parse_version() and gnu/libc-version.h> with gnu_get_libc_version() for this.

**Comment by ivmai** [comment]
> Do you observe only warnings about libpthread.so? (not the one about ld.so)

@plajjan Do you see only warnings `Failed to find libpthread.so text mapping: Expect crash`?

**Comment by plajjan** [comment]
@ivmai yes exactly, here's example output from running the program:
```
GC Warning: Failed to find libpthread.so text mapping: Expect crash
RSS at second 0 : 4.78906 MB
GC Warning: Heap grown by 65536 bytes while GC was disabled
RSS at second 1 : 5.03516 MB
Actor 0: 473894
Actor 1: 473897
In total across all actors: 947791
Total messages per second: 947791
RSS: 5279744
```

so no warning about ld. I quite frequently get this Heap grown warning too, which I'd be happy to understand better, but at least it seems quite benign. Like maybe I leak some memory but overall my program heap is kept quite small (without GC it's quickly in GB range).

**Comment by plajjan** [comment]
Also, not sure if interesting or not but I added in GC_print_address_map into GC_text_mapping so I could see what it sees and here's that output:
```
---------- Begin address map ----------
00400000-00405000 r--p 00000000 fd:02 1121509843                         /home/kll/terastream/acton/test/perf/ring
00405000-004eb000 r-xp 00005000 fd:02 1121509843                         /home/kll/terastream/acton/test/perf/ring
004eb000-00570000 r--p 000eb000 fd:02 1121509843                         /home/kll/terastream/acton/test/perf/ring
00570000-00575000 r--p 0016f000 fd:02 1121509843                         /home/kll/terastream/acton/test/perf/ring
00575000-0057a000 rw-p 00174000 fd:02 1121509843                         /home/kll/terastream/acton/test/perf/ring
0057a000-005e3000 rw-p 00000000 00:00 0 
7f5c01c00000-7f5c01c28000 r--p 00000000 fd:02 2216959898                 /usr/lib/x86_64-linux-gnu/libc.so.6
7f5c01c28000-7f5c01d98000 r-xp 00028000 fd:02 2216959898                 /usr/lib/x86_64-linux-gnu/libc.so.6
7f5c01d98000-7f5c01df0000 r--p 00198000 fd:02 2216959898                 /usr/lib/x86_64-linux-gnu/libc.so.6
7f5c01df0000-7f5c01df4000 r--p 001f0000 fd:02 2216959898                 /usr/lib/x86_64-linux-gnu/libc.so.6
7f5c01df4000-7f5c01df6000 rw-p 001f4000 fd:02 2216959898                 /usr/lib/x86_64-linux-gnu/libc.so.6
7f5c01df6000-7f5c01e03000 rw-p 00000000 00:00 0 
7f5c01f23000-7f5c01f56000 rw-p 00000000 00:00 0 
7f5c01f56000-7f5c01f58000 r--p 00000000 fd:02 2148658421                 /usr/lib/x86_64-linux-gnu/libuuid.so.1.3.0
7f5c01f58000-7f5c01f5c000 r-xp 00002000 fd:02 2148658421                 /usr/lib/x86_64-linux-gnu/libuuid.so.1.3.0
7f5c01f5c000-7f5c01f5d000 r--p 00006000 fd:02 2148658421                 /usr/lib/x86_64-linux-gnu/libuuid.so.1.3.0
7f5c01f5d000-7f5c01f5e000 r--p 00006000 fd:02 2148658421                 /usr/lib/x86_64-linux-gnu/libuuid.so.1.3.0
7f5c01f5e000-7f5c01f5f000 rw-p 00007000 fd:02 2148658421                 /usr/lib/x86_64-linux-gnu/libuuid.so.1.3.0
7f5c01f5f000-7f5c01f6d000 r--p 00000000 fd:02 2216959905                 /usr/lib/x86_64-linux-gnu/libm.so.6
7f5c01f6d000-7f5c01fdf000 r-xp 0000e000 fd:02 2216959905                 /usr/lib/x86_64-linux-gnu/libm.so.6
7f5c01fdf000-7f5c0203c000 r--p 00080000 fd:02 2216959905                 /usr/lib/x86_64-linux-gnu/libm.so.6
7f5c0203c000-7f5c0203d000 r--p 000dc000 fd:02 2216959905                 /usr/lib/x86_64-linux-gnu/libm.so.6
7f5c0203d000-7f5c0203e000 rw-p 000dd000 fd:02 2216959905                 /usr/lib/x86_64-linux-gnu/libm.so.6
7f5c02048000-7f5c0205a000 rw-p 00000000 00:00 0 
7f5c0205a000-7f5c0205c000 r--p 00000000 fd:02 2203375177                 /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
7f5c0205c000-7f5c02082000 r-xp 00002000 fd:02 2203375177                 /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
7f5c02082000-7f5c0208d000 r--p 00028000 fd:02 2203375177                 /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
7f5c0208d000-7f5c0208f000 r--p 00033000 fd:02 2203375177                 /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
7f5c0208f000-7f5c02091000 rw-p 00035000 fd:02 2203375177                 /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
7ffe1ae3e000-7ffe1ae5f000 rw-p 00000000 00:00 0                          [stack]
7ffe1ae9e000-7ffe1aea2000 r--p 00000000 00:00 0                          [vvar]
7ffe1aea2000-7ffe1aea4000 r-xp 00000000 00:00 0                          [vdso]
---------- End address map ----------
```
as can be seen, there's no libhpthread at all since I'm on glibc 2.35 on this computer.

**Comment by ivmai** [comment]
> so no warning about ld. 
> ...
> 7f5c0205c000-7f5c02082000 r-xp 00002000 fd:02 2203375177                 /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
> as can be seen, there's no libhpthread at all since I'm on glibc 2.35 on this computer.

Got it, thank you. We should remove the warning about libpthread.

**Comment by ivmai** [comment]
> GC Warning: Heap grown by 65536 bytes while GC was disabled
> I quite frequently get this Heap grown warning too, which I'd be happy to understand better, but at least it seems quite benign.

Sometimes the heap is full - the collector should either collect the garbage and expand (grow) the heap, this warning says that someone blocks (disables) collection of garbage (see GC_dont_gc variable). Sometimes it does not hurt but theoretically this could lead to unbounded heap growth (step by step). In some cases, probably the client could force GC (GC_gcollect before disabling GC) to minimize the risk of growing heap in such way.

**Comment by ivmai** [comment]
Please test the above commit, should be fine. I think static check of glibc version is OK in this case.

**Comment by ivmai** [comment]
Commit 8d209bffe avoids GC_text_mapping("libpthread-") call on musl, bionic and glibc 2.34+ at all (instead of just suppressing the warning).

**Comment by plajjan** [comment]
This looks good! Seems to work correctly on the Linux boxes I've tried, thanks!
