### ISSUE TITLE
Pass Boehm allocated buffer to libc function

### ISSUE THREAD

**Issue by Azer0s** [ivmai/bdwgc#484]
So in this code, I try to call `getline` with a buffer I previously alloced from Boehm. Unfortunately, this crashes on Mac OS with the error: `malloc: *** error for object 0x1051b9fa0: pointer being realloc'd was not allocated`. Am I doing something wrong? Is there another way around this?

```c
char *tmp = GC_malloc(sizeof(char) * size);
*tmp = '\0';

size_t old_size = 1;

enum {
    PATH,
    HEADER,
} mode = PATH;

ssize_t n;
while ((n = getline(&tmp, &size, conn_file)) > 0) {
  if (strcmp(tmp, "\r\n") == 0) {
    break;
  }
  block = GC_realloc(block, size + old_size);
  old_size += size;
  strcat(block, tmp);

  switch (mode) {
    case PATH:
      parse_request_meta(request, tmp, n);
      mode = HEADER;
      break;

    case HEADER:
      parse_request_header(request, tmp, n);
      break;

    default:
      assert(false);
  }
}
```

**Comment by ivmai** [comment]
I don't see where `block` variable is assigned initially in the code.

**Comment by Azer0s** [comment]
This is not about the block variable but about tmp

**Comment by ivmai** [comment]
getline may call C realloc if the buffer is not enough, you should allocate tmp with malloc.

**Comment by Azer0s** [comment]
Will it not be randomly deallocated by the GC?

**Comment by ivmai** [comment]
GC deallocates only memory allocated with GC_malloc or friends. If you pass GC-allocated memory to C free or realloc, it is an undefined behavior.

**Comment by Azer0s** [comment]
Alright, thanks for the help! <3
