### ISSUE TITLE
Support targetting musl libc

### ISSUE THREAD

**Issue by plajjan** [ivmai/bdwgc#500]
I attempted to build and use bdwgc targeting the musl libc instead of GNU libc on Linux. Beyond just trying it out, the idea is to get a completely static binary in the end, which musl does support (and glibc does not).

It fails since bdwgc is using `getcontext`:
```
ld.lld: error: undefined symbol: getcontext
>>> referenced by mach_dep.c:345 (./mach_dep.c:345)
>>>               mach_dep.o:(GC_with_callee_saves_pushed) in archive /home/kll/terastream/acton/dist/lib/libactongc.a
```

And musl does not support this, as per https://wiki.musl-libc.org/open-issues.html:
> Legacy functions operating on ucontext_t (getcontext, setcontext, makecontext, swapcontext) are not implemented. They are no longer part of POSIX, but cooperative multi-tasking applications use them. ucontext_t also appears as an argument to sigaction handlers which cannot be used portably.

I wonder, is bdwgc dependency on getcontext a hard dependecy? Are there alternatives that we could move to?

Would it be possible for me to work around this issue by implementing some shim that defines getcontext?

**Comment by plajjan** [comment]
Maybe I should google more before opening an issue here ;)

Seems https://github.com/kaniini/libucontext is just such a compatibility shim1. I will try it out!

**Comment by ivmai** [comment]
If you use `configure` or `cmake` to build bdwgc, it should define `NO_GETCONTEXT` macro. Please check it.

**Comment by plajjan** [comment]
@ivmai cool, thanks, I suppose I should investigate that end first. Thanks!

**Comment by plajjan** [comment]
FWIW, I fixed this for the build.zig I started hacking on, see https://github.com/actonlang/bdwgc/commit/6f729399e329de5373f8f117f85f03181ec64d58
