### ISSUE TITLE
ctest - "No tests were found"

### ISSUE THREAD

**Issue by juj** [ivmai/bdwgc#501]
Running on Windows:

```
    git clone https://github.com/ivmai/bdwgc
    cd bdwgc
    git clone https://github.com/ivmai/libatomic_ops
    mkdir out
    cd out
    cmake ..
    cmake --build .
    ctest
```
results in an error

```
E:\code\bdwgc\out>ctest
Test project E:/code/bdwgc/out
No tests were found!!!
```

![image](https://user-images.githubusercontent.com/225351/203093641-b1e5f8c0-4c48-462d-9527-a5496942e9cc.png)

Though README.md instructions suggests that those incantations should result in running tests?

I.e.

![image](https://user-images.githubusercontent.com/225351/203094035-30123ae5-320f-43c0-83dd-e4a27e21765f.png)

**Comment by ivmai** [comment]
I will fix the docs.
cmake -Dbuild_tests=ON ..
cmake --build
ctest

**Comment by juj** [comment]
Great, thanks!

**Comment by juj** [comment]
Looks like one has to run command `ctest -C Debug` instead of just `ctest`, otherwise ctest will say 14 out of 14 tests failed (Not Run). 

Might be good to mention the config for flipping between testing Debug/Release build. I'd recommend

```
cmake -Dbuild_tests=ON -DCMAKE_BUILD_TYPE=Release ..
cmake --build . --config Release
ctest -C Release
```
that should work on CMake multigenerators like Visual Studio and Xcode, but also on singlegenerators like Unix Makefiles and Ninja. (Change `Release` to `Debug` to test debug build)

**Comment by juj** [comment]
btw, if I'm looking to port bdwgc to a new platform (WebAssembly with Emscripten), is there somewhere recommended "hello world" tests/samples that would be good to look at first for "minimal" test programs? The test files I looked so far look a bit overwhelming for first tests.

**Comment by ivmai** [comment]
Related: #163, #312, #337, #440

**Comment by ivmai** [comment]
> Might be good to mention the config for flipping between testing Debug/Release build. I'd recommend
> cmake -Dbuild_tests=ON -DCMAKE_BUILD_TYPE=Release ..
> cmake --build . --config Release
> ctest -C Release

This is already mentioned here: https://github.com/ivmai/bdwgc/blob/64706a08ec4cdc07160e4bc3f0ece7874f663458/doc/README.cmake#L41
