### ISSUE TITLE
Deprecated, unsupported functions compiling with clang 14 on MacOS 13

### ISSUE THREAD

**Issue by coolbikerdad** [ivmai/bdwgc#514]
While building with Xcode 14 command-line tools (clang 14.0) compiler warnings are generated for deprecated declarations including:
get_etext()
get_end()
getsectbynamefromheader_64()
with the accompanying note:
... is deprecated: first deprecated in macOS 13.0 [-Wdeprecated-declarations]
and
_dyld_bind_fully_image_containing_address()
... is deprecated: first deprecated in macOS 10.5 - dlopen(RTLD_NOW) [-Wdeprecated-declarations]

My concern would be that should these functions be removed in future macOS releases, bdwgc would not build.
Is there a plan to mitigate these deprecations?

**Comment by ivmai** [comment]
As of now, there is no proposal how to avoid these deprecated symbols.

**Comment by ivmai** [comment]
Does anyone have any proposal how not to use the deprecated functions?

**Comment by coolbikerdad** [comment]
I have an idea for a solution for the **getsectbynamefromheader** deprecation warning, it will take a DARWIN specific change **dyn_load.c** that may be best protected by a **configure** definition. I am only compiling via **Makefile.direct** so I'll have to give that change to someone else to figure out. I'll test it out and add a reply here.

As for the final warning about **_dyld_bind_fully_image_containing_address**, I'll take a look, but it may be a little while.

Regards
Neil

**Comment by ivmai** [comment]
Thank you, I will process it in a week.

**Comment by ivmai** [comment]
> I have been looking through the source for bdwgc looking at use of get_etext() and get_end() (they only appear in the definition of DATASTART and DATAEND) and I think there is an error in os_dep.c. 

No, this code part is correct. But I got your point, some change is needed.

**Comment by ivmai** [comment]
Actually get_end and get_etext were not called since commit 111a44f98 (v6.2, year 2003).

**Comment by ivmai** [comment]
Do we need to call dlclose after dlopen?

**Comment by coolbikerdad** [comment]
> I've refactored and merged your code. Please test it on your side. Automatic testing is performed on Travis CI and on Github Actions. Thank you for fixing this long standing issue!

Builds and checks OK using Makefile.direct

However, autogen.sh fails for me. I'd like to be able to use configure, any idea how to fix?

neil@BETH-STUDIO bdwgc ./autogen.sh
configure.ac:27: installing './compile'
configure.ac:18: installing './config.guess'
configure.ac:18: installing './config.sub'
configure.ac:21: installing './install-sh'
configure.ac:21: installing './missing'
src/Makefile.am:14: error: Libtool library used but 'LIBTOOL' is undefined
src/Makefile.am:14:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
src/Makefile.am:14:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
src/Makefile.am:14:   If 'LT_INIT' is in 'configure.ac', make sure
src/Makefile.am:14:   its definition is in aclocal's search path.
src/Makefile.am: installing './depcomp'
parallel-tests: installing './test-driver'
autoreconf: error: automake failed with exit status: 1

**Comment by ivmai** [comment]
> However, autogen.sh fails for me. I'd like to be able to use configure, any idea how to fix?
> neil@BETH-STUDIO bdwgc ./autogen.sh
> ..
> src/Makefile.am:14: error: Libtool library used but 'LIBTOOL' is undefined

Please try the advice reported in https://github.com/ivmai/bdwgc/issues/75#issuecomment-221384481

**Comment by ivmai** [comment]
Commit [18b5111](https://github.com/ivmai/bdwgc/commit/18b511147d818d37824826b5d8cffa3a73cf91ba) caused a regression: issue #596

**Comment by ivmai** [comment]
I hope this is the final change;)

**Comment by mtnygard** [comment]
Hi! Was this change merged into a release or on a branch? I don't see the fix in the 8.2 release or on `master`.

**Comment by ivmai** [comment]
> Hi! Was this change merged into a release or on a branch? I don't see the fix in the 8.2 release or on `master`.

It is not backported to release-8_2 branch. Sorry I'm currently busy with other issues. It would be nice if you could figure out the minimum set of patches needed and do back porting (make a PR).

**Comment by ivmai** [comment]
> Hi! Was this change merged into a release or on a branch? I don't see the fix in the 8.2 release or on `master`.

The issue should be fixed on `master` branch. It consists of s7everal commits (see above).

I am checking possibility of backporting to release 8.2.x
