### ISSUE TITLE
Keep doc folders structure on package install

### ISSUE THREAD

**Issue by ivmai** [ivmai/bdwgc#518]
What else to improve in the doc folder: when the documents are installed they seems to be copied all into one folder (including the base README.md) - this is overwhelming (as mentioned in #386) and breaks links in .md files (for files located in different folder in source repository).

**Comment by ivmai** [comment]
Most (all those I checked) installed packages have flat doc folder.

According to https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes:
> If you put your README file in your repository's hidden .github, root, or docs directory, GitHub will recognize and automatically surface your README to repository visitors.

So, to solve this issue, we could:
1. Change all non-platform READMEs to .md files (https://github.com/ivmai/bdwgc/pull/520#issuecomment-1363727293)
2. Revert PR #515 (as it seems no longer useful after step 1) or change naming pattern to something else, e.g. "README_*"
3. Move README.md to doc folder (and update links)
4. If doc/README.md is still not visible by GitHub from the base folder, then rename doc to docs folder.

**Comment by rdp** [comment]
My initial target was to make the doc folder less overwhelming when viewed in github...with lots of files it was fairly confusing... :)

**Comment by ivmai** [comment]
Yes, I know, the above is just an idea.

**Comment by ivmai** [comment]
I've checked other packages on Ubuntu - some of them have nested folders inside /usr/share/doc/<pkg>, e.g.
p7zip/DOC/MANUAL/general/faq.htm

So, we don't need to revert the above mentioned PR. To solve the current issue, we 
could copy the doc files keeping the folders structure as is in the source repository:
README.md -> /usr/share/doc/libgc-dev/README.md
doc/overview.md -> /usr/share/doc/libgc-dev/doc/overview.md
doc/platforms/README.linux -> /usr/share/doc/libgc-dev/doc/platforms/README.linux
