### ISSUE TITLE
Design question, concurent GC + free?

### ISSUE THREAD

**Issue by deadalnix** [ivmai/bdwgc#546]
Hi,

While this is not really an issue per se, I though to ask a question here would be beneficial as it can be found back later using search engines.

I have been studying the source code of bdwgc with great interest. However, there is something that I do not quite understand. Contrary to more traditional GC uses, this GC must support explicit free operation so it can be dropped in as a replacement for malloc/free. While this wouldn't be a problem in a stop the world situation, this is definitively a problem when done concurrently with a GC cycle and it is not clear to me how this is solved.

Let me explain.

The GC will do lookups for pointer in a datastructure as described [here](https://www.hboehm.info/gc/tree.html) to find a hblk that describe the allocation that lives there. But, as the thread that is marking does its job, we may be freeing the object and making the hblk invalid.

One might retort that we remove the hblk from the tree before invalidating it and/or recycling it, but the following sequence of event remain possible, as far as I can tell:
1. Mark thread fetch a pointer to the hblk in the tree.
2. User thread frees the data represented by the hblk. The hblk is modified to reflect this or even recycled to represent something else.
3. Mark thread uses the hblk to continue its marking process, but it is now representing something else, and/or in an invalid state.

How is this worked around? I can't really find the parts of the code that manages this.

Thanks in advance.

**Comment by ivmai** [comment]
Concurrent free and mark is not possible because each acquires the GC lock.
I think it would be convenient to make a test case to reproduce the scenario you are asking about.

**Comment by ivmai** [comment]
It is a parallel GC, not a concurrent one. This means all threads are stopped while the garbage collector is working.
