### ISSUE TITLE
config doesn't recognize riscv on netbsd

### ISSUE THREAD

**Issue by sauclovian** [ivmai/bdwgc#556]
The RISC-V ifdef on lines 570-571 of include/private/gcconfig.h doesn't include NetBSD so the build fails. Fix is trivial: add "NETBSD" along with "FREEBSD" and "OPENBSD".

**Comment by sauclovian** [comment]
Downstream patch is here: https://mail-index.netbsd.org/pkgsrc-changes/2023/05/28/msg275600.html

**Comment by ivmai** [comment]
Thank you!

**Comment by ivmai** [comment]
@sauclovian, I suggest to update libgc package in NetBSD to v8.2.4 (this will also shortens the gcconfig.h patch).

[1] http://cvsweb.netbsd.org/bsdweb.cgi/pkgsrc/devel/boehm-gc/
