### ISSUE TITLE
README.win32: inconsistency in threads docs for MINGW and pthreads-win32

### ISSUE THREAD

**Issue by spk121** [ivmai/bdwgc#559]
In README.win32, it says to build for MINGW pthreads-win32, use "`--enable-threads=pthreads`"

In the MINGW `mingw-w64-gc` `PKGBUILD`, they instead use "`--enable-threads=posix`"

I think the PKGBUILD is correct.

Also, it is unclear from the README.win32 how to use MINGW `mingw-w64-gc` DLL with MINGW pthread-win32.

My best guess is that
- do need to call GC_INIT from main thread
- do need to include "gc.h" to pick up `pthread_create` macro
- just use `pthread_create` and not `GC_CreateThread`

If I have that right, the doc sort of implies that, but doesn't say that clearly.

**Comment by ivmai** [comment]
> In README.win32, it says to build for MINGW pthreads-win32, use "--enable-threads=pthreads"
> In the MINGW mingw-w64-gc PKGBUILD, they instead use "--enable-threads=posix"

In my understanding the documentation is correct, it just describes 2 variants of the build (relying on pthreads-win32 library and relying on native Win32 thread support). The configure script is a bit tricky regarding this.

**Comment by ivmai** [comment]
> do need to call GC_INIT from main thread 

If possible, it is better to call GC_INIT() from main()

**Comment by ivmai** [comment]
> do need to include "gc.h" to pick up pthread_create macro

Yes, do it before include pthread.h like this:
```
#ifndef GC_THREADS
#define GC_THREADS 1
#endif
#include <gc.h>
#include <pthreads.h> // optional
```

> just use pthread_create and not GC_CreateThread

You can use either or mix them in your code.

**Comment by ivmai** [comment]
If you have idea how to improve the docs, PRs are welcomed!

**Comment by spk121** [comment]
Thank you for the clarifications.  I'll try to make a docs PR when I understand it better.
