### ISSUE TITLE
Does bdwgc track pointers to base classes and class members?

### ISSUE THREAD

**Issue by jeaye** [ivmai/bdwgc#562]
Hi folks. I'm currently using bdwgc in [jank](https://jank-lang.org/), a programming language. bdwgc has made it very easy to get going, so thank you. :)

I've been wondering what bdwgc's promises are regarding the tracking of pointers to base classes, since the pointer values themselves can shift when hanging onto a pointer to the base versus the original pointer value the GC provided when allocating the derived object. Based on some testing I've done, bdwgc does seem to track this and I'd like to understand more about it.

### Example code
```cpp
struct behavior
{
  virtual ~behavior() = default;

  virtual void behave() = 0;
};

struct entity : gc_cleanup, behavior
{
  virtual ~entity()
  { std::cout << "dtor " << this << std::endl; }

  void behave() override
  { }

  std::array<char, 1024> a{};
};

int main()
{
  GC_enable_incremental();

  std::cout << "TEST Allocating entities" << std::endl;

  /* This can be either entity* or behavior* and bdwgc only cleans it up if they're all set to null. */
  std::array<behavior*, 1024> v{};

  for(size_t i{}; i < v.size(); ++i)
  {
    auto e(new (GC) entity{});
    v[i] = e;
    /* The pointer values are different here, due to the size of the vtable ptr.
       On my machine, the behavior* is offset 8 bytes. */
    std::cout << "e " << e << std::endl;
    std::cout << "b " << v[i] << std::endl;
  }

  /* This reliably causes cleanup. */
  //for(auto &e : v)
  //{ e = nullptr; }

  std::cout << "TEST Last collection time" << std::endl;

  GC_gcollect();
}
```

In this example, I can have an array of either `entity*` or `behavior*` and it seems the bdwgc can track them, even though the pointer values change when casting to `behavior*`.

### Questions
1. Is this guaranteed to work for all base classes?
2. Does bdwgc also track pointers to members?

### Clarification of question 2
To expand on the second question, let me expand my example to contain a handle for each entity. Let's assume I held onto a pointer to that instead of the object itself. In my testing, this works, which I found surprising. Is bdwgc just tracking any pointer value within the range of the start of the object + its size?

```cpp
struct behavior
{
  virtual ~behavior() = default;

  virtual void behave() = 0;
};

struct entity : gc_cleanup, behavior
{
  virtual ~entity()
  { std::cout << "dtor " << this << std::endl; }

  void behave() override
  { }

  std::array<char, 1024> a{};
  /* I will store a pointer to this member, rather than the entity or behavior. */
  bool handle{};
};

int main()
{
  GC_enable_incremental();

  std::cout << "TEST Allocating entities" << std::endl;

  std::array<bool*, 1024> v{};

  for(size_t i{}; i < v.size(); ++i)
  {
    auto e(new (GC) entity{});
    v[i] = &e->handle;
    std::cout << "e " << e << std::endl;
    std::cout << "b " << v[i] << std::endl;
  }

  //for(auto &e : v)
  //{ e = nullptr; }

  std::cout << "TEST Last collection time" << std::endl;

  GC_gcollect();
}
```

**Comment by ivmai** [comment]
> what bdwgc's promises are regarding the tracking of pointers to base classes, since the pointer values themselves can shift when hanging onto a pointer to the base versus the original pointer value the GC provided when allocating the derived object.
> ...
> Is this guaranteed to work for all base classes?

Yes, it bdwgc handles pointers to object interiors correctly but provided the corresponding mode is on - it may be set during bdwgc compile time or at runtime. To be sure it is on, please call GC_set_all_interior_pointers(1) at the beginning of main(), e.g. see it in [tests/cpp.cc](https://github.com/ivmai/bdwgc/blob/9b1a6e6d32915cfc24eacd5d6b4ba68d1d74eb74/tests/cpp.cc#L309).

**Comment by ivmai** [comment]
> Does bdwgc also track pointers to members?

Yes, but provided the pointers are allocated in bdwgc heap (i.e. by bdwgc routines). E.g. if you use std::array, the implementation of array might use the default C++ new[] which is not redirected to bdwgc new[] - in this case the elements of the array are not visible to bdwgc.

**Comment by jeaye** [comment]
> > Does bdwgc also track pointers to members?
> 
> Yes, but provided the pointers are allocated in bdwgc heap (i.e. by bdwgc routines). E.g. if you use std::array, the implementation of array might use the default C++ new[] which is not redirected to bdwgc new[] - in this case the elements of the array are not visible to bdwgc.

Thanks for the responses. In my example, the `bool*` was to a `bool` member of something allocated in the bdwgc heap, but the bool itself wasn't directly allocated from bdwgc, only indirectly.

So, the bool isn't an interior pointer, since it's not a pointer, it's a bool. Yet storing pointers to that bool ends up keeping my entities alive. Is this guaranteed by some other mechanism?
