### ISSUE TITLE
System requirements for bdwgc (use on a microcontroller)

### ISSUE THREAD

**Issue by MucaGinger** [ivmai/bdwgc#563]
The following question is of informative nature.

I'm looking for an effective, preferably faster, and less time-deterministic alternative to `malloc()` memory allocator. I'm targetting use in C++ where code runs on a _freestanding_ (no underlying operating system) implementation on a memory constrained device (microcontroller device with up to 1Mbyte of RAM/FLASH and sub-gigahertz frequency of CPU operation speed). Additionally I would be using such a memory allocation mechanism in combination with a pre-allocated (statically, at compile time, fixed-size container) memory and not dynamic (on heap) memory.

Therefore I'm asking whether `bdwgc` is a suitable component for integration in such a system?

**Comment by ivmai** [comment]
I think it is OK to use bdwgc on a system with several hundred KB available for heap. Porting should not be difficult (at least in single-threaded environment, as typical for microcontrollers).
I cannot say about performance - please make an experiment.

**Comment by ivmai** [comment]
If you manage you port bdwgc to your target, it is OK to contribute, I am fine even with a draft patch.
