### ISSUE TITLE
does bdwgc process circular reference?

### ISSUE THREAD

**Issue by mttbx** [ivmai/bdwgc#564]
This is a question. I want to use bdwgc in my cpp project and I want to know does bdwgc process circular reference? Can I just use it and expected everything will be fine?

**Comment by mttbx** [comment]
I find this I gc_cpp.h. So bdwgc can't deal with circular reference or I understand wrong?
```
Thus, if objects A and B both have clean-up functions, and A points at
B, B is considered accessible.  After A's clean-up is invoked and its
storage released, B will then become inaccessible and will have its
clean-up invoked.  If A points at B and B points to A, forming a
cycle, then that's considered a storage leak, and neither will be
collectible.
```

**Comment by mttbx** [comment]
If I linked to gccpp and use traceable_allocator and gc_allocator. And inherit from class gc. Should I worry about circular reference ?

**Comment by ivmai** [comment]
Sorry, I can't answer you exactly right now.
C++ relies on particular variant of GC_register_finalizer_..., please check its documentation.

**Comment by mttbx** [comment]
@ivmai If I don't use destructor function. What's your answer? Do I have to worry about memory leak anymore?

**Comment by ivmai** [comment]
> If I don't use destructor function. What's your answer? Do I have to worry about memory leak anymore?
If A points to B and vice versa: no issue (no leak).

**Comment by mttbx** [comment]
Thank you
