### ISSUE TITLE
gc didn't collect all linklist nodes in c++ 

### ISSUE THREAD

**Issue by mttbx** [ivmai/bdwgc#565]
Here's the program:
```
// compiled with clang++17.
#include <gc/gc.h>
#include <gc/gc_cpp.h>

struct st : gc_cleanup {
  st *next;
  st() { next = nullptr; }
  ~st() { LOG_I(MAIN, "ttt"); }
};

void test() {
  st *a1 = new st();
  a1->next = new st();
  a1->next->next = new st();
}

int main() {
  GC_set_all_interior_pointers(1);
  GC_INIT();

  test();
  GC_gcollect();
  return 0;
}
```

The output is:
```
[MAIN(I)] ttt
```
Apparently only one node is deleted.

**Comment by ivmai** [comment]
This is correct. When a1 is detected, it is made accessible again to run the destructor. So, to collect other objects referenced from a1, you need to run GC again

**Comment by mttbx** [comment]
If I run gc_gcollect multiple times, I can only collect up to two  nodes, the third node is not collected.

**Comment by mttbx** [comment]
Thank you
