### ISSUE TITLE
Pointer tagging

### ISSUE THREAD

**Issue by peter7891** [ivmai/bdwgc#577]
Hello,

I am using pointer tagging in my VM.
It is written in Rust and i am trying to use bindings for this GC.
However, even though i am using the flag POINTER_MASK the GC behaves with UB as if it still 
doesn't know i am doing pointer tagging.
I have non existing C programming experience but the definition of the POINTER_MASK macro or whatever it is looks a bit strange.
Correct me, if i am wrong but this reads like POINTER_SHIFT and POINTER_MASK depend on each other and none of them will actually be defined, which would explain why setting the flag didn't do anything.

```rust
    let dst = Config::new(LIB_GC_DIR)
        .profile("Release")
        .define("BUILD_SHARED_LIBS", "FALSE")
        .cflag(format!(
            "-I{} -DPOINTER_MASK=0x7FFFFFFFFFFFFFF",
            libatomic_include_path,
        ))
        .build();
```        

```C
#if defined(POINTER_MASK) && !defined(POINTER_SHIFT)
# define POINTER_SHIFT 0
#endif

#if defined(POINTER_SHIFT) && !defined(POINTER_MASK)
# define POINTER_MASK ((word)(signed_word)(-1))
#endif

#if !defined(FIXUP_POINTER) && defined(POINTER_MASK)
# define FIXUP_POINTER(p) (p = ((p) & POINTER_MASK) << POINTER_SHIFT)
#endif

#if defined(FIXUP_POINTER)
# define NEED_FIXUP_POINTER
#else
# define FIXUP_POINTER(p)
#endif
```

**Comment by ivmai** [comment]
The definition above looks correct: in short it means if any of mask or shift is defined  then define how to fix up the pointer.

**Comment by ivmai** [comment]
But it might be the fix up is not properly applied everywhere.

**Comment by peter7891** [comment]
> But it might be the fix up is not properly applied everywhere.

When i hardcode this, everything works and i no longer get memory corruption.

```c
#if !defined(POINTER_MASK)
# define POINTER_MASK 0x7FFFFFFFFFFFFFF
#endif
```

**Comment by ivmai** [comment]
> > But it might be the fix up is not properly applied everywhere.
> 
> When i hardcode this, everything works and i no longer get memory corruption.
> 
> ```c
> #if !defined(POINTER_MASK)
> # define POINTER_MASK 0x7FFFFFFFFFFFFFF
> #endif
> ```

How does it differ from -DPOINTER_MASK=0x7FFFFFFFFFFFFFF ?

**Comment by peter7891** [comment]
> > > But it might be the fix up is not properly applied everywhere.
> > 
> > 
> > When i hardcode this, everything works and i no longer get memory corruption.
> > ```c
> > #if !defined(POINTER_MASK)
> > # define POINTER_MASK 0x7FFFFFFFFFFFFFF
> > #endif
> > ```
> 
> How does it differ from -DPOINTER_MASK=0x7FFFFFFFFFFFFFF ?

It differs in the fact that building with this flag, from Rust, does not actually set `POINTER_MASK`.

This does nothing
```rust
    let dst = Config::new(LIB_GC_DIR)
        .profile("Release")
        .define("BUILD_SHARED_LIBS", "FALSE")
        .cflag(format!(
            "-I{} -DPOINTER_MASK=0x7FFFFFFFFFFFFFF",
            libatomic_include_path,
        ))
        .build();
```

**Comment by ivmai** [comment]
> This does nothing

Strange. Issue in the build system.

Alternatively, you could add #define to include/config.h.

**Comment by ivmai** [comment]
> > This does nothing
> 
> Strange. Issue in the build system.
> 
> Alternatively, you could add #define to include/config.h.

Alternatively, this should work:
...
define("BUILD_SHARED_LIBS", "FALSE").define("CFLAGS_EXTRA",
"-DPOINTER_MASK=0x7FFFFFFFFFFFFFF"). ...

**Comment by ivmai** [comment]
BTW. Commit 57828b3c2b (in master) adds API to set pointer mask at runtime (before GC initialization): GC_set_pointer_mask().

**Comment by peter7891** [comment]
> BTW. Commit [57828b3](https://github.com/ivmai/bdwgc/commit/57828b3c2b7e811abd6bb1ba37060eb456b3824e) (in master) adds API to set pointer mask at runtime (before GC initialization): GC_set_pointer_mask(). But this requires: define("enable_dynamic_pointer_mask", "TRUE")

thanks
