### ISSUE TITLE
Only conditionally include `<signal.h>`

### ISSUE THREAD

**Issue by plajjan** [ivmai/bdwgc#588]
I'm trying to use the GC for wasm and I've been targetting wasm32-wasi which is seemingly used by https://github.com/corazawaf/coraza-proxy-wasm/ which I found referenced in https://github.com/ivmai/bdwgc/pull/519 where some support was added to the GC for wasm. However, the build fails because bwdgc imports `<signal.h>` which isn't available. I found the following comment in the coraza-proxy-wasm repo (https://github.com/anuraaga/coraza-proxy-wasm/blob/90a30fc2c3b338f3fcd7e62edee58921b40f60ee/buildtools/bdwgc/Dockerfile#L12):
```
# While signals aren't actually used the header file is included unconditionally. We can enable the header file
# without linking the actual signals library because the functions aren't called.
ENV CFLAGS -D_WASI_EMULATED_SIGNAL ${CFLAGS}
```

I wonder, could we make the include conditional instead, so this would work better out of the box?

**Comment by ivmai** [comment]
Probably, please try.

**Comment by ivmai** [comment]
It seems alloc.c does not need signal.h at all, and mach_dep.c does not include the header on WASI.

**Comment by plajjan** [comment]
Thanks for guidance @ivmai, very helpful. I'll try to hack something together!

**Comment by ivmai** [comment]
Should be fixed now, please test it on wasi target.

**Comment by plajjan** [comment]
Wow, Yes!

Compiles without any errors now!
```
kll@Boxy:~/terastream/acton-deps/bdwgc$ ~/kod/zig/zig-linux-x86_64-0.12.0-dev.1536+6b9f7e26c/zig build -Dtarget=wasm32-wasi
Using musl flags
kll@Boxy:~/terastream/acton-deps/bdwgc$ 
```

FWIW, https://github.com/actonlang/bdwgc/tree/zig-build is the branch I'm using to build that includes a build.zig file if anyone wants to try this out :)

Very nice work Ivan! :)
