### ISSUE TITLE
Memory allocated with `GC_memalign` or `GC_posix_memalign` can't be manually freed.

### ISSUE THREAD

**Issue by jacob-hughes** [ivmai/bdwgc#589]
Consider the following:

```C
#include <stdio.h>

int main() {
    size_t align = 64;
    size_t size = 512;

    void* ptr = GC_memalign(align, size);

    GC_free(ptr);
}
```

When Boehm is built with `-Denable_assertions=On` the above causes the following assertion
to fail in malloc.c:643:

```
GC_ASSERT(GC_base(p) == p);
```

It looks like the alignment requirements mean that extra steps would be needed to correctly identify the base pointer. If we build this without assertions, it segfaults at malloc.c:587.

Perhaps passing the pointer returned from `GC_memalign` to `GC_free` is intentially unsupported in Boehm, and, if so, is there another way to manually free memory that was allocated using `GC_memalign` or `GC_posix_memalign`?

Thanks!

**Comment by ivmai** [comment]
As a workaround you could use GC_free(GC_base(p))

**Comment by ivmai** [comment]
But, of course, it would be better to fix it in GC_memalign() (for align > GC_GRANULE_BYTES && align < HBLKSIZE/2).
I can't say right now how to.

**Comment by ivmai** [comment]
Related issue: #510

**Comment by ivmai** [comment]
Should be solved. Please test.
