### ISSUE TITLE
Remove dependency on CoreFoundation or make it optional

### ISSUE THREAD

**Issue by plajjan** [ivmai/bdwgc#594]
I've been trying to compile bdwgc using zig and zig is currently missing a few header files. I opened an issue for that https://github.com/ziglang/zig/issues/18257 and it was accepted for some of the headers but framework headers will not be included in zig. bdwgc includes `CoreFoundation/CoreFoundation.h` which is part of the `CoreFoundation` framework.

I wonder though, is it really necessary? Or could we maybe make the include conditional? I haven't dug very deep but from a cursory look it appears CoreFoundation.h is used more or less for some form of platform capability detection. 

```c

#ifndef kCFCoreFoundationVersionNumber_iOS_8_0
# define kCFCoreFoundationVersionNumber_iOS_8_0 1140.1
#endif


...


/* Evaluates the stack range for a given thread.  Returns the lower     */
/* bound and sets *phi to the upper one.  Sets *pfound_me to TRUE if    */
/* this is current thread, otherwise the value is not changed.          */
STATIC ptr_t GC_stack_range_for(ptr_t *phi, thread_act_t thread, GC_thread p,
                                mach_port_t my_thread, ptr_t *paltstack_lo,
                                ptr_t *paltstack_hi, GC_bool *pfound_me)
{
...
      if (cputype == CPU_TYPE_ARM64
          || kCFCoreFoundationVersionNumber
             >= kCFCoreFoundationVersionNumber_iOS_8_0) {
        arm_unified_thread_state_t unified_state;
        mach_msg_type_number_t unified_thread_state_count
                                        = ARM_UNIFIED_THREAD_STATE_COUNT;
...
}
```

We are looking for IOS 8.0 or later, right? IOS 8.0 was End-of-Lifed 8 years ago. Maybe we can just remove this condition altogether and assume we are always on ios 8.0 or later?

Or if we want to keep the condition, maybe we could allow a separate variable that instructs the compilation to presume ios 8.0. That way I could do platform detection separately, which I think is already possible with zig...

@ivmai I'd like to hear your thoughts on this and perhaps the reasoning behind this before I dive in and spend more time on it... :)

**Comment by ivmai** [comment]
If you just remove the include, will the build fail?

**Comment by ivmai** [comment]
If we wrap the include into `if defined(ARM32) && defined(ARM_THREAD_STATE32)`, will it fit your needs?

**Comment by plajjan** [comment]
@ivmai I think that would remove my immediate focus which is mostly on removing the need of `CoreFoundation.h` on MacOS machines (which I presume the IOS related checks are not for).

I've looked into zig a bit and it has the concept of macos version with some heuristics code for detecting it. I think this makes sense, i.e. that if a build system has a good idea of the version of the OS or some library dependency, then it can tell us through a variable, like instruct the code how to be compiled. If we do not get that information, we can try to apply heuristics of our own. See what I mean? Like we would try harder in CMake or using the zig build system to determine the macos version rather than include a header file to get the version. Only if the build system does NOT feed us a version, then we apply that heuristic of our own by including the header?

This also plays very well with the cross-compilation support, at least the way it looks in zig, since it would allow that variable to instruct targetting a particular release.

So yes, your suggestion does fix my immediate need but I think doing a slightly bigger take on it would be beneficial :)

**Comment by ivmai** [comment]
> So yes, your suggestion does fix my immediate need 

I will apply it because it is a small change not breaking anything.

>  but I think doing a slightly bigger take on it would be beneficial :)

I got your idea, in general. If you have time to implement it I'm ready to review it.

**Comment by ivmai** [comment]
Closing the issue. You could propose your changes in another PR.
