### ISSUE TITLE
Soft-dirty bit is not supported by kernel on Ubuntu 22.04/x86_64

### ISSUE THREAD

**Issue by ivmai** [ivmai/bdwgc#599]
As mentioned in #579 :
Running gctest on Ubuntu on x86_64 by @UltimatePea:
```
Switched to incremental mode
Emulating dirty bits with mprotect/signals
Completed 6 tests
```

Strange, output should be different, e.g. as in https://app.travis-ci.com/github/ivmai/bdwgc/jobs/614968861 (I get the same output on  a local test PC running Ubuntu 22.04 (kernel 5.15.0-88-generic):
```
cat gctest.log
Switched to incremental mode
Reading dirty bits from /proc
Completed 6 tests
```

**Comment by ivmai** [comment]
> Please run GC_PRINT_VERBOSE_STATS=1 ./gctest |& head -n15

@UltimatePea wrote:
```
$ GC_PRINT_VERBOSE_STATS=1 ./gctest |& head -n15
Got 65536 bytes from OS
Initializing mprotect virtual dirty bit implementation
Soft-dirty bit is not supported by kernel
Recycle 12288/16384 scratch-allocated bytes at 0x7f616ed06020
Grew heap sections array to 32 elements
Got 65536 bytes from OS
Got 65536 bytes from OS
In-use heap: 0% (0 KiB pointers + 0 KiB other)
Got 65536 bytes from OS
Grow heap to 76 KiB after 0 bytes allocated
Got 65536 bytes from OS
Number of processors: 32
Will retry suspend and restart signals if necessary
Initiating full world-stop collection!
0 bytes in heap blacklisted for interior pointers
```

**Comment by ivmai** [comment]
> Soft-dirty bit is not supported by kernel

Strange, I can't reproduce it on my Ubuntu 22.04 x86_64 host. Why is detect_soft_dirty_supported() returning false and what's the value of *vaddr at return? (you could rebuild libgc by `./configure --disable-shared --disable-threads && make check CFLAGS_EXTRA="-O0 -g"` and set breakpoint in the mentioned function in the debugger (`gdb ./gctest`).

What's your kernel version? I've tested it on 5.15.0-88-generic.

**Comment by UltimatePea** [comment]
I am running on `wsl2` on windows.  The OS is still Ubuntu. 
```
uname -r
5.15.133.1-microsoft-standard-WSL2
```

I can try to reproduce this issue on a native Ubuntu install. Please let me know. 

I don't seem to know how to run `./configure`, as something always errors out, but I can run the build command for CMake. Do you have an equivalent command to run for `cmake`?

**Comment by ivmai** [comment]
> I am running on `wsl2` on windows. The OS is still Ubuntu.
> 
> ```
> uname -r
> 5.15.133.1-microsoft-standard-WSL2
> ```

Got it. Then it is as expected (kernel just does not support the soft dirty bots feature), I am closing the issue.

> 
> I can try to reproduce this issue on a native Ubuntu install. Please let me know.
> 
> I don't seem to know how to run `./configure`, as something always errors out, but I can run the build command for CMake. Do you have an equivalent command to run for `cmake`?

You could type simply: gcc -I include -O0 -g -o gctest tests/gctest.c extra/gc.c
