### ISSUE TITLE
gctest fails if shared build by Zig

### ISSUE THREAD

**Issue by ivmai** [ivmai/bdwgc#601]
Source: master (71d1ba4bf)
Build: https://github.com/ivmai/bdwgc/actions/runs/7319490595/job/19937385974
Host: Linux/x64
How to reproduce: `zig/zig build -DBUILD_SHARED_LIBS=true -Dbuild_tests=true -Denable_gc_assertions=true -Denable_large_config=true -Denable_munmap=false test`
Output (gctest):
```
Supported VDBs: manual soft mprotect
Switched to incremental mode
Reading dirty bits from /proc
Test failed
List reversal produced incorrect list - collector is broken
```

Related issue: #557

**Comment by ivmai** [comment]
If threads are on, then gctest fails with:
`GC_is_visible produced wrong failure indication`

**Comment by ivmai** [comment]
The root cause of this, I suppose, is that some roots are not scanned, most provably static roots. E.g. the static roots of gctest itself are not discovered.

**Comment by plajjan** [comment]
I started testing various combinations to find failing cases and adding `-O2` fixed certain cases while others, while it broke others. It's net positive though as fewer things broke than were fixed by adding `-O2`.

**Comment by ivmai** [comment]
Is this observed on Linux only?
I think this duplicates #544 because if you set environment variable GC_USE_GETWRITEWATCH=0 or pass -D NO_SOFT_VDB to cflag then the issue is not reproduced.

**Comment by ivmai** [comment]
Duplicates #544
