### ISSUE TITLE
Zig support improvement

### ISSUE THREAD

**Issue by ivmai** [ivmai/bdwgc#602]
Continuation of #557 and PR #598.

What to improve in build.zig:
- resolve TODO item: specify PACKAGE_VERSION and LIB*_VER_INFO, convert VER_INFO values to [SO]VERSION ones (moved to #638)
- [x] resolve TODO item: support enable_cplusplus
- [x] resolve TODO item: support enable_throw_bad_alloc_library
- [x] resolve TODO item: support build_cord
- [x] change test names to have "test" suffix as produced by cmake
- [x] support MacOS targets
- [x] remove -Dbuild_tests options

What to improve in GH Actions:
- [x] update to zig v0.12 final (when released)
- [x] support cross-compile for MacOS
- [x] build and test natively on MacOS
- [x] support cross-compile for other tier 1 targets
- [x] test with -Denable_cplusplus

**Comment by ivmai** [comment]
@plajjan It would be very convenient to support CFLAGS_EXTRA option, could you please add it?
See CMakeLists.txt and Makefile.direct for the reference. (I'm not sure we need to separate the arguments in CFLAGS_EXTRA.)

**Comment by plajjan** [comment]
With "replace -Denable_threads=false to -fsingle-threaded", do you mean we should replace the user visible input? I don't think that is possible. I think the idea with zig build is that you don't just let users pass compiler flags straight to the compiler but rather expose them as project specific options (the `-D` options) and then set compiler flags based on that. 

If on the other hand you mean that we should set `-fsingle-threaded` based on `-Denable_threads=false`, that should certainly be possible. Zig compilation objects, i.e. libraries and executable, have a single_threaded option on them, that we should probably set. I think that implies `-fsingle-threaded` down the line.

**Comment by plajjan** [comment]
@ivmai yes, I can add a simple CFLAGS_EXTRA option that just passes through its value to the compiler. I don't see any added value in parsing it to separate arguments etc, so straight pass-through it is! :)

**Comment by ivmai** [comment]
> With "replace -Denable_threads=false to -fsingle-threaded", do you mean we should replace the user visible input? I don't think that is possible. I think the idea with zig build is that you don't just let users pass compiler flags straight to the compiler but rather expose them as project specific options (the `-D` options) and then set compiler flags based on that.
> 
> If on the other hand you mean that we should set `-fsingle-threaded` based on `-Denable_threads=false`, that should certainly be possible. Zig compilation objects, i.e. libraries and executable, have a single_threaded option on them, that we should probably set. I think that implies `-fsingle-threaded` down the line.

I mean expose change build.zig to let client build single-threaded library using -fsingle-threaded option (more nature way in zig world if I understand it correctly) instead of -Denable_threads=false option. I.e.:
`zig build -fsingle-threaded` instead of `zig build -Denable_threads=false`.
If this possible. Not a big deal, of course.

**Comment by ivmai** [comment]
Similarly, it looks like `-Dbuild_tests` option is redundant (to build and run the tests we need to pass both this option and `test`). I think it worth to remove build_tests option.

**Comment by plajjan** [comment]
@ivmai I'm no authoritative zig expert but as far as I know this is not possible. `zig build-exe` supports `-fsingle-threaded` but this is for compiling a single zig module / .c into an executable. It is similar to invoking `cc` directly. With `zig build` we use zig as a build system and not as a direct compiler, so we are expected to control things like `single-threaded` through code in `build.zig` and based on that pass down parameters to the compiler. 

Just testing `zig build -fsingle-threaded` is invalid...
```
kll@Boxy:~/terastream/acton-deps/bdwgc$ ~/kod/zig/zig-linux-x86_64-0.12.0-dev.2105+60094cc3f/zig build -fsingle-threaded
Unrecognized argument: -fsingle-threaded
...
```

**Comment by ivmai** [comment]
@plajjan Could we make test names as given in cmake script? (hugetest, subthreadcreatetest, etc.)

**Comment by ivmai** [comment]
> @ivmai yes, I can add a simple CFLAGS_EXTRA option that just passes through its value to the compiler. I don't see any added value in parsing it to separate arguments etc, so straight pass-through it is! :)

It seems that cmake's separate_arguments() is needed, see https://github.com/ivmai/bdwgc/pull/607#issuecomment-1885164978

**Comment by ivmai** [comment]
> Similarly, it looks like `-Dbuild_tests` option is redundant (to build and run the tests we need to pass both this option and `test`). I think it worth to remove build_tests option.

@plajjan I will remove this option. If you agree it is redundant.

**Comment by ivmai** [comment]
> @plajjan Could we make test names as given in cmake script? (hugetest, subthreadcreatetest, etc.)

I'll do it.

**Comment by kassane** [comment]
Taking advantage of the Zig toolchain topic.
I haven't seen any reference about libc++ yet as it is statically linked by default in Zig on all LLVM targets.

What is the level of support between C++ ABI?

**Comment by plajjan** [comment]
@kassane when I built C++ things with Zig I have had to add `.linkLibCpp()` to my build.zig to get it working, doesn't that mean libc++ is not linked in per default?

**Comment by kassane** [comment]
Yes. By adding `-lc++` or `.linkLibCpp()` it is linked by default to llvm-libcxx (static only).

**Comment by ivmai** [comment]
It would be good to add building of libgccpp.so, libgctba.so and cpptest to build.zig (at least to have a working sample of C++ support).

**Comment by kassane** [comment]
also, add msvc support using zig-build.

```zig
// zig v0.12.0 - for C++ build on msvc or gnu

// https://github.com/ziglang/zig/issues/5312
if (exe.rootModuleTarget().abi != .msvc)
    exe.linkLibCpp() // libc++ + libunwind [static]
else
    exe.linkLibC(); // search VSCrt + winSDK
```

**Comment by kassane** [comment]
> It would be good to add building of libgccpp.so, libgctba.so and cpptest to build.zig (at least to have a working sample of C++ support).

My sample: https://github.com/kassane/bdwgc-d/commit/9944b658a3c9592ca38189dea700af59d1282dfb
CI: https://github.com/kassane/bdwgc-d/actions/runs/8741234879

**Comment by ivmai** [comment]
Colleagues, I've added build of cord library (7201f3f) - the code is work, but maybe you could suggest me tips to improve the code if any (cordtest request linking against 2 libs, so I've added addTestExt to be able to pass 2 libs for a test).
