### ISSUE TITLE
Illegal instruction in GC_clear_stack in tests built by Zig on Linux

### ISSUE THREAD

**Issue by ivmai** [ivmai/bdwgc#612]
Source: master (c0936ed)
Build: https://github.com/ivmai/bdwgc/actions/runs/7504908429/job/20433000980
Host: Linux/x86_64
Zig version: 0.12.0-dev.2015
How to reproduce: `zig build -Denable_gc_debug -Denable_redirect_malloc -DBUILD_SHARED_LIBS=false -Denable_threads=false test`
gdb output:
```
(gdb) r
Starting program: middletest
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGILL, Illegal instruction.
0x000000000100ddb1 in GC_clear_stack (arg=0x7ffff7d79f00) at misc.c:394
394           MAKE_COOLER(GC_high_water, WORDS_TO_BYTES(DEGRADE_RATE) + GC_SLOP);
```

**Comment by ivmai** [comment]
/cc @plajjan 

Looks like an issue of LLVM.

**Comment by ivmai** [comment]
Currently this config is excluded from zig build - commit da6260947

**Comment by ivmai** [comment]
Still exists.
Source: master (f791770d60)
Zig version: 0.12.0-dev.3291

**Comment by plajjan** [comment]
Zig runs clang/LLVM and per default Zig enables more sanitization of undefined behavior than what clang normally does. Hitting UB behavior then leads to SIGILL so I suspect that is what is going on here. You can disable some of the UB sanitization in zig/clang or you can try to figure it out. 

A common cause is integer arithmetic and overflow in particular, so when doing bit operations that overflows (it's many times OK), then we're actually hitting UB. I found a couple of such cases and the way it works on all / many CPUs is just fine, but it is basically UB and I'd hit SIGILL.

**Comment by ivmai** [comment]
> A common cause is integer arithmetic and overflow in particular

It seems so, I'll make a workaround.

**Comment by ivmai** [comment]
Fixed.
Also commit 26a0222e4 removes a workaround (and TODO) in github actions.

**Comment by plajjan** [comment]
Nice! :smiley:
