### ISSUE TITLE
7.5.0: include <gc.h> doesn't work, first two tests fail

### ISSUE THREAD

**Issue by Syrdocai** [ivmai/bdwgc#62]
On OS X 10.10, Yosemite

When building with the given instructions, the first two tests fail the "make check" command, gctests and something else. In addition, using "include <gc.h>" with -lgc on clang ang gcc compilers does not work. Please help out fast? Need this garbage collector soon for AST construction.

**Comment by brucehoult** [comment]
This was fixed by my bf62552 and c2918ed
