### ISSUE TITLE
Problem getting finalizers to work

### ISSUE THREAD

**Issue by plajjan** [ivmai/bdwgc#624]
I am trying to get a rather basic version of finalizers going but... it's not working. This is my test program:

```c
#include <stdio.h>

#include <gc.h>

void my_finalizer(void *obj, void *client_data) {
    printf("Finalizing object %p\n", obj); 
}

int main() {
    GC_INIT();
    void *obj = GC_malloc(100);  
    GC_finalization_proc ofn = 0;
    void *ocd = 0;
    printf("GC_get_finalize_on_demand: %d\n", GC_get_finalize_on_demand());
    printf("GC_get_java_finalization: %d\n", GC_get_java_finalization());
    GC_debug_register_finalizer(obj, my_finalizer, NULL, NULL, NULL);

    GC_gcollect(); // Force collection for testing
    return 0;
} 
```

which seems to be about as basic as it gets. I tried to build and link this with the bdwgc version I use in Acton (built statically with enable_redirect_malloc, ignore_free, large_config, enable_mmap) but it fails:
```
GC_get_finalize_on_demand: 0
GC_get_java_finalization: 1
GC_debug_register_finalizer called with non-base-pointer 0x7f8e8f543f50
```

Figuring that it's because of some weird config combination I'm using I opted to link with libgc that I install as apt packages in Debian. I would presume that version is built using some rather well tested combination of config options
```
kll@Boxy:~/para/projects/2024-03-c-bdwgc-finalizer$ make test-stockgc 
~/terastream/acton/dist/zig/zig cc test.c -o test-stockgc -lgc
kll@Boxy:~/para/projects/2024-03-c-bdwgc-finalizer$ ldd test-stockgc 
	linux-vdso.so.1 (0x00007ffe0fa5a000)
	libgc.so.1 => /lib/x86_64-linux-gnu/libgc.so.1 (0x00007f4431281000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f44310a0000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4431312000)
```

but alas, I get the same error:
```
GC_get_finalize_on_demand: 0
GC_get_java_finalization: 1
GC_debug_register_finalizer called with non-base-pointer 0x7fa9bf1a9f50
```

I don't understand, how can obj not be the base-pointer when I just got it from malloc? I presume the GC has some header on like negative addresses, but surely the pointer I get back from GC_malloc should be the pointer I use when interacting with the finalizer functions, no?

I tried to look at what gctest is doing. It's a little hard to read with all the macro and preprocessing conditions but I think it's about the same. At least in CI for this repo, the finalizer tests seem to be working, e.g. https://github.com/ivmai/bdwgc/actions/runs/8305927771/job/22733415190 which writes `Finalized 6616/6616 objects - finalization is probably OK`.

Is my usage incorrect?

**Comment by ivmai** [comment]
I think you should use GC_MALLOC() and GC_REGISTER_FINALIZER() macros.

**Comment by ivmai** [comment]
> do you think we could have a small examples collection where this could be part of solving a very simple case of finalizers?

Please open another issue (feature request) to discuss this. I will add my concerns there.
Thank you!
