### ISSUE TITLE
using extra pointer bits on x86_64 (tagged pointer support)

### ISSUE THREAD

**Issue by paniq** [ivmai/bdwgc#628]
Is it safe to use some of the msbits of 64-bit pointer addresses to store metadata? In other words, does the GC mask out unused msbits by default, so that so-called tagged pointers are supported?

I was trying to figure this out from the source as well as experiments, alas I couldn't figure it out nor find documentation on it, nor google it.

Thanks.

**Comment by ivmai** [comment]
I think you need GC_set_pointer_mask()
Related issue #577

**Comment by paniq** [comment]
> I think you need GC_set_pointer_mask() Related issue #577

This feature is not released yet, is it? 8.2.6 does not seem to have it

**Comment by ivmai** [comment]
Not released yet. Consider POINTER_MASK macro as an alternative.
