### ISSUE TITLE
zig-msvc target error: 'unistd.h' file not found 

### ISSUE THREAD

**Issue by kassane** [ivmai/bdwgc#635]
```bash
+- run middletest
   +- zig build-exe middletest Debug native-native-msvc
      +- zig build-lib gc Debug native-native-msvc 1 errors
D:\a\bdwgc\bdwgc\include/private/gcconfig.h:2588:11: error: 'unistd.h' file not found
D:\a\bdwgc\bdwgc\extra/gc.c:40:10: note: in file included from D:\a\bdwgc\bdwgc\extra/gc.c:40:
D:\a\bdwgc\bdwgc\extra/../backgraph.c:15:10: note: in file included from D:\a\bdwgc\bdwgc\extra/../backgraph.c:15:
D:\a\bdwgc\bdwgc\include/private/dbg_mlc.h:28:10: note: in file included from D:\a\bdwgc\bdwgc\include/private/dbg_mlc.h:28:
```

### References
- #602 
- https://github.com/kassane/bdwgc-d/issues/1

**Comment by ivmai** [comment]
Is _MSC_VER macro predefined by the compiler? I guess no.

**Comment by ivmai** [comment]
If not predefined, then how could we detect msvc target (using some predefined macro)?

**Comment by kassane** [comment]
> Is _MSC_VER macro predefined by the compiler? I guess no.

in my fork: https://github.com/ivmai/bdwgc/compare/master...kassane:bdwgc:zig-msvc

https://github.com/ivmai/bdwgc/blob/ff194429be688b008047db54aef1420c49841fd1/build.zig#L469-L470

```bash
 +- run subthreadcreatetest
   +- zig build-exe subthreadcreatetest Debug native-native-msvc
      +- zig build-lib gc Debug native-native-msvc 20 errors
<command line>:2:9: error: '_MSC_VER' macro redefined
<built-in>:407:2: note: in file included from <built-in>:407:
<built-in>:393:9: note: previous definition is here
```

**Comment by ivmai** [comment]
Aha, I see. Nobody added support of Windows to build.zig. See cmake script as a reference.

**Comment by ivmai** [comment]
How to reproduce it?
I tried with zig 0.12.0 (final) `zig build test` on Win64 host, it works OK.

**Comment by ivmai** [comment]
`flags.append("-D HAVE_UNISTD_H") catch unreachable;` - this should not be defined on Win32

**Comment by kassane** [comment]
> `flags.append("-D HAVE_UNISTD_H") catch unreachable;` - this should not be defined on Win32

https://github.com/ivmai/bdwgc/blob/c77eee19e30773a46e9a00817fcfefa61bca171f/build.zig#L398-L399
**new error**
```bash
D:\a\bdwgc\bdwgc\extra/../gcj_mlc.c:88:31: error: 'getenv' is deprecated: This function or variable may be unsafe. Consider using _dupenv_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
D:\a\bdwgc\bdwgc\extra/gc.c:43:10: note: in file included from D:\a\bdwgc\bdwgc\extra/gc.c:43:
D:\a\bdwgc\bdwgc\include/private/gc_priv.h:781:23: note: expanded from macro 'GETENV'
C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\ucrt/stdlib.h:1183:20: note: 'getenv' has been explicitly marked deprecated here
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.39.33519\include/vcruntime.h:355:55: note: expanded from macro '_CRT_INSECURE_DEPRECATE'
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.39.33519\include/vcruntime.h:345:47: note: expanded from macro '_CRT_DEPRECATE_TEXT'
```
---
#### Try again

https://github.com/ivmai/bdwgc/blob/a97781a277c8f68425e546a9ee17de9066903876/build.zig#L398-L401

```bash
D:\a\bdwgc\bdwgc\extra/../mark.c:531:11: error: extension used
D:\a\bdwgc\bdwgc\extra/gc.c:56:10: note: in file included from D:\a\bdwgc\bdwgc\extra/gc.c:56:
D:\a\bdwgc\bdwgc\extra/../win32_threads.c:1387:7: error: extension used
D:\a\bdwgc\bdwgc\extra/gc.c:77:10: note: in file included from D:\a\bdwgc\bdwgc\extra/gc.c:77:
D:\a\bdwgc\bdwgc\extra/../win32_threads.c:1393:7: error: extension used
D:\a\bdwgc\bdwgc\extra/gc.c:77:10: note: in file included from D:\a\bdwgc\bdwgc\extra/gc.c:77:
error: the following command failed with 3 compilation errors:
```

**Comment by ivmai** [comment]
Make a PR please.

**Comment by kassane** [comment]
> Add "-D DONT_USE_USER32_DLL" to flags

Doesn't it apply to windows in general (gnu & msvc)?
https://github.com/ivmai/bdwgc/blob/df1a787929aa550ec5343442fd2212a2717ac0cd/build.zig#L386-L390

> Make a PR please.

I do.

**Comment by ivmai** [comment]
> Doesn't it apply to windows in general (gnu & msvc)?
[bdwgc/build](https://github.com/ivmai/bdwgc/blob/df1a787929aa550ec5343442fd2212a2717ac0cd/build.zig#L386-L390)

Currently it is applied to static builds only.
You may try to define it for static ones as well, but it is better to specify dependency on user32 system library for static builds.

**Comment by kassane** [comment]
> Currently it is applied to static builds only. You may try to define it for static ones as well, but it is better to specify dependency on user32 system library for static builds.

Got it.

**Comment by kassane** [comment]
I successfully tested using the first PR #636, with the exception of msvc-debug mode.
CI (releases x debug): https://github.com/kassane/bdwgc-d/actions/runs/8803927218
```bash
gc.lib(misc.obj) : error LNK2019: unresolved external symbol _CrtDbgReport referenced in function GC_write
```

**Comment by ivmai** [comment]
> gc.lib(misc.obj) : error LNK2019: unresolved external symbol _CrtDbgReport referenced in function GC_write

This symbol is defined only in debug version of msvc libs. Please check which version of msvc libs are used.

**Comment by ivmai** [comment]
If not possible to instruct msvc to use the correct version of the libs, then there could be a workaround in misc.c (plus a define of NO_CRTDBGREPORT in build.zig):
```
#     if defined(_MSC_VER) && defined(_DEBUG) && !defined(NO_CRT)
```
->
```
#     if defined(_MSC_VER) && defined(_DEBUG) && !defined(NO_CRT) \
         && !defined(NO_CRTDBGREPORT)
```

**Comment by ivmai** [comment]
I'm processing your PR #636. I've to break it into several commits.

**Comment by ivmai** [comment]
What's preventing to turn on -Werror? cmake script uses /W4 /wd4127 /WX /wd4091 options.

**Comment by kassane** [comment]
> Please check which version of msvc libs are used.

Windows (msvc/gnu) linked libs (LLD):
https://github.com/ziglang/zig/blob/refs%2Fheads%2Fmaster/src%2Flink%2FCoff%2Flld.zig#L425-L432

MSVC_libdir search: https://github.com/ziglang/zig/blob/f6f7a47aad7da251f1e4ee6f45b6de79ce8bbbd8/lib/std/zig/WindowsSdk.zig#L589 (`std.zig.WindowsSdk`)

> What's preventing to turn on -Werror? cmake script uses /W4 /wd4127 /WX /wd4091 options.

`zig cc`, need `clang-cl` flags for MSVC!

Currently `zig-toolchain`, can't build `llvm-libcxx + llvm-libunwind` for **MSVC**. So, for this (specific) target, the flags `-nostdlib++` and `-nostdinc++` are used. However, `zig-cc` (`build.zig` called `cc1` as opposed to `c++`) emits warnings about the non-use of flags, with `-Werror` these warnings become errors and stop the compilation.

previoud CI: https://github.com/kassane/bdwgc/actions/runs/8787776049/job/24113766036#step:5:5
```bash
  zig build -Dtarget=native-native-msvc -DBUILD_SHARED_LIBS=false -Ddisable_handle_fork=false -Denable_gc_assertions=true -Denable_gc_debug=false -Denable_large_config=false -Denable_munmap=false -Denable_parallel_mark=false -Denable_redirect_malloc=false -Denable_rwlock=false -Denable_thread_local_alloc=false -Denable_threads=true -Denable_cplusplus=true -Denable_werror test
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
test
+- run cpptest
   +- zig build-exe cpptest Debug native-native-msvc
      +- zig build-lib gccpp Debug native-native-msvc 2 errors
:1:1: error: argument unused during compilation: '-nostdinc++'
:1:1: error: argument unused during compilation: '-nostdinc++'
```

### Reference
- https://github.com/ziglang/zig/issues/5312

**Comment by kassane** [comment]
> I'm processing your PR #636. I've to break it into several commits.

rebased.

> This symbol is defined only in debug version of msvc libs. Please check which version of msvc libs are used.

After rebase, I re-examined this problem and discovered that it was currently caused by the D (ldc2 - msvc-compat only) compiler. Missing `-lmsvcrtd.lib`, but zig add.
CI: https://github.com/kassane/bdwgc-d/actions/runs/8818670109
