### ISSUE TITLE
Redirect malloc_usable_size() in leak_detector.h

### ISSUE THREAD

**Issue by ivmai** [ivmai/bdwgc#644]
The task is to redirect `malloc_usable_size` (and `malloc_size`) to GC_size in leak_detector.h. (moved from #497)

https://man7.org/linux/man-pages/man3/malloc_usable_size.3.html describes it as: `size_t malloc_usable_size(void *_Nullable ptr);`

https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/malloc_size.3.html describes `size_t malloc_size(const void *ptr);`

Important notes: GC_size() should be extended to support nullptr as the argument; unclear what's the expected behavior of malloc_usable_size() for a non-heap argument.

**Comment by ivmai** [comment]
@fruffy wrote:
How much work would it be to implement this? We are currently running into crashes when using Z3 with BDWGC because they are using https://github.com/Z3Prover/z3/pull/6321.

I do not quite understand how we could fix this from the BDWGC without patching Z3 and removing those calls.

**Comment by ivmai** [comment]
It should not be difficult - just add to leak_detector.h
```
#undef malloc_usable_size
#define malloc_usable_size(p) GC_size(p)
```
However, GC_size() should be modified a bit to support nullptr argument.

**Comment by ivmai** [comment]
Note: macOS provides malloc_size(), we could also support it.

**Comment by ivmai** [comment]
> unclear what's the expected behavior of malloc_usable_size() for a non-heap argument.

Still unclear, I think we could silently return 0 if the pointer does no belong to a bdwgc heap.

**Comment by ivmai** [comment]
@fruffy, could you please make a PR?

**Comment by fruffy** [comment]
Some more context: https://github.com/Z3Prover/z3/issues/6890 seems to be a related issue. Z3 does not work well with third-party allocators. But I do not know how we could fix Z3 here. 

>@fruffy, could you please make a PR?

Can do. What should I change in the PR? Just add 

```
#undef malloc_usable_size
#define malloc_usable_size(p) GC_size(p)
```
?

**Comment by ivmai** [comment]
I've merged your commit and changed definition of GC_size. Please test.
Thank you!
