### ISSUE TITLE
Compilation with TCC fails on ARM macs

### ISSUE THREAD

**Issue by medvednikov** [ivmai/bdwgc#646]
```
tcc -c -I include/ gc.c
gc.c:14208: error: ARM asm not implemented.
```

We use an amalgamation of bdwgc:

https://github.com/vlang/v/blob/master/thirdparty/libgc/gc.c

Would it be be possible to replace asm with C inside an `#ifdef __TINYC__`?

Compilation on Linux and Intel macs works, this is a pure ARM mac + tcc issue.

Thanks

**Comment by ivmai** [comment]
It is OK to use GC_noop1 instead, like on Intel compiler. Please make a PR

**Comment by medvednikov** [comment]
Thanks! That indeed worked. Will submit a PR today.

**Comment by medvednikov** [comment]
https://github.com/ivmai/bdwgc/pull/647
