### ISSUE TITLE
How to use bdwgc in multi-thread program correctly?

### ISSUE THREAD

**Issue by butterunderflow** [ivmai/bdwgc#648]
Thank you for maintaining this amazing open-source library.

I am encountering an issue with using the bdwgc library in a multi-threaded program. Specifically, I would like to know if bdwgc supports multi-threading out-of-the-box, or if additional configuration is needed to properly allocate GC-managed memory.

I built bdwgc by cmake with the default configuration and attempted to run the following C++ program, which calls `GC_malloc_atomic` in multiple threads:

```cpp
#include <cstdio>
#include <thread>
#define GC_THREADS
#include "bdwgc/include/gc.h"

void only_alloc(int thread_id)
{
    for (auto i = 0; i < 10; i++)
    {
        printf("alloc 100 bytes at thread %d\n", thread_id);
        GC_malloc_atomic(100);
    }
    printf("only_alloc at thread %d finished\n", thread_id);
}

int main()
{
    std::thread threads[10];
    for (auto i = 0; i < 10; i++)
    {
        threads[i] = std::thread(only_alloc, i);
    }
    for (auto i = 0; i < 10; i++)
    {
        threads[i].join();
    }
}
```

However, the program crashes with the following warning messages:

```
alloc 100 bytes at thread 0
alloc 100 bytes at thread 1
Exclusion ranges overlap
alloc 100 bytes at thread 4
Exclusion ranges overlapalloc 100 bytes at thread 3

alloc 100 bytes at thread 7
Exclusion ranges overlapalloc 100 bytes at thread 2
Exclusion ranges overlap
Exclusion ranges overlapalloc 100 bytes at thread 8


alloc 100 bytes at thread 9
Exclusion ranges overlapExclusion ranges overlap

alloc 100 bytes at thread 6
Exclusion ranges overlap
[1]    20675 IOT instruction  ./main
```

To troubleshoot, I rebuilt bdwgc with additional debugging options (`enable_gc_debug` and `enable_gc_assertions`) enabled:

```bash
cmake .. -Denable_threads=ON -Denable_thread_local_alloc=ON -Denable_threads_discovery=ON -DCMAKE_USE_PTHREADS_INIT=true -Denable_gc_debug=ON -Denable_sigrt_signals=ON -Denable_gc_assertions=ON
```

While more kinds messages were printed, I am still unable to identify the cause of the problem:

Kind 1-`*** longjmp causes uninitialized stack frame ***`:
```
alloc 100 bytes at thread 0
alloc 100 bytes at thread 3
alloc 100 bytes at thread 4
alloc 100 bytes at thread 1
Exclusion ranges overlap*** longjmp causes uninitialized stack frame ***: terminated
*** longjmp causes uninitialized stack frame ***: terminated
alloc 100 bytes at thread 6

alloc 100 bytes at thread 5
Exclusion ranges overlapExclusion ranges overlap

alloc 100 bytes at thread 2
Exclusion ranges overlap
alloc 100 bytes at thread 7
Exclusion ranges overlap
[1]    26702 IOT instruction  ./main
```

Kind 2-`*** stack smashing detected ***`:
```
alloc 100 bytes at thread 1
alloc 100 bytes at thread 0
alloc 100 bytes at thread 4
alloc 100 bytes at thread 3
alloc 100 bytes at thread 2
Exclusion ranges overlapExclusion ranges overlap

Exclusion ranges overlap
*** stack smashing detected ***: terminated
*** stack smashing detected ***: terminated
[1]    29472 IOT instruction  ./main
```

I would appreciate any guidance on how to resolve this issue and correctly configure bdwgc for multi-threaded memory allocation. 

## PS
My test environment:
```sh
$ uname -a
Linux DESKTOP-D2VV7GU 5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by butterunderflow** [comment]
Oh I found I forget `GC_INIT()` before everything. After putting `GC_INIT()` at the beginning of `main`, and everything works.

**Comment by ivmai** [comment]
Yes, the collector should be initialized somehow before the first thread is created. Actually it should be done automatically but it does not happen in your case because probslby you use C++ primitive to create a thread. Also, gc.h should be included before thread header inclusion - this might help.
