### ISSUE TITLE
Build failed on NetBSD/sparc64, Makefile problem

### ISSUE THREAD

**Issue by tnn2** [ivmai/bdwgc#65]
Hi,
When building with ./configure && make on NetBSD/sparc64  the build failed with:
> make[1]: don't know how to make sparc_mach_dep.lo. Stop

This fixed the problem:
gc-7.4.2$ mv src/* .

(Why are the sparc assembler files alone in the src subdirectory?)

**Comment by ivmai** [comment]
Hello Tobias,
Could you please submit a patch for configure.
For historical reasons C files remain in rootdir while others (required only for some targets) are moved to src folder.
--
Mon, 16 Feb 2015, 11:04 +03:00 from Tobias Nygren <notifications@github.com>:
Hi,
When building with ./configure && make on NetBSD/sparc64  the build failed with:
>make[1]: don't know how to make sparc_mach_dep.lo. Stop
This fixed the problem:
gc-7.4.2$ mv src/* .
gc-7.4.2$ rmdir src
(Why are the sparc assembler files alone in the src subdirectory?)

**Comment by tnn2** [comment]
This patch fixes the problem. The Makefile.am change is probably not the correct fix but libtool does not put objects in the src directory and I couldn't figure out how to fix that.
https://gist.github.com/tnn2/b359756edf6b4094dfd0

**Comment by ivmai** [comment]
I have moved *.s files back to base folder (5e756d4d8d) - it should solve the issue
