### ISSUE TITLE
libc5 support code in os_dep.c breaks compilation with musl libc

### ISSUE THREAD

**Issue by doughdemon** [ivmai/bdwgc#66]
Trying to compile boehm-gc on a linux system with musl libc (http://musl-libc.org) fails:

    In file included from os_dep.c:47:0:
    /usr/include/asm/sigcontext.h:134:8: error: redefinition of 'struct _fpstate'
     struct _fpstate {
            ^
    In file included from /usr/include/signal.h:243:0,
                     from ./include/private/../gc_pthread_redirects.h:50,
                     from ./include/private/../gc.h:923,
                     from ./include/private/gc_priv.h:40,
                     from os_dep.c:17:
    /usr/include/bits/signal.h:37:16: note: originally defined here
     typedef struct _fpstate {
                    ^
    In file included from os_dep.c:47:0:
    /usr/include/asm/sigcontext.h:157:8: error: redefinition of 'struct sigcontext'
     struct sigcontext {
            ^
    In file included from /usr/include/signal.h:243:0,
                     from ./include/private/../gc_pthread_redirects.h:50,
                     from ./include/private/../gc.h:923,
                     from ./include/private/gc_priv.h:40,
                     from os_dep.c:17:
    /usr/include/bits/signal.h:49:8: note: originally defined here
     struct sigcontext {
            ^
    make[1]: *** [os_dep.lo] Error 1
    make: *** [all-recursive] Error 1

Because `__GLIBC__` is not declared the file assumes that musl is libc5 (!) and includes
https://github.com/ivmai/bdwgc/blob/0d147af1c4ecfe24c46952e059a78ad1e6b28553/os_dep.c#L44
a conflicting kernel header. Everything compiles fine after removing this line.

Is libc5 still relevant? If not, could this code be removed (and maybe the stuff around it cleaned up)? If it is still supported, I'll try to come up with an autoconf test. (However I have no idea how to get a libc5 system to test it.)

**Comment by ivmai** [comment]
Fixed in c887470.
Thanks for reporting the issue.
