### ISSUE TITLE
GC_is_visible produced wrong failure indication on Haiku if single-threaded build

### ISSUE THREAD

**Issue by ivmai** [ivmai/bdwgc#680]
Source: master (6dcc828d2)
Host: Haiku (R1)
How to reproduce: `./configure --disable-threads && make check`
gctest output:
```
Running on HAIKU/X86_64 target
Supported VDBs: manual default
GC_is_visible produced wrong failure indication
Test failed
```
Reported in PR #678 by @waddlesplash
Note: was also observed on old source, e.g. in gc-8.2.8

**Comment by ivmai** [comment]
Please rerun `make -j check` multiple times.

**Comment by waddlesplash** [comment]
Ran it at least 10 times, all passed.

**Comment by ivmai** [comment]
Okay, good, let me close it.
