### ISSUE TITLE
Upstream Serenity OS support

### ISSUE THREAD

**Issue by ivmai** [ivmai/bdwgc#685]
Existing patches location (for v8.2.8): https://github.com/SerenityOS/serenity/tree/master/Ports/bdwgc/patches
(Initially downstream support was added in https://github.com/SerenityOS/serenity/pull/12748)

**Comment by linusg** [comment]
I updated the port here: https://github.com/linusg/serenity/tree/ports-bdwgc-update

However I can't tell if everything works correctly because gctest doesn't seem to work with the current patches either. Probably needs to be tested with a real application instead.

**Comment by ivmai** [comment]
> However I can't tell if everything works correctly because gctest doesn't seem to work with the current patches either.

I have opened #688 (I don't have time to address it, maybe someone else will investigate the failure.)

**Comment by ivmai** [comment]
@linusg, please test https://github.com/ivmai/bdwgc/tree/release-8_2 branch, Serenity OS support has been backported. The upcoming stable release (v8.2.10) will be based on this branch.

**Comment by linusg** [comment]
I've updated the port to the latest release, dropping almost all patches: https://github.com/SerenityOS/serenity/pull/26318
