### ISSUE TITLE
Benchmarks for the Boehm Garbage Collector ?

### ISSUE THREAD

**Issue by leo-ard** [ivmai/bdwgc#692]
Hi ! 

I'm currently working on a garbage collection algorithm and are looking for benchmarks. I saw some benchmarks of the Boehm GC here : https://www.hboehm.info/gc/gc_bench/. However, these seem incomplete (only about 3 benchmark for the C API). I'm wondering if other micro-benchmarks exist for garbage collectors compatible with the Boehm API ? 

Thanks in advance !

**Comment by ivmai** [comment]
> I'm wondering if other micro-benchmarks exist for garbage collectors compatible with the Boehm API?

Unfortunately, I can't say we have micro-benchmarking in bdwgc. Some benchmarking exists among bdwgc tests, but their goal is primary do functional testing not benchmarking.

It is appreciated, of course, if someone adds the requested functionality;)

**Comment by leo-ard** [comment]
> Some benchmarking exists among bdwgc tests, but their goal is primary do functional testing not benchmarking.

Which tests are used for benchmarking (out of curiosity) ?

**Comment by ivmai** [comment]
The tests that could be used for benchmarking (by measurement of the total execution time):
* disclaim_bench
* gctest
* middletest
* realloctest
* weakmaptest
* treetest // exists only in master (i.e. v8.4.0 candidate)

**Comment by leo-ard** [comment]
Thanks ! I'll do a PR if this quest for benchmarking tests results in a usable benchmarking suite.
