### ISSUE TITLE
LIBTOOL undefined

### ISSUE THREAD

**Issue by blakemcbride** [ivmai/bdwgc#75]
On a current LinuxMint 64 with current git version of bdwgc & libatomic_ops:

...
$ autoreconf -vif
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: adding subdirectory libatomic_ops to autoreconf
autoreconf: Entering directory `libatomic_ops'
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:14: installing './compile'
configure.ac:5: installing './config.guess'
configure.ac:5: installing './config.sub'
configure.ac:8: installing './install-sh'
configure.ac:8: installing './missing'
src/Makefile.am:5: error: Libtool library used but 'LIBTOOL' is undefined
src/Makefile.am:5:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
src/Makefile.am:5:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
src/Makefile.am:5:   If 'LT_INIT' is in 'configure.ac', make sure
src/Makefile.am:5:   its definition is in aclocal's search path.
src/Makefile.am: installing './depcomp'
parallel-tests: installing './test-driver'
autoreconf: automake failed with exit status: 1
$ libtool --version
libtool (GNU libtool) 2.4.2
Written by Gordon Matzigkeit <gord@gnu.ai.mit.edu>, 1996

**Comment by ivmai** [comment]
LT_INIT is present in configure.ac (both bdwgc and libatomic_ops).

Can it be reproduce if libatomic_ops folder deleted from bdwgc?

**Comment by blakemcbride** [comment]
$ rm -rf *
$ git checkout --force
$ autoreconf -vif
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: subdirectory libatomic_ops not present
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
configure.ac:540: error: possibly undefined macro: AC_ENABLE_SHARED
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:615: error: possibly undefined macro: AC_PROG_LIBTOOL
autoreconf: /usr/bin/autoconf failed with exit status: 1

**Comment by ethe** [comment]
Got it on Ubuntu 15.10 64bit
```
 ➜  autoreconf -vif
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: adding subdirectory libatomic_ops to autoreconf
autoreconf: Entering directory `libatomic_ops'
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
src/Makefile.am:5: error: Libtool library used but 'LIBTOOL' is undefined
src/Makefile.am:5:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
src/Makefile.am:5:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
src/Makefile.am:5:   If 'LT_INIT' is in 'configure.ac', make sure
src/Makefile.am:5:   its definition is in aclocal's search path.
autoreconf: automake failed with exit status: 1

```

**Comment by ivmai** [comment]
configure.ac:
LT_INIT
# Note: If Autoconf reports that LIBTOOL (or AC_ENABLE_SHARED, or
# AC_PROG_LIBTOOL) is undefined, Libtool installation should be checked.

**Comment by ethe** [comment]
I've already fixed it, thanks.

**Comment by ivmai** [comment]
I've just run into this issue after installing libtool-2.4.6 built from sources - .m4 files are installed to /usr/local/share/aclocal by default (instead of /usr/share/aclocal). The quick (dirty) workaround is to run: sudo cp /usr/local/share/aclocal/* /usr/share/aclocal/

**Comment by glicerico** [comment]
The quick (dirty) copying fixed it for me ;)
