### ISSUE TITLE
Deadlock due to race when using thread discovery and parallel GC on Darwin

### ISSUE THREAD

**Issue by ntherning** [ivmai/bdwgc#78]
We ran into a deadlock when we enabled thread discovery in RoboVM. See robovm/bdwgc@0458ff8c3cc04376bb4584de7729e6dbb6384bad and robovm/robovm#1113. Feel free to cherry-pick this or let me know if you want me to submit this as a PR. It compiles and runs fine for OSX/iOS x86/ARM 32/64-bit and Linux x86 32/64-bit. Reproducing is easy on OSX. Just compile a simple C program which calls `GC_INIT()` linked with a `libgc` compiled with `--enable-parallel-mark=yes` and `-DGC_DISCOVER_TASK_THREADS`. Run that program many times (I had to run it > 100 times) and it will eventually deadlock with call stacks similar to the one in robovm/robovm#1113.

**Comment by ivmai** [comment]
Fixed in 0ca6d3f
