### ISSUE TITLE
Bug: the last allocated object can not be finalized? Shall we clear the stack after we construct the gc_cleanup object?

### ISSUE THREAD

**Issue by taigacon** [ivmai/bdwgc#85]
Here is my test source:
```c++
#include <vector>

#include "gc_cpp.h"

std::vector<int> calc;
class AA : virtual public GC_NS_QUALIFY(gc_cleanup)
{
public:
	int c;
	static int idx;
	AA()
	{
		c = idx++;
		calc.push_back(c);
	}
	virtual ~AA()
	{
		calc.erase(std::find(calc.begin(), calc.end(), c));
		idx--;
		return;
	}
};
int AA::idx = 0;

int main()
{
	GC_INIT();
	for (int i = 0; i < 256; i++)
	{
		AA* aaa = new AA();
	}

	GC_gcollect();
	GC_invoke_finalizers();
	int c = AA::idx;
	int d = calc.size();
	int id = calc[0];
	return(0); //break point
}
```

When breaked on return, I saw the value of c is 1, not 0 as expected. d is 1 as well. The ID of the left object is 255 which means the latest allocated object.
My host infomation is AMD64-windows 6.2, and the program is in X86 mode.
I use CMake 3.2.1 to configure libgc of latest master branch, and only enabled 'enable_cplusplus' flag.

**Comment by taigacon** [comment]
All right, maybe gc think the 'aaa' variable is still using in stack. If I put allocation in a independent function, everything is fine.

**Comment by taigacon** [comment]
All right, EAX and ECX still hold the address of the latest allocated object ( in Debug mode ). Shall we clear all the registers before we call GC_gccollect() ?

**Comment by taigacon** [comment]
See that ESP+4 to ESP+12 stores the address unexpectedly. And here is the asm of gc_cleanup::gc_cleanup() in Debug mode.

![1](https://cloud.githubusercontent.com/assets/7021624/12093562/a3ba1086-b33e-11e5-85d2-317d83d9a513.png)
![2](https://cloud.githubusercontent.com/assets/7021624/12093563/a3fe9242-b33e-11e5-84a5-ee7e9376ab9c.png)

**Comment by hboehm** [comment]
My feeling is that this is a judgment call.  If there is an easy way to
clean more dead registers or stack locations at minimal cost, then it may
be worth doing.  But a conservative collector is never going to guarantee
that "all dead objects" will be collected.  Even for a non-conservative GC,
that's a tough notion to define, and Java doesn't try.  No code should be
relying on running a finalizer at a certain point.

In this particular case, it's not clear to me there is a cheap/easy
solution.  Especially if this only happens in debug mode.

I would generally be more concerned with stack locations that may not be
overwritten for a long time than with registers that might keep an object
live for a single GC.

**Comment by rptb1** [comment]
@hboehm writes:
> Even for a non-conservative GC, that's a tough notion to define

Indeed. See http://www.memorymanagement.org/glossary/d.html#term-dead
> It is not possible, in general, for garbage collectors to determine exactly which objects are dead and which are live. Instead, they use some approximation to detect objects that are provably dead, such as those that are unreachable.

And also http://www.ravenbrook.com/project/mps/master/manual/html/topic/finalization.html#cautions
> Don’t rely on finalization for your program to work. Treat it as an optimization that enables the freeing of resources that the garbage collector can prove are unreachable.

This is a message I've been repeating for many years :)
