### ISSUE TITLE
test_cpp.cc FAILs with GCC and -std=gnu++14

### ISSUE THREAD

**Issue by rguenth** [ivmai/bdwgc#87]
GCC 6 defaults to -std=gnu++14 which makes test_cpp.cc FAIL with

Assuming 10 iters
Starting iteration 1
**\* Error in `/home/abuild/osc-build-root/home/abuild/rpmbuild/BUILD/gc-7.4.2/.libs/test_cpp': free(): invalid pointer: 0x00000000006f8fe0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7364f)[0x7ffff71ac64f]
/lib64/libc.so.6(+0x78eae)[0x7ffff71b1eae]
/lib64/libc.so.6(+0x79b87)[0x7ffff71b2b87]
/home/abuild/osc-build-root/home/abuild/rpmbuild/BUILD/gc-7.4.2/.libs/tes

at

```
    for (i = 0; i < 1000; i++) {
        A* a = (A*) Undisguise( as[ i ] );
        B* b = (B*) Undisguise( bs[ i ] );
        a->Test( i );
        delete a;
```

^^^^

I suspect this has sth to do with the more recent standards allocator changes and the wrapping
no longer working properly.  It works when specifying -std=gnu++98 manually (with GCC 6).

I have tested gc 7.4.2 sofar.

**Comment by ivmai** [comment]
This should be now fixed by 3150107d3e12b06764e3fd4598cef0652e127b3c
