### ISSUE TITLE
"Stable" Version 7.2f Fails to Build on openSUSE Linux

### ISSUE THREAD

**Issue by martinvahi** [ivmai/bdwgc#90]
[gc-7.2f.tar.gz](http://www.hboehm.info/gc/gc_source/gc-7.2f.tar.gz)

    ts2@linux-0fiz:~/m_local/bin_p/Sage/kompileerimine$ rm -fr ./gc-7.2
    ts2@linux-0fiz:~/m_local/bin_p/Sage/kompileerimine$ sha256sum ./gc-7.2f.tar 
    84b346c7399ac18be4d7dabc350038d608d447e94fc88a6208d23929f333acce  ./gc-7.2f.tar
    ts2@linux-0fiz:~/m_local/bin_p/Sage/kompileerimine$ tar -xf ./gc-7.2f.tar 
    ts2@linux-0fiz:~/m_local/bin_p/Sage/kompileerimine$ cd gc-7.2/
    ts2@linux-0fiz:~/m_local/bin_p/Sage/kompileerimine/gc-7.2$ ls
    aclocal.m4                  dbg_mlc.c                  Makefile.am                     PCR-Makefile
    allchblk.c                  depcomp                    Makefile.direct                 pthread_start.c
    alloc.c                     digimars.mak               Makefile.dj                     pthread_stop_world.c
    alpha_mach_dep.S            doc                        Makefile.DLLs                   pthread_support.c
    autogen.sh                  dyn_load.c                 Makefile.in                     ptr_chck.c
    backgraph.c                 EMX_MAKEFILE               malloc.c                        README.QUICK
    BCC_MAKEFILE                extra                      mallocx.c                       real_malloc.c
    bdw-gc.pc.in                finalize.c                 mark.c                          reclaim.c
    blacklst.c                  gc_cpp.cc                  mark_rts.c                      rs6000_mach_dep.s
    build_atomic_ops.sh         gc_cpp.cpp                 mips_sgi_mach_dep.s             SMakefile.amiga
    build_atomic_ops.sh.cygwin  gc_dlopen.c                mips_ultrix_mach_dep.s          sparc_mach_dep.S
    callprocs                   gcj_mlc.c                  misc.c                          sparc_netbsd_mach_dep.s
    ChangeLog                   gc.mak                     missing                         sparc_sunos4_mach_dep.s
    checksums.c                 headers.c                  mkinstalldirs                   specific.c
    CMakeLists.txt              ia64_save_regs_in_stack.s  new_hblk.c                      stubborn.c
    compile                     include                    NT_MAKEFILE                     test-driver
    config.guess                install-sh                 NT_STATIC_THREADS_MAKEFILE      tests
    config.sub                  libatomic_ops              NT_X64_STATIC_THREADS_MAKEFILE  thread_local_alloc.c
    configure                   ltmain.sh                  NT_X64_THREADS_MAKEFILE         typd_mlc.c
    configure.ac                m4                         obj_map.c                       WCC_MAKEFILE
    configure.host              Mac_files                  OS2_MAKEFILE                    win32_threads.c
    cord                        mach_dep.c                 os_dep.c
    darwin_stop_world.c         MacProjects.sit.hqx        pcr_interface.c
    ts2@linux-0fiz:~/m_local/bin_p/Sage/kompileerimine/gc-7.2$ ./autogen.sh 
    + aclocal
    + autoconf
    + autoheader
    + automake -ac
    + libtoolize --automake --force
    + set +x
    
    Ready to run './configure'.
    
    ts2@linux-0fiz:~/m_local/bin_p/Sage/kompileerimine/gc-7.2$ ./configure --prefix=/home/ts2/m_local/bin_p/Sage/paigaldatult/boehm_demers_weiser_garbage_collector --with-gnu-ld --enable-cplusplus --enable-large-config --enable-handle-fork 
    configure: loading site script /usr/share/site/x86_64-unknown-linux-gnu
    checking build system type... x86_64-unknown-linux-gnu
    checking host system type... x86_64-unknown-linux-gnu
    checking target system type... x86_64-unknown-linux-gnu
    checking GC version numbers... major=7 minor=2 
    checking for a BSD-compatible install... /usr/bin/install -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
    checking for gawk... gawk
    checking whether make sets $(MAKE)... yes
    checking whether make supports nested variables... yes
    checking whether to enable maintainer-specific portions of Makefiles... no
    checking for style of include used by make... GNU
    checking for gcc... gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables... 
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking dependency style of gcc... gcc3
    checking whether gcc and cc understand -c and -o together... yes
    checking whether we are using the GNU C++ compiler... yes
    checking whether g++ accepts -g... yes
    checking dependency style of g++... gcc3
    checking dependency style of gcc... gcc3
    checking for thread model used by GCC... posix
    checking for inline... inline
    checking for pthread_self in -lpthread... yes
    configure: WARNING: "Explicit GC_INIT() calls may be required."
    checking for xlc... no
    checking whether gcc supports -fno-strict-aliasing... yes
    checking for dlopen in -ldl... yes
    checking whether to build shared libraries... yes
    checking which machine-dependent code should be used... 
    checking how to print strings... printf
    checking for a sed that does not truncate output... /usr/bin/sed
    checking for grep that handles long lines and -e... /usr/bin/grep
    checking for egrep... /usr/bin/grep -E
    checking for fgrep... /usr/bin/grep -F
    checking for ld used by gcc... /usr/x86_64-suse-linux/bin/ld
    checking if the linker (/usr/x86_64-suse-linux/bin/ld) is GNU ld... yes
    checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
    checking the name lister (/usr/bin/nm -B) interface... BSD nm
    checking whether ln -s works... yes
    checking the maximum length of command line arguments... 1572864
    checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
    checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
    checking for /usr/x86_64-suse-linux/bin/ld option to reload object files... -r
    checking for objdump... objdump
    checking how to recognize dependent libraries... pass_all
    checking for dlltool... no
    checking how to associate runtime and link libraries... printf %s\n
    checking for ar... ar
    checking for archiver @FILE support... @
    checking for strip... strip
    checking for ranlib... ranlib
    checking command to parse /usr/bin/nm -B output from gcc object... ok
    checking for sysroot... no
    checking for mt... mt
    checking if mt is a manifest tool... no
    checking how to run the C preprocessor... gcc -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for dlfcn.h... yes
    checking for objdir... .libs
    checking if gcc supports -fno-rtti -fno-exceptions... no
    checking for gcc option to produce PIC... -fPIC -DPIC
    checking if gcc PIC flag -fPIC -DPIC works... yes
    checking if gcc static flag -static works... yes
    checking if gcc supports -c -o file.o... yes
    checking if gcc supports -c -o file.o... (cached) yes
    checking whether the gcc linker (/usr/x86_64-suse-linux/bin/ld -m elf_x86_64) supports shared libraries... yes
    checking whether -lc should be explicitly linked in... no
    checking dynamic linker characteristics... GNU/Linux ld.so
    checking how to hardcode library paths into programs... immediate
    checking whether stripping libraries is possible... yes
    checking if libtool supports shared libraries... yes
    checking whether to build shared libraries... yes
    checking whether to build static libraries... yes
    checking how to run the C++ preprocessor... g++ -E
    checking for ld used by g++... /usr/x86_64-suse-linux/bin/ld -m elf_x86_64
    checking if the linker (/usr/x86_64-suse-linux/bin/ld -m elf_x86_64) is GNU ld... yes
    checking whether the g++ linker (/usr/x86_64-suse-linux/bin/ld -m elf_x86_64) supports shared libraries... yes
    checking for g++ option to produce PIC... -fPIC -DPIC
    checking if g++ PIC flag -fPIC -DPIC works... yes
    checking if g++ static flag -static works... yes
    checking if g++ supports -c -o file.o... yes
    checking if g++ supports -c -o file.o... (cached) yes
    checking whether the g++ linker (/usr/x86_64-suse-linux/bin/ld -m elf_x86_64) supports shared libraries... yes
    checking dynamic linker characteristics... (cached) GNU/Linux ld.so
    checking how to hardcode library paths into programs... immediate
    checking whether Solaris gcc optimization fix is necessary... no
    checking sys/dg_sys_info.h usability... no
    checking sys/dg_sys_info.h presence... no
    checking for sys/dg_sys_info.h... no
    checking for pkg-config... /usr/bin/pkg-config
    checking pkg-config is at least version 0.9.0... yes
    checking for ATOMIC_OPS... no
    checking which libatomic_ops to use... internal
    checking that generated files are newer than configure... done
    configure: creating ./config.status
    config.status: creating Makefile
    config.status: creating bdw-gc.pc
    config.status: creating include/private/config.h
    config.status: executing depfiles commands
    config.status: executing libtool commands
    config.status: executing default commands
    === configuring in libatomic_ops (/home/ts2/m_local/bin_p/Sage/kompileerimine/gc-7.2/libatomic_ops)
    configure: running /bin/sh ./configure --disable-option-checking '--prefix=/home/ts2/m_local/bin_p/Sage/paigaldatult/boehm_demers_weiser_garbage_collector'  '--with-gnu-ld' '--enable-cplusplus' '--enable-large-config' '--enable-handle-fork' 'CC=gcc' 'CFLAGS= -mtune=native -ftree-vectorize ' 'CXX=g++' 'CXXFLAGS= -mtune=native -ftree-vectorize ' --cache-file=/dev/null --srcdir=.
    configure: loading site script /usr/share/site/x86_64-unknown-linux-gnu
    checking build system type... x86_64-unknown-linux-gnu
    checking host system type... x86_64-unknown-linux-gnu
    checking target system type... x86_64-unknown-linux-gnu
    checking for a BSD-compatible install... /usr/bin/install -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
    checking for gawk... gawk
    checking whether make sets $(MAKE)... yes
    checking whether make supports nested variables... yes
    checking for ranlib... ranlib
    checking for style of include used by make... GNU
    checking for gcc... gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables... 
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking whether gcc understands -c and -o together... yes
    checking dependency style of gcc... gcc3
    checking dependency style of gcc... gcc3
    checking how to run the C preprocessor... gcc -E
    checking for grep that handles long lines and -e... /usr/bin/grep
    checking for egrep... /usr/bin/grep -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for stdlib.h... (cached) yes
    checking for unistd.h... (cached) yes
    checking for sys/param.h... yes
    checking for getpagesize... yes
    checking for working mmap... yes
    checking for ANSI C header files... (cached) yes
    checking for PIC compiler flag... -fPIC
    checking whether gcc -fPIC causes __PIC__ definition... yes
    checking for pthread_self in -lpthread... yes
    checking that generated files are newer than configure... done
    configure: creating ./config.status
    config.status: creating Makefile
    config.status: creating pkgconfig/atomic_ops.pc
    config.status: creating pkgconfig/atomic_ops-uninstalled.pc
    config.status: creating doc/Makefile
    config.status: creating src/Makefile
    config.status: creating src/atomic_ops/Makefile
    config.status: creating src/atomic_ops/sysdeps/Makefile
    config.status: creating tests/Makefile
    config.status: creating src/config.h
    config.status: executing depfiles commands
    config.status: executing default commands
    ts2@linux-0fiz:~/m_local/bin_p/Sage/kompileerimine/gc-7.2$ nice -n20 make
    make[1]: Entering directory '/opt/2dot7TiB_k8vaketas/ts2/mittevarundatav/_home/m_local/bin_p/Sage/kompileerimine/gc-7.2'
    depbase=`echo allchblk.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
    /bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H   -I./include -I./include -I./libatomic_ops/src -I./libatomic_ops/src  -fexceptions -mtune=native -ftree-vectorize  -fno-strict-aliasing -MT allchblk.lo -MD -MP -MF $depbase.Tpo -c -o allchblk.lo allchblk.c &&\
    mv -f $depbase.Tpo $depbase.Plo
    libtool: Version mismatch error.  This is libtool 2.4.2, but the
    libtool: definition of this LT_INIT comes from libtool 2.4.2.418.
    libtool: You should recreate aclocal.m4 with macros from libtool 2.4.2
    libtool: and run autoconf again.
    Makefile:1377: recipe for target 'allchblk.lo' failed
    make[1]: *** [allchblk.lo] Error 63
    make[1]: Leaving directory '/opt/2dot7TiB_k8vaketas/ts2/mittevarundatav/_home/m_local/bin_p/Sage/kompileerimine/gc-7.2'
    Makefile:1517: recipe for target 'all-recursive' failed
    make: *** [all-recursive] Error 1
    ts2@linux-0fiz:~/m_local/bin_p/Sage/kompileerimine/gc-7.2$ uname -a
    Linux linux-0fiz 3.16.7-29-desktop #1 SMP PREEMPT Fri Oct 23 00:46:04 UTC 2015 (6be6a97) x86_64 x86_64 x86_64 GNU/Linux
    ts2@linux-0fiz:~/m_local/bin_p/Sage/kompileerimine/gc-7.2$ gcc --version
    gcc (SUSE Linux) 4.8.3 20140627 [gcc-4_8-branch revision 212064]
    Copyright (C) 2013 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    
    ts2@linux-0fiz:~/m_local/bin_p/Sage/kompileerimine/gc-7.2$ date
    Sat Feb  6 03:00:15 EET 2016
    ts2@linux-0fiz:~/m_local/bin_p/Sage/kompileerimine/gc-7.2$ echo $CFLAGS
    -mtune=native -ftree-vectorize
    ts2@linux-0fiz:~/m_local/bin_p/Sage/kompileerimine/gc-7.2$ echo $CXXFLAGS
    -mtune=native -ftree-vectorize
    ts2@linux-0fiz:~/m_local/bin_p/Sage/kompileerimine/gc-7.2$ echo $CC
    gcc
    ts2@linux-0fiz:~/m_local/bin_p/Sage/kompileerimine/gc-7.2$ echo $CXX
    g++
    ts2@linux-0fiz:~/m_local/bin_p/Sage/kompileerimine/gc-7.2$

**Comment by martinvahi** [comment]
In stead of just "complaining" I offer the attached file (~15MiB) for packaging the new stable version. 


[2016_02_06_Boehm-Demers–Weiser_Garbage_Collector_edge.zip](https://github.com/ivmai/bdwgc/files/120113/2016_02_06_Boehm-Demers.Weiser_Garbage_Collector_edge.zip)

The version in the ZIP-file builds fine on openSUSE.
The Bash scripts in there archive the previously downloaded versions 
of the source and the previously compiled version before overwriting anything.

**Comment by ivmai** [comment]
Thank you. I will pay attention to this on releasing gc7.2g

**Comment by ivmai** [comment]
I have downgraded libtool to latest official release both in bdwgc and libatomic_ops (in release-7_2 branch). See commits: 75f4f19 and https://github.com/ivmai/libatomic_ops/commit/aae1c04a8b6fea34a351c666ca4bc334ace5f973
