### ISSUE TITLE
GC_realloc should call GC_free if pointer is not NULL and size is 0

### ISSUE THREAD

**Issue by funny-falcon** [ivmai/bdwgc#96]
Most implementations of `realloc` calls `free` if pointer is not NULL and size is zero:

- http://linux.die.net/man/3/realloc
  > if size is equal to zero, and ptr is not NULL, then the call is equivalent to free(ptr).

- https://msdn.microsoft.com/en-us/library/xbebcx7d.aspx
  > If size is zero, then the block pointed to by memblock is freed; the return value is NULL, and memblock is left pointing at a freed block.

- http://www.cplusplus.com/reference/cstdlib/realloc/
  > C90: Otherwise, if size is zero, the memory previously allocated at ptr is deallocated as if a call to free was made, and a null pointer is returned.
  > C99/C11: If size is zero, the return value depends on the particular library implementation: it may either be a null pointer or some other location that shall not be dereferenced.

Notable exceptions are:

- https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man3/realloc.3.html
  > If size is zero and ptr is not NULL, a new, minimum sized object is allocated and the original object is freed.

- https://www.freebsd.org/cgi/man.cgi?realloc(3) -  no special comments at all

As an alternative, pointer to fixed position could be returned.

**Comment by funny-falcon** [comment]
Main reason: when used as leak detector, a lot of results of `realloc(ptr, 0)` are detected as leakage.
Secondary reason is just performance issue.

**Comment by ivmai** [comment]
Agree. I will change and refine the documentation.

**Comment by ivmai** [comment]
Fixed. See b929f72
