### ISSUE TITLE
Support for Haiku Platform

### ISSUE THREAD

**Issue by CodeforEvolution** [ivmai/bdwgc#97]
Support for the operating system Haiku, the open source successor to beos.

Main Homepage:
https://www.haiku-os.org

Development Websites:
https://dev.haiku-os.org/
https://www.haiku-os.org/development

**Comment by ivmai** [comment]
BeOS/x86 should be supported. Probably not tested for a long time.
Anyway, the patch is welcomed.

**Comment by ivmai** [comment]
Initial support of Haiku/amd64: 847927f

Would be good to test it.

Related topic: haikuports/haikuports#2215

**Comment by ivmai** [comment]
Fork handling (--enable-handle-fork) is not supported because of some bug in Haiku (as of hrev51798): pthread_mutex_unlock (called from GC_release_mark_lock called from fork_parent_proc) returns ESIGPARM.

**Comment by ivmai** [comment]
Besides the above bug, there are 2 more bugs in Haiku (for which I've created workarounds in bdwgc):
* sem_wait sometimes returns EACCES (the workaround is to retry)
* pthread_join returns ESRCH if too many threads were created (sample: tests/subthread_create.c compiled with -D GC_NO_THREAD_REDIRECTS).
